import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:stream_chat/stream_chat.dart';
import 'package:stream_chat_persistence/src/db/drift_chat_database.dart';
import 'package:stream_chat_persistence/src/entity/channel_queries.dart';
import 'package:stream_chat_persistence/src/entity/channel_queries_metadata.dart';
import 'package:stream_chat_persistence/src/entity/channels.dart';
import 'package:stream_chat_persistence/src/entity/users.dart';
import 'package:stream_chat_persistence/src/mapper/mapper.dart';

part 'channel_query_dao.g.dart';

/// The Data Access Object for operations in [ChannelQueries] table.
@DriftAccessor(
    tables: [ChannelQueries, ChannelQueriesMetadata, Channels, Users])
class ChannelQueryDao extends DatabaseAccessor<DriftChatDatabase>
    with _$ChannelQueryDaoMixin {
  /// Creates a new channel query dao instance
  ChannelQueryDao(super.db);

  String _computeHash(Filter? filter) {
    if (filter == null) {
      return 'allchannels';
    }
    final hash = base64Encode(utf8.encode('filter: ${jsonEncode(filter)}'));
    return hash;
  }

  String _computeHashForPredefined(
    String filterName,
    Map<String, Object?>? filterValues,
    Map<String, Object?>? sortValues,
  ) {
    final payload = <String, Object?>{
      'name': filterName,
      if (filterValues != null) 'filter_values': filterValues,
      if (sortValues != null) 'sort_values': sortValues,
    };
    return 'p:${base64Encode(utf8.encode(jsonEncode(payload)))}';
  }

  /// Update list of channel queries
  /// If [clearQueryCache] is true before the insert
  /// the list of matching rows will be deleted
  Future<void> updateChannelQueries(
    Filter? filter,
    List<String> cids, {
    bool clearQueryCache = false,
  }) async =>
      transaction(() async {
        final hash = _computeHash(filter);
        if (clearQueryCache) {
          await batch((it) {
            it.deleteWhere<ChannelQueries, ChannelQueryEntity>(
              channelQueries,
              (c) => c.queryHash.equals(hash),
            );
          });
        }

        await batch((it) {
          it.insertAllOnConflictUpdate(
            channelQueries,
            cids
                .map((cid) =>
                    ChannelQueryEntity(queryHash: hash, channelCid: cid))
                .toList(),
          );
        });
      });

  /// Update list of channel queries for a predefined-filter query.
  ///
  /// Writes the cached cids to [ChannelQueries] and the server-resolved
  /// [filter] and [sort] to [ChannelQueriesMetadata] in a single transaction.
  /// If [clearQueryCache] is true, prior cids and metadata for this query are
  /// deleted before the insert.
  Future<void> updateChannelQueriesByPredefinedFilter(
    String filterName,
    List<String> cids, {
    required Filter filter,
    required SortOrder<ChannelState> sort,
    Map<String, Object?>? filterValues,
    Map<String, Object?>? sortValues,
    bool clearQueryCache = false,
  }) async =>
      transaction(() async {
        final hash =
            _computeHashForPredefined(filterName, filterValues, sortValues);

        if (clearQueryCache) {
          await batch((it) {
            it
              ..deleteWhere<ChannelQueries, ChannelQueryEntity>(
                channelQueries,
                (c) => c.queryHash.equals(hash),
              )
              ..deleteWhere<ChannelQueriesMetadata, ChannelQueryMetadataEntity>(
                channelQueriesMetadata,
                (m) => m.queryHash.equals(hash),
              );
          });
        }

        await batch((it) {
          it
            ..insertAllOnConflictUpdate(
              channelQueries,
              cids
                  .map((cid) =>
                      ChannelQueryEntity(queryHash: hash, channelCid: cid))
                  .toList(),
            )
            ..insert(
              channelQueriesMetadata,
              ChannelQueryMetadataEntity(
                queryHash: hash,
                filter: filter,
                sort: sort,
              ),
              mode: InsertMode.insertOrReplace,
            );
        });
      });

  /// Get the CIDs stored under the hash generated by [filter].
  Future<List<String>> getCachedChannelCids(Filter? filter) {
    final hash = _computeHash(filter);
    return (select(channelQueries)..where((c) => c.queryHash.equals(hash)))
        .map((c) => c.channelCid)
        .get();
  }

  /// Get list of channels by filter, sort and paginationParams
  Future<List<ChannelModel>> getChannels({Filter? filter}) async {
    final cachedChannelCids = await getCachedChannelCids(filter);
    final query = select(channels)..where((c) => c.cid.isIn(cachedChannelCids));

    final cachedChannels = await query.join([
      leftOuterJoin(users, channels.createdById.equalsExp(users.id)),
    ]).map((row) {
      final createdByEntity = row.readTableOrNull(users);
      final channelEntity = row.readTable(channels);
      return channelEntity.toChannelModel(createdBy: createdByEntity?.toUser());
    }).get();

    return cachedChannels;
  }

  /// Get the cached channels and persisted filter/sort spec for a
  /// predefined-filter query.
  ///
  /// Returns a record `(channels, filter, sort)`. The two
  /// spec fields are null when no metadata row exists for this query.
  Future<(List<ChannelModel>, Filter?, SortOrder<ChannelState>?)>
      getChannelsAndSpecByPredefinedFilter(
    String filterName, {
    Map<String, Object?>? filterValues,
    Map<String, Object?>? sortValues,
  }) async {
    final hash =
        _computeHashForPredefined(filterName, filterValues, sortValues);

    final cidsQuery = (select(channelQueries)
          ..where((c) => c.queryHash.equals(hash)))
        .map((c) => c.channelCid)
        .get();

    final metadataQuery = (select(channelQueriesMetadata)
          ..where((m) => m.queryHash.equals(hash)))
        .getSingleOrNull();

    final (cachedCids, metadata) = await (cidsQuery, metadataQuery).wait;

    if (cachedCids.isEmpty) {
      return (const <ChannelModel>[], metadata?.filter, metadata?.sort);
    }

    final cachedChannels =
        await (select(channels)..where((c) => c.cid.isIn(cachedCids))).join([
      leftOuterJoin(users, channels.createdById.equalsExp(users.id)),
    ]).map((row) {
      final createdByEntity = row.readTableOrNull(users);
      final channelEntity = row.readTable(channels);
      return channelEntity.toChannelModel(
        createdBy: createdByEntity?.toUser(),
      );
    }).get();

    return (cachedChannels, metadata?.filter, metadata?.sort);
  }
}
