import 'package:stream_core/stream_core.dart' show PatternMatching, Result;

import '../../open_api/api.dart' as api;
import '../core/models/response/add_user_group_members_response.dart';
import '../core/models/response/create_user_group_response.dart';
import '../core/models/response/get_user_group_response.dart';
import '../core/models/response/list_user_groups_response.dart';
import '../core/models/response/remove_user_group_members_response.dart';
import '../core/models/response/search_user_groups_response.dart';
import '../core/models/response/update_user_group_response.dart';
import 'mapper/result_mapper.dart';
import 'mapper/user_groups_mapper.dart';

/// Repository dedicated to user group operations.
class UserGroupsRepository {
  /// Initialize a new user groups repository.
  const UserGroupsRepository(this._api);

  final api.DefaultApi _api;

  /// Lists user groups with cursor-based pagination.
  ///
  /// [idGt] and [createdAtGt] are cursors: each returns only the groups
  /// ordering after the value given.
  Future<Result<ListUserGroupsResponse>> listUserGroups({
    int? limit,
    String? idGt,
    DateTime? createdAtGt,
    String? teamId,
  }) async {
    final result = await _api.listUserGroups(
      limit: limit,
      idGt: idGt,
      createdAtGt: createdAtGt?.toUtc().toIso8601String(),
      teamId: teamId,
    );

    return result.map((response) => response.toModel());
  }

  /// Searches user groups by name prefix (autocomplete).
  Future<Result<SearchUserGroupsResponse>> searchUserGroups(
    String query, {
    int? limit,
    String? nameGt,
    String? idGt,
    String? teamId,
  }) async {
    final result = await _api.searchUserGroups(
      query: query,
      limit: limit,
      nameGt: nameGt,
      idGt: idGt,
      teamId: teamId,
    );

    return result.map((response) => response.toModel());
  }

  /// Gets a user group by ID, including its members.
  Future<Result<GetUserGroupResponse>> getUserGroup(
    String id, {
    String? teamId,
  }) async {
    final result = await _api.getUserGroup(id: id, teamId: teamId);
    return result.map((response) => response.toModel());
  }

  /// Creates a new user group, optionally with initial members.
  ///
  /// [id] is generated by the server when omitted.
  Future<Result<CreateUserGroupResponse>> createUserGroup(
    String name, {
    String? id,
    String? description,
    String? teamId,
    List<String>? memberIds,
  }) async {
    final result = await _api.createUserGroup(
      createUserGroupRequest: api.CreateUserGroupRequest(
        name: name,
        id: id,
        description: description,
        teamId: teamId,
        memberIds: memberIds,
      ),
    );

    return result.map((response) => response.toModel());
  }

  /// Updates a user group's name and/or description.
  ///
  /// At least one of [name] / [description] must be provided. Passing
  /// `description: ''` clears the description; passing `null` (or omitting)
  /// leaves it unchanged.
  ///
  /// [teamId] scopes the lookup; a group's team cannot be changed.
  Future<Result<UpdateUserGroupResponse>> updateUserGroup(
    String id, {
    String? name,
    String? description,
    String? teamId,
  }) async {
    final result = await _api.updateUserGroup(
      id: id,
      updateUserGroupRequest: api.UpdateUserGroupRequest(
        name: name,
        description: description,
        teamId: teamId,
      ),
    );

    return result.map((response) => response.toModel());
  }

  /// Deletes a user group and all its memberships.
  Future<Result<void>> deleteUserGroup(
    String id, {
    String? teamId,
  }) async {
    final result = await _api.deleteUserGroup(id: id, teamId: teamId);
    return result.ignoreValue();
  }

  /// Adds members to a user group. All user IDs must exist
  /// (operation is all-or-nothing).
  ///
  /// [asAdmin] defaults to `false` — a regular member — when not given.
  Future<Result<AddUserGroupMembersResponse>> addUserGroupMembers(
    String id,
    List<String> memberIds, {
    bool? asAdmin,
    String? teamId,
  }) async {
    final result = await _api.addUserGroupMembers(
      id: id,
      addUserGroupMembersRequest: api.AddUserGroupMembersRequest(
        memberIds: memberIds,
        asAdmin: asAdmin,
        teamId: teamId,
      ),
    );

    return result.map((response) => response.toModel());
  }

  /// Removes members from a user group. User IDs not currently members
  /// are silently ignored.
  Future<Result<RemoveUserGroupMembersResponse>> removeUserGroupMembers(
    String id,
    List<String> memberIds, {
    String? teamId,
  }) async {
    final result = await _api.removeUserGroupMembers(
      id: id,
      removeUserGroupMembersRequest: api.RemoveUserGroupMembersRequest(
        memberIds: memberIds,
        teamId: teamId,
      ),
    );

    return result.map((response) => response.toModel());
  }
}
