name: example
description: A new Flutter project.
publish_to: "none"
version: 2.1.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_app_badger: ^1.3.0
  flutter:
    sdk: flutter
  stream_chat_flutter:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat_flutter
  stream_chat_persistence:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat_persistence
  stream_chat_localizations:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat_localizations
  flutter_local_notifications: ^9.0.0
  flutter_svg: ^1.0.3
  flutter_secure_storage: ^5.0.2
  yaml: ^3.1.0
  uuid: ^3.0.5
  streaming_shared_preferences: ^2.0.0
  lottie: ^1.2.1
  collection: ^1.15.0
  sentry_flutter: ^6.5.0
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  test: any

dependency_overrides:
  stream_chat:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat
  stream_chat_flutter_core:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat_flutter_core
  stream_chat_flutter:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat_flutter

flutter:
  assets:
    - assets/
    - pubspec.lock
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/android_icon.png"
  image_path_ios: "assets/ios_icon.png"
