name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.5.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_app_badger: ^1.1.2
  flutter:
    sdk: flutter
  stream_chat_flutter:
    path: ../../../stream-chat-flutter/packages/stream_chat_flutter
  stream_chat_persistence:
    path: ../../../stream-chat-flutter/packages/stream_chat_persistence
  flutter_local_notifications: ^2.0.2
  flutter_svg: ^0.19.3
  flutter_secure_storage: ^3.3.5
  yaml: ^2.2.1
  uuid: ^2.2.2
  streaming_shared_preferences: ^1.0.2
  lottie: ^0.7.0+1

dependency_overrides:
  stream_chat:
    path: ../../../stream-chat-flutter/packages/stream_chat
  stream_chat_flutter_core:
    path: ../../../stream-chat-flutter/packages/stream_chat_flutter_core

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  test: any

flutter:
  assets:
    - assets/
    - pubspec.lock
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/android_icon.png"
  image_path_ios: "assets/ios_icon.png"
