name: example
description: A new Flutter project.
publish_to: "none"
version: 2.2.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_app_badger: ^1.3.0
  flutter:
    sdk: flutter
  stream_chat_flutter:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat_flutter
  stream_chat_persistence:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat_persistence
  stream_chat_localizations:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat_localizations
  flutter_local_notifications: ^9.0.0
  flutter_svg: ^2.0.4
  flutter_secure_storage: ^6.0.0
  yaml: ^3.1.0
  uuid: ^3.0.5
  streaming_shared_preferences: ^2.0.0
  lottie: ^2.3.2
  collection: ^1.15.0
  sentry_flutter: ^6.5.0
  flutter_slidable: ^2.0.0
  go_router: ^5.0.5
  provider: ^6.0.3
  firebase_messaging: ^14.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0

dependency_overrides:
  stream_chat:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat
  stream_chat_flutter_core:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat_flutter_core
  stream_chat_flutter:
    git:
      url: https://github.com/GetStream/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat_flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  image_path: "assets/ic_launcher.png"

  android: true
  adaptive_icon_background: "assets/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
