name: Pana Workflow

inputs:
  min_score:
    required: false
    type: number
    default: 120
  pana_version:
    required: false
    type: string
  runs_on:
    required: false
    type: string
    default: "ubuntu-latest"
  working_directory:
    required: false
    type: string
    default: "."

runs:
  using: "composite"
  steps:
    - name: Temporary Override Local Dependencies
      shell: bash
      run: |
        git apply .github/actions/pana/chore__temporarily_override_dep_to_local.patch
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        # Forcing to 3.24.5 for right now as pana has an issue with Dart 3.6 https://github.com/dart-lang/dartdoc/issues/3947
        flutter-version: "3.24.5"
        cache: true
        cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

    - name: Install Pana
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: flutter pub global activate pana ${{inputs.pana_version}}

    - name: Verify Pana Score
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        PANA=$(pana . --no-warning); PANA_SCORE=$(echo $PANA | sed -n "s/.*Points: \([0-9]*\)\/\([0-9]*\)./\1\/\2/p")
        echo "Score: $PANA_SCORE"
        IFS='/'; read -a SCORE_ARR <<< "$PANA_SCORE"; SCORE=SCORE_ARR[0];
        if (( $SCORE < ${{inputs.min_score}} )); then echo "The minimum score of ${{inputs.min_score}} was not met!"; exit 1; fi