#!/bin/bash
set -euo pipefail

# Detects whether DB entity files changed in a PR and whether the schema
# version was bumped. Writes the PR comment body to `comment_body.md` and
# emits `has_changes` / `version_bumped` to $GITHUB_OUTPUT so the calling
# workflow can decide whether to fail the job.
#
# Required env:
#   BASE_BRANCH    Base branch name (e.g. "master").
#   PR_HEAD_SHA    SHA of the PR's head commit.
# Optional env:
#   GITHUB_OUTPUT  File to append step outputs to. Defaults to /dev/null
#                  so the script can be run locally without side effects.
#
# Local usage:
#   BASE_BRANCH=master PR_HEAD_SHA=$(git rev-parse HEAD) \
#     bash .github/workflows/scripts/check-db-entities.sh

: "${BASE_BRANCH:?BASE_BRANCH must be set}"
: "${PR_HEAD_SHA:?PR_HEAD_SHA must be set}"
: "${GITHUB_OUTPUT:=/dev/null}"

ENTITY_DIR="packages/stream_chat_persistence/lib/src/entity"
DB_FILE="packages/stream_chat_persistence/lib/src/db/drift_chat_database.dart"
COMMENT_FILE="comment_body.md"

echo "Using base branch: origin/$BASE_BRANCH for comparison"

# Fetch the PR head only if it isn't already locally resolvable — keeps
# local invocations from needing network access.
if ! git rev-parse --quiet --verify "${PR_HEAD_SHA}^{commit}" >/dev/null; then
  git fetch --no-tags origin "$PR_HEAD_SHA"
fi

MODIFIED_FILES=$(
  git diff --name-only "origin/${BASE_BRANCH}...${PR_HEAD_SHA}" -- "$ENTITY_DIR" \
    | grep -E '\.dart$' || true
)

if [ -z "$MODIFIED_FILES" ]; then
  echo "✅ No entity files changed."
  echo "has_changes=false" >> "$GITHUB_OUTPUT"
  exit 0
fi

echo "⚠️ Entity files modified:"
echo "$MODIFIED_FILES"
echo "has_changes=true" >> "$GITHUB_OUTPUT"

# Pull the `int get schemaVersion => EXPR;` expression from each side. The
# regex only matches a single-line arrow form; multi-line reformats fall
# through to the `unknown` branch below (warning, no failure).
extract_version_expr() {
  git show "$1:$DB_FILE" 2>/dev/null \
    | sed -nE 's/.*schemaVersion[[:space:]]*=>[[:space:]]*([^;]+);.*/\1/p' \
    | head -n1
}

BASE_EXPR=$(extract_version_expr "origin/$BASE_BRANCH")
HEAD_EXPR=$(extract_version_expr "$PR_HEAD_SHA")

VERSION_BUMPED="unknown"
BASE_VERSION=""
HEAD_VERSION=""
SUGGESTED_EXPR=""

if [ -n "$BASE_EXPR" ] && [ -n "$HEAD_EXPR" ]; then
  BASE_VERSION=$((BASE_EXPR))
  HEAD_VERSION=$((HEAD_EXPR))
  echo "Base schemaVersion: $BASE_VERSION ($BASE_EXPR)"
  echo "Head schemaVersion: $HEAD_VERSION ($HEAD_EXPR)"

  # Bump the last integer in the base expression so the existing
  # `1000 + N` style is preserved in the suggested diff.
  LAST_NUM=$(echo "$BASE_EXPR" | grep -oE '[0-9]+' | tail -n1)
  NEW_LAST_NUM=$((LAST_NUM + 1))
  SUGGESTED_EXPR=$(echo "$BASE_EXPR" | sed -E "s/${LAST_NUM}([^0-9]*)\$/${NEW_LAST_NUM}\1/")

  if [ "$HEAD_VERSION" -le "$BASE_VERSION" ]; then
    echo "❌ schemaVersion was not bumped ($BASE_VERSION → $HEAD_VERSION)."
    VERSION_BUMPED="false"
  else
    echo "✅ schemaVersion bumped: $BASE_VERSION → $HEAD_VERSION."
    VERSION_BUMPED="true"
  fi
else
  echo "::warning::Could not parse schemaVersion from $DB_FILE; skipping version check."
fi
echo "version_bumped=$VERSION_BUMPED" >> "$GITHUB_OUTPUT"

{
  echo '## ⚠️ Database Entity Files Modified'
  echo ''
  echo 'The following database entity files have been modified in this PR:'
  echo '```'
  echo "$MODIFIED_FILES"
  echo '```'
  echo ''
  echo '### 📝 Remember to:'
  case "$VERSION_BUMPED" in
    false)
      echo "1. **Bump the database schema version** in \`$DB_FILE\` — CI will fail until this is done:"
      echo ''
      echo '   ```diff'
      echo "   -  int get schemaVersion => ${BASE_EXPR};"
      echo "   +  int get schemaVersion => ${SUGGESTED_EXPR};"
      echo '   ```'
      ;;
    true)
      echo "1. ✅ Database schema version bumped to \`${HEAD_VERSION}\`."
      ;;
    *)
      echo "1. Update the database schema version in \`$DB_FILE\`."
      ;;
  esac
  echo '2. Update entity schema tests if necessary.'
  echo ''
  echo '*Note: This comment is automatically generated by the CI workflow.*'
} > "$COMMENT_FILE"

echo "Comment body written to $COMMENT_FILE"
