include: ../analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    cascade_invocations: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false