name: sample_app_jaspr
description: Stream Chat sample app built with the Jaspr web framework.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.11.0

dependencies:
  jaspr: ^0.23.1
  jaspr_router: ^0.8.2
  stream_chat_jaspr:
    path: ../packages/stream_chat_jaspr
  universal_web: ^1.1.1+1

dev_dependencies:
  build_runner: ^2.15.0
  build_web_compilers: ^4.4.6
  jaspr_builder: ^0.23.1
  jaspr_test: ^0.23.1

jaspr:
  mode: client
