name: 'Enable KVM'
description: 'Configure KVM permissions for Android emulator on Linux runners'
runs:
  using: "composite"
  steps:
    - name: Enable KVM
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
