// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:retrofit/retrofit.dart';
import 'package:stream_core/stream_core.dart';

import '../models.dart';

part 'default_api.g.dart';

@RestApi(callAdapter: _ResultCallAdapter)
abstract interface class DefaultApi {
  factory DefaultApi(
    Dio dio, {
    String? baseUrl,
  }) = _DefaultApi;

  @POST('/api/v2/usergroups/{id}/members')
  Future<Result<AddUserGroupMembersResponse>> addUserGroupMembers({
    @Path('id') required String id,
    @Body() required AddUserGroupMembersRequest addUserGroupMembersRequest,
  });

  @POST('/api/v2/moderation/appeal')
  Future<Result<AppealResponse>> appeal({
    @Body() required AppealRequest appealRequest,
  });

  @POST('/api/v2/moderation/ban')
  Future<Result<ModerationBanResponse>> ban({
    @Body() required BanRequest banRequest,
  });

  @POST('/api/v2/users/block')
  Future<Result<BlockUsersResponse>> blockUsers({
    @Body() required BlockUsersRequest blockUsersRequest,
  });

  @POST('/api/v2/moderation/appeals/bulk_action')
  Future<Result<BulkActionAppealsResponse>> bulkActionAppeals({
    @Body() required BulkActionAppealsRequest bulkActionAppealsRequest,
  });

  @POST('/api/v2/moderation/action_config/bulk_delete')
  Future<Result<BulkDeleteActionConfigResponse>> bulkDeleteActionConfig({
    @Body() required BulkDeleteActionConfigRequest bulkDeleteActionConfigRequest,
  });

  @POST('/api/v2/moderation/action_config/bulk')
  Future<Result<BulkUpsertActionConfigResponse>> bulkUpsertActionConfig({
    @Body() required BulkUpsertActionConfigRequest bulkUpsertActionConfigRequest,
  });

  @POST('/api/v2/chat/messages/{message_id}/polls/{poll_id}/vote')
  Future<Result<PollVoteResponse>> castPollVote({
    @Path('message_id') required String messageId,
    @Path('poll_id') required String pollId,
    @Body() CastPollVoteRequest? castPollVoteRequest,
  });

  @POST('/api/v2/blocklists')
  Future<Result<CreateBlockListResponse>> createBlockList({
    @Body() required CreateBlockListRequest createBlockListRequest,
  });

  @POST('/api/v2/devices')
  Future<Result<DurationResponse>> createDevice({
    @Body() required CreateDeviceRequest createDeviceRequest,
  });

  @POST('/api/v2/chat/channels/{type}/{id}/draft')
  Future<Result<CreateDraftResponse>> createDraft({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() required CreateDraftRequest createDraftRequest,
  });

  @POST('/api/v2/guest')
  Future<Result<CreateGuestResponse>> createGuest({
    @Body() required CreateGuestRequest createGuestRequest,
  });

  @POST('/api/v2/polls')
  Future<Result<PollResponse>> createPoll({
    @Body() required CreatePollRequest createPollRequest,
  });

  @POST('/api/v2/polls/{poll_id}/options')
  Future<Result<PollOptionResponse>> createPollOption({
    @Path('poll_id') required String pollId,
    @Body() required CreatePollOptionRequest createPollOptionRequest,
  });

  @POST('/api/v2/moderation/queues')
  Future<Result<QueueResponse>> createQueue({
    @Body() required CreateQueueRequest createQueueRequest,
  });

  @POST('/api/v2/chat/messages/{message_id}/reminders')
  Future<Result<ReminderResponseData>> createReminder({
    @Path('message_id') required String messageId,
    @Body() CreateReminderRequest? createReminderRequest,
  });

  @POST('/api/v2/usergroups')
  Future<Result<CreateUserGroupResponse>> createUserGroup({
    @Body() required CreateUserGroupRequest createUserGroupRequest,
  });

  @DELETE('/api/v2/moderation/action_config/{id}')
  Future<Result<DeleteActionConfigResponse>> deleteActionConfig({
    @Path('id') required String id,
  });

  @DELETE('/api/v2/blocklists/{name}')
  Future<Result<DurationResponse>> deleteBlockList({
    @Path('name') required String name,
    @Query('team') String? team,
  });

  @DELETE('/api/v2/chat/channels/{type}/{id}')
  Future<Result<DeleteChannelResponse>> deleteChannel({
    @Path('type') required String type,
    @Path('id') required String id,
    @Query('hard_delete') bool? hardDelete,
  });

  @DELETE('/api/v2/chat/channels/{type}/{id}/file')
  Future<Result<DurationResponse>> deleteChannelFile({
    @Path('type') required String type,
    @Path('id') required String id,
    @Query('url') String? url,
  });

  @DELETE('/api/v2/chat/channels/{type}/{id}/image')
  Future<Result<DurationResponse>> deleteChannelImage({
    @Path('type') required String type,
    @Path('id') required String id,
    @Query('url') String? url,
  });

  @POST('/api/v2/chat/channels/delete')
  Future<Result<DeleteChannelsResponse>> deleteChannels({
    @Body() required DeleteChannelsRequest deleteChannelsRequest,
  });

  @DELETE('/api/v2/moderation/config/{key}')
  Future<Result<DeleteModerationConfigResponse>> deleteConfig({
    @Path('key') required String key,
    @Query('team') String? team,
  });

  @DELETE('/api/v2/devices')
  Future<Result<DurationResponse>> deleteDevice({
    @Query('id') required String id,
  });

  @DELETE('/api/v2/chat/channels/{type}/{id}/draft')
  Future<Result<DurationResponse>> deleteDraft({
    @Path('type') required String type,
    @Path('id') required String id,
    @Query('parent_id') String? parentId,
  });

  @DELETE('/api/v2/uploads/file')
  Future<Result<DurationResponse>> deleteFile({
    @Query('url') String? url,
  });

  @DELETE('/api/v2/uploads/image')
  Future<Result<DurationResponse>> deleteImage({
    @Query('url') String? url,
  });

  @DELETE('/api/v2/chat/messages/{id}')
  Future<Result<DeleteMessageResponse>> deleteMessage({
    @Path('id') required String id,
    @Query('hard') bool? hard,
    @Query('delete_for_me') bool? deleteForMe,
  });

  @DELETE('/api/v2/polls/{poll_id}')
  Future<Result<DurationResponse>> deletePoll({
    @Path('poll_id') required String pollId,
  });

  @DELETE('/api/v2/polls/{poll_id}/options/{option_id}')
  Future<Result<DurationResponse>> deletePollOption({
    @Path('poll_id') required String pollId,
    @Path('option_id') required String optionId,
  });

  @DELETE('/api/v2/chat/messages/{message_id}/polls/{poll_id}/vote/{vote_id}')
  Future<Result<PollVoteResponse>> deletePollVote({
    @Path('message_id') required String messageId,
    @Path('poll_id') required String pollId,
    @Path('vote_id') required String voteId,
  });

  @POST('/api/v2/moderation/queues/{id}/delete')
  Future<Result<QueueResponse>> deleteQueue({
    @Path('id') required String id,
  });

  @DELETE('/api/v2/chat/messages/{id}/reaction/{type}')
  Future<Result<DeleteReactionResponse>> deleteReaction({
    @Path('id') required String id,
    @Path('type') required String type,
  });

  @DELETE('/api/v2/chat/messages/{message_id}/reminders')
  Future<Result<DeleteReminderResponse>> deleteReminder({
    @Path('message_id') required String messageId,
  });

  @DELETE('/api/v2/usergroups/{id}')
  Future<Result<DurationResponse>> deleteUserGroup({
    @Path('id') required String id,
    @Query('team_id') String? teamId,
  });

  @POST('/api/v2/moderation/flag')
  Future<Result<FlagItemResponse>> flag({
    @Body() required FlagRequest flagRequest,
  });

  @GET('/api/v2/moderation/action_config')
  Future<Result<GetActionConfigResponse>> getActionConfig({
    @Query('queue_type') String? queueType,
    @Query('entity_type') String? entityType,
    @Query('exclude_defaults') bool? excludeDefaults,
    @Query('only_defaults') bool? onlyDefaults,
  });

  @GET('/api/v2/app')
  Future<Result<GetApplicationResponse>> getApp();

  @GET('/api/v2/moderation/appeal/{id}')
  Future<Result<GetAppealResponse>> getAppeal({
    @Path('id') required String id,
  });

  @GET('/api/v2/users/block')
  Future<Result<GetBlockedUsersResponse>> getBlockedUsers();

  @GET('/api/v2/chat/channels/{type}/{id}')
  Future<Result<ChannelStateResponse>> getChannel({
    @Path('type') required String type,
    @Path('id') required String id,
    @Query('state') bool? state,
    @Query('messages_limit') int? messagesLimit,
    @Query('members_limit') int? membersLimit,
    @Query('watchers_limit') int? watchersLimit,
    @Query('messages_id_lt') String? messagesIdLt,
    @Query('messages_id_lte') String? messagesIdLte,
    @Query('messages_id_gt') String? messagesIdGt,
    @Query('messages_id_gte') String? messagesIdGte,
    @Query('messages_id_around') String? messagesIdAround,
  });

  @GET('/api/v2/moderation/config/{key}')
  Future<Result<GetConfigResponse>> getConfig({
    @Path('key') required String key,
    @Query('team') String? team,
  });

  @GET('/api/v2/chat/channels/{type}/{id}/draft')
  Future<Result<GetDraftResponse>> getDraft({
    @Path('type') required String type,
    @Path('id') required String id,
    @Query('parent_id') String? parentId,
  });

  @GET('/api/v2/chat/channels/{type}/{id}/messages')
  Future<Result<GetManyMessagesResponse>> getManyMessages({
    @Path('type') required String type,
    @Path('id') required String id,
    @Query('ids') required List<String> ids,
    @Query('member_custom_include') List<String>? memberCustomInclude,
  });

  @GET('/api/v2/chat/messages/{id}')
  Future<Result<GetMessageResponse>> getMessage({
    @Path('id') required String id,
  });

  @GET('/api/v2/og')
  Future<Result<GetOGResponse>> getOG({
    @Query('url') required String url,
  });

  @POST('/api/v2/chat/channels/{type}/{id}/query')
  Future<Result<ChannelStateResponse>> getOrCreateChannel({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() ChannelGetOrCreateRequest? channelGetOrCreateRequest,
  });

  @POST('/api/v2/chat/channels/{type}/query')
  Future<Result<ChannelStateResponse>> getOrCreateDistinctChannel({
    @Path('type') required String type,
    @Body() ChannelGetOrCreateRequest? channelGetOrCreateRequest,
  });

  @GET('/api/v2/chat/channels/{type}/{id}/pinned_messages')
  Future<Result<GetPinnedMessagesResponse>> getPinnedMessages({
    @Path('type') required String type,
    @Path('id') required String id,
    @Query('limit') int? limit,
    @Query('offset') int? offset,
    @Query('id_gte') String? idGte,
    @Query('id_gt') String? idGt,
    @Query('id_lte') String? idLte,
    @Query('id_lt') String? idLt,
    @Query('pinned_at_after_or_equal') DateTime? pinnedAtAfterOrEqual,
    @Query('pinned_at_after') DateTime? pinnedAtAfter,
    @Query('pinned_at_before_or_equal') DateTime? pinnedAtBeforeOrEqual,
    @Query('pinned_at_before') DateTime? pinnedAtBefore,
    @Query('id_around') String? idAround,
    @Query('pinned_at_around') DateTime? pinnedAtAround,
    @Query('sort') List<SortParamRequest>? sort,
    @Query('member_custom_include') List<String>? memberCustomInclude,
  });

  @GET('/api/v2/polls/{poll_id}')
  Future<Result<PollResponse>> getPoll({
    @Path('poll_id') required String pollId,
  });

  @GET('/api/v2/polls/{poll_id}/options/{option_id}')
  Future<Result<PollOptionResponse>> getPollOption({
    @Path('poll_id') required String pollId,
    @Path('option_id') required String optionId,
  });

  @GET('/api/v2/moderation/queues/{id}')
  Future<Result<QueueResponse>> getQueue({
    @Path('id') required String id,
  });

  @GET('/api/v2/chat/messages/{id}/reactions')
  Future<Result<GetReactionsResponse>> getReactions({
    @Path('id') required String id,
    @Query('limit') int? limit,
    @Query('offset') int? offset,
  });

  @GET('/api/v2/chat/messages/{parent_id}/replies')
  Future<Result<GetRepliesResponse>> getReplies({
    @Path('parent_id') required String parentId,
    @Query('limit') int? limit,
    @Query('id_gte') String? idGte,
    @Query('id_gt') String? idGt,
    @Query('id_lte') String? idLte,
    @Query('id_lt') String? idLt,
    @Query('id_around') String? idAround,
    @Query('sort') List<SortParamRequest>? sort,
    @Query('member_custom_include') List<String>? memberCustomInclude,
  });

  @GET('/api/v2/chat/threads/{message_id}')
  Future<Result<GetThreadResponse>> getThread({
    @Path('message_id') required String messageId,
    @Query('watch') bool? watch,
    @Query('reply_limit') int? replyLimit,
    @Query('participant_limit') int? participantLimit,
    @Query('member_limit') int? memberLimit,
  });

  @GET('/api/v2/usergroups/{id}')
  Future<Result<GetUserGroupResponse>> getUserGroup({
    @Path('id') required String id,
    @Query('team_id') String? teamId,
  });

  @GET('/api/v2/users/live_locations')
  Future<Result<SharedLocationsResponse>> getUserLiveLocations();

  @POST('/api/v2/chat/channels/grouped')
  Future<Result<GroupedQueryChannelsResponse>> groupedQueryChannels({
    @Body() GroupedQueryChannelsRequest? groupedQueryChannelsRequest,
  });

  @POST('/api/v2/chat/channels/{type}/{id}/hide')
  Future<Result<HideChannelResponse>> hideChannel({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() HideChannelRequest? hideChannelRequest,
  });

  @POST('/api/v2/blocklists/{id}/import')
  Future<Result<ImportBlockListResponse>> importBlockList({
    @Path('id') required String id,
    @Body() required ImportBlockListRequest importBlockListRequest,
  });

  @GET('/api/v2/blocklists')
  Future<Result<ListBlockListResponse>> listBlockLists({
    @Query('team') String? team,
    @Query('cursor') String? cursor,
    @Query('limit') int? limit,
  });

  @GET('/api/v2/devices')
  Future<Result<ListDevicesResponse>> listDevices();

  @GET('/api/v2/moderation/queues')
  Future<Result<ListQueuesResponse>> listQueues();

  @GET('/api/v2/usergroups')
  Future<Result<ListUserGroupsResponse>> listUserGroups({
    @Query('limit') int? limit,
    @Query('id_gt') String? idGt,
    @Query('created_at_gt') String? createdAtGt,
    @Query('team_id') String? teamId,
  });

  @GET('/api/v2/longpoll')
  Future<Result<void>> longPoll({
    @Query('json') WSAuthMessage? json,
  });

  @POST('/api/v2/chat/channels/read')
  Future<Result<MarkReadResponse>> markChannelsRead({
    @Body() MarkChannelsReadRequest? markChannelsReadRequest,
  });

  @POST('/api/v2/chat/channels/delivered')
  Future<Result<MarkDeliveredResponse>> markDelivered({
    @Body() MarkDeliveredRequest? markDeliveredRequest,
  });

  @POST('/api/v2/chat/channels/{type}/{id}/read')
  Future<Result<MarkReadResponse>> markRead({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() MarkReadRequest? markReadRequest,
  });

  @POST('/api/v2/chat/channels/{type}/{id}/unread')
  Future<Result<DurationResponse>> markUnread({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() MarkUnreadRequest? markUnreadRequest,
  });

  @POST('/api/v2/moderation/mute')
  Future<Result<MuteResponse>> mute({
    @Body() required MuteRequest muteRequest,
  });

  @POST('/api/v2/chat/moderation/mute/channel')
  Future<Result<MuteChannelResponse>> muteChannel({
    @Body() MuteChannelRequest? muteChannelRequest,
  });

  @POST('/api/v2/moderation/appeals')
  Future<Result<QueryAppealsResponse>> queryAppeals({
    @Body() QueryAppealsRequest? queryAppealsRequest,
  });

  @GET('/api/v2/chat/query_banned_users')
  Future<Result<QueryBannedUsersResponse>> queryBannedUsers({
    @Query('payload') QueryBannedUsersPayload? payload,
  });

  @POST('/api/v2/chat/channels')
  Future<Result<QueryChannelsResponse>> queryChannels({
    @Body() QueryChannelsRequest? queryChannelsRequest,
  });

  @POST('/api/v2/chat/drafts/query')
  Future<Result<QueryDraftsResponse>> queryDrafts({
    @Body() QueryDraftsRequest? queryDraftsRequest,
  });

  @GET('/api/v2/chat/query_future_channel_bans')
  Future<Result<QueryFutureChannelBansResponse>> queryFutureChannelBans({
    @Query('payload') QueryFutureChannelBansPayload? payload,
  });

  @GET('/api/v2/chat/members')
  Future<Result<MembersResponse>> queryMembers({
    @Query('payload') QueryMembersPayload? payload,
  });

  @GET('/api/v2/chat/moderation/flags/message')
  Future<Result<QueryMessageFlagsResponse>> queryMessageFlags({
    @Query('payload') QueryMessageFlagsPayload? payload,
  });

  @POST('/api/v2/moderation/configs')
  Future<Result<QueryModerationConfigsResponse>> queryModerationConfigs({
    @Body() QueryModerationConfigsRequest? queryModerationConfigsRequest,
  });

  @POST('/api/v2/polls/{poll_id}/votes')
  Future<Result<PollVotesResponse>> queryPollVotes({
    @Path('poll_id') required String pollId,
    @Body() QueryPollVotesRequest? queryPollVotesRequest,
  });

  @POST('/api/v2/polls/query')
  Future<Result<QueryPollsResponse>> queryPolls({
    @Body() QueryPollsRequest? queryPollsRequest,
  });

  @POST('/api/v2/chat/messages/{id}/reactions')
  Future<Result<QueryReactionsResponse>> queryReactions({
    @Path('id') required String id,
    @Body() QueryReactionsRequest? queryReactionsRequest,
  });

  @POST('/api/v2/chat/reminders/query')
  Future<Result<QueryRemindersResponse>> queryReminders({
    @Body() QueryRemindersRequest? queryRemindersRequest,
  });

  @POST('/api/v2/moderation/review_queue')
  Future<Result<QueryReviewQueueResponse>> queryReviewQueue({
    @Body() QueryReviewQueueRequest? queryReviewQueueRequest,
  });

  @POST('/api/v2/chat/threads')
  Future<Result<QueryThreadsResponse>> queryThreads({
    @Body() QueryThreadsRequest? queryThreadsRequest,
  });

  @GET('/api/v2/users')
  Future<Result<QueryUsersResponse>> queryUsers({
    @Query('payload') QueryUsersPayload? payload,
  });

  @POST('/api/v2/usergroups/{id}/members/delete')
  Future<Result<RemoveUserGroupMembersResponse>> removeUserGroupMembers({
    @Path('id') required String id,
    @Body() required RemoveUserGroupMembersRequest removeUserGroupMembersRequest,
  });

  @POST('/api/v2/chat/messages/{id}/action')
  Future<Result<MessageActionResponse>> runMessageAction({
    @Path('id') required String id,
    @Body() required MessageActionRequest messageActionRequest,
  });

  @GET('/api/v2/chat/search')
  Future<Result<SearchResponse>> search({
    @Query('payload') SearchPayload? payload,
  });

  @GET('/api/v2/roles/search')
  Future<Result<SearchRolesResponse>> searchRoles({
    @Query('query') required String query,
    @Query('limit') int? limit,
    @Query('name_gt') String? nameGt,
    @Query('role_type') String? roleType,
    @Query('include_global_roles') bool? includeGlobalRoles,
  });

  @GET('/api/v2/usergroups/search')
  Future<Result<SearchUserGroupsResponse>> searchUserGroups({
    @Query('query') required String query,
    @Query('limit') int? limit,
    @Query('name_gt') String? nameGt,
    @Query('id_gt') String? idGt,
    @Query('team_id') String? teamId,
  });

  @POST('/api/v2/chat/channels/{type}/{id}/event')
  Future<Result<EventResponse>> sendEvent({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() required SendEventRequest sendEventRequest,
  });

  @POST('/api/v2/chat/channels/{type}/{id}/message')
  Future<Result<SendMessageResponse>> sendMessage({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() required SendMessageRequest sendMessageRequest,
  });

  @POST('/api/v2/chat/messages/{id}/reaction')
  Future<Result<SendReactionResponse>> sendReaction({
    @Path('id') required String id,
    @Body() required SendReactionRequest sendReactionRequest,
  });

  @POST('/api/v2/chat/channels/{type}/{id}/show')
  Future<Result<ShowChannelResponse>> showChannel({
    @Path('type') required String type,
    @Path('id') required String id,
  });

  @POST('/api/v2/chat/channels/{type}/{id}/stop-watching')
  Future<Result<DurationResponse>> stopWatchingChannel({
    @Path('type') required String type,
    @Path('id') required String id,
  });

  @POST('/api/v2/moderation/submit_action')
  Future<Result<SubmitActionResponse>> submitAction({
    @Body() required SubmitActionRequest submitActionRequest,
  });

  @POST('/api/v2/chat/sync')
  Future<Result<SyncResponse>> sync({
    @Query('with_inaccessible_cids') bool? withInaccessibleCids,
    @Query('watch') bool? watch,
    @Body() required SyncRequest syncRequest,
  });

  @POST('/api/v2/chat/messages/{id}/translate')
  Future<Result<MessageActionResponse>> translateMessage({
    @Path('id') required String id,
    @Body() required TranslateMessageRequest translateMessageRequest,
  });

  @POST('/api/v2/chat/channels/{type}/{id}/truncate')
  Future<Result<TruncateChannelResponse>> truncateChannel({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() TruncateChannelRequest? truncateChannelRequest,
  });

  @POST('/api/v2/users/unblock')
  Future<Result<UnblockUsersResponse>> unblockUsers({
    @Body() required UnblockUsersRequest unblockUsersRequest,
  });

  @POST('/api/v2/moderation/unmute')
  Future<Result<UnmuteResponse>> unmute({
    @Body() required UnmuteRequest unmuteRequest,
  });

  @POST('/api/v2/chat/moderation/unmute/channel')
  Future<Result<UnmuteResponse>> unmuteChannel({
    @Body() UnmuteChannelRequest? unmuteChannelRequest,
  });

  @GET('/api/v2/chat/unread')
  Future<Result<WrappedUnreadCountsResponse>> unreadCounts();

  @PUT('/api/v2/blocklists/{name}')
  Future<Result<UpdateBlockListResponse>> updateBlockList({
    @Path('name') required String name,
    @Body() UpdateBlockListRequest? updateBlockListRequest,
  });

  @POST('/api/v2/chat/channels/{type}/{id}')
  Future<Result<UpdateChannelResponse>> updateChannel({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() UpdateChannelRequest? updateChannelRequest,
  });

  @PATCH('/api/v2/chat/channels/{type}/{id}')
  Future<Result<UpdateChannelPartialResponse>> updateChannelPartial({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() UpdateChannelPartialRequest? updateChannelPartialRequest,
  });

  @PUT('/api/v2/users/live_locations')
  Future<Result<SharedLocationResponse>> updateLiveLocation({
    @Body() required UpdateLiveLocationRequest updateLiveLocationRequest,
  });

  @PATCH('/api/v2/chat/channels/{type}/{id}/member')
  Future<Result<UpdateMemberPartialResponse>> updateMemberPartial({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() UpdateMemberPartialRequest? updateMemberPartialRequest,
  });

  @POST('/api/v2/chat/messages/{id}')
  Future<Result<UpdateMessageResponse>> updateMessage({
    @Path('id') required String id,
    @Body() required UpdateMessageRequest updateMessageRequest,
  });

  @PUT('/api/v2/chat/messages/{id}')
  Future<Result<UpdateMessagePartialResponse>> updateMessagePartial({
    @Path('id') required String id,
    @Body() UpdateMessagePartialRequest? updateMessagePartialRequest,
  });

  @PUT('/api/v2/polls')
  Future<Result<PollResponse>> updatePoll({
    @Body() required UpdatePollRequest updatePollRequest,
  });

  @PUT('/api/v2/polls/{poll_id}/options')
  Future<Result<PollOptionResponse>> updatePollOption({
    @Path('poll_id') required String pollId,
    @Body() required UpdatePollOptionRequest updatePollOptionRequest,
  });

  @PATCH('/api/v2/polls/{poll_id}')
  Future<Result<PollResponse>> updatePollPartial({
    @Path('poll_id') required String pollId,
    @Body() UpdatePollPartialRequest? updatePollPartialRequest,
  });

  @POST('/api/v2/push_preferences')
  Future<Result<UpsertPushPreferencesResponse>> updatePushNotificationPreferences({
    @Body() required UpsertPushPreferencesRequest upsertPushPreferencesRequest,
  });

  @PATCH('/api/v2/moderation/queues/{id}')
  Future<Result<QueueResponse>> updateQueue({
    @Path('id') required String id,
    @Body() UpdateQueueRequest? updateQueueRequest,
  });

  @PATCH('/api/v2/chat/messages/{message_id}/reminders')
  Future<Result<UpdateReminderResponse>> updateReminder({
    @Path('message_id') required String messageId,
    @Body() UpdateReminderRequest? updateReminderRequest,
  });

  @PATCH('/api/v2/chat/threads/{message_id}')
  Future<Result<UpdateThreadPartialResponse>> updateThreadPartial({
    @Path('message_id') required String messageId,
    @Body() UpdateThreadPartialRequest? updateThreadPartialRequest,
  });

  @PUT('/api/v2/usergroups/{id}')
  Future<Result<UpdateUserGroupResponse>> updateUserGroup({
    @Path('id') required String id,
    @Body() UpdateUserGroupRequest? updateUserGroupRequest,
  });

  @POST('/api/v2/users')
  Future<Result<UpdateUsersResponse>> updateUsers({
    @Body() required UpdateUsersRequest updateUsersRequest,
  });

  @PATCH('/api/v2/users')
  Future<Result<UpdateUsersResponse>> updateUsersPartial({
    @Body() required UpdateUsersPartialRequest updateUsersPartialRequest,
  });

  @POST('/api/v2/chat/channels/{type}/{id}/file')
  Future<Result<UploadChannelFileResponse>> uploadChannelFile({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() UploadChannelFileRequest? uploadChannelFileRequest,
  });

  @POST('/api/v2/chat/channels/{type}/{id}/image')
  Future<Result<UploadChannelResponse>> uploadChannelImage({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() UploadChannelRequest? uploadChannelRequest,
  });

  @POST('/api/v2/uploads/file')
  Future<Result<FileUploadResponse>> uploadFile({
    @Body() FileUploadRequest? fileUploadRequest,
  });

  @POST('/api/v2/uploads/image')
  Future<Result<ImageUploadResponse>> uploadImage({
    @Body() ImageUploadRequest? imageUploadRequest,
  });

  @POST('/api/v2/moderation/action_config')
  Future<Result<UpsertActionConfigResponse>> upsertActionConfig({
    @Body() required UpsertActionConfigRequest upsertActionConfigRequest,
  });

  @POST('/api/v2/moderation/config')
  Future<Result<UpsertConfigResponse>> upsertConfig({
    @Body() required UpsertConfigRequest upsertConfigRequest,
  });
}

class _ResultCallAdapter<T> extends CallAdapter<Future<T>, Future<Result<T>>> {
  @override
  Future<Result<T>> adapt(Future<T> Function() call) => runApiSafely(call);
}
