// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'action.g.dart';
part 'action.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class Action with _$Action {
  const Action({
    required this.name,
    this.style,
    required this.text,
    required this.type,
    this.value,
  });

  @override
  @JsonKey(name: 'name')
  final String name;

  @override
  @JsonKey(name: 'style')
  final String? style;

  @override
  @JsonKey(name: 'text')
  final String text;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @JsonKey(name: 'value')
  final String? value;

  Map<String, dynamic> toJson() => _$ActionToJson(this);

  static Action fromJson(Map<String, dynamic> json) => _$ActionFromJson(json);
}
