// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'action_sequence.g.dart';
part 'action_sequence.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ActionSequence with _$ActionSequence {
  const ActionSequence({
    required this.action,
    required this.blur,
    required this.cooldownPeriod,
    required this.threshold,
    required this.timeWindow,
    required this.warning,
    required this.warningText,
  });

  @override
  @JsonKey(name: 'action')
  final String action;

  @override
  @JsonKey(name: 'blur')
  final bool blur;

  @override
  @JsonKey(name: 'cooldown_period')
  final int cooldownPeriod;

  @override
  @JsonKey(name: 'threshold')
  final int threshold;

  @override
  @JsonKey(name: 'time_window')
  final int timeWindow;

  @override
  @JsonKey(name: 'warning')
  final bool warning;

  @override
  @JsonKey(name: 'warning_text')
  final String warningText;

  Map<String, dynamic> toJson() => _$ActionSequenceToJson(this);

  static ActionSequence fromJson(Map<String, dynamic> json) => _$ActionSequenceFromJson(json);
}
