// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'add_user_group_members_request.g.dart';
part 'add_user_group_members_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class AddUserGroupMembersRequest with _$AddUserGroupMembersRequest {
  const AddUserGroupMembersRequest({
    this.asAdmin,
    required this.memberIds,
    this.teamId,
  });

  @override
  @JsonKey(name: 'as_admin')
  final bool? asAdmin;

  @override
  @JsonKey(name: 'member_ids')
  final List<String> memberIds;

  @override
  @JsonKey(name: 'team_id')
  final String? teamId;

  Map<String, dynamic> toJson() => _$AddUserGroupMembersRequestToJson(this);

  static AddUserGroupMembersRequest fromJson(Map<String, dynamic> json) => _$AddUserGroupMembersRequestFromJson(json);
}
