// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'ai_audio_config_response.g.dart';
part 'ai_audio_config_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class AIAudioConfigResponse with _$AIAudioConfigResponse {
  const AIAudioConfigResponse({
    required this.enabled,
    required this.profile,
    required this.rules,
  });

  @override
  @JsonKey(name: 'enabled')
  final bool enabled;

  @override
  @JsonKey(name: 'profile')
  final String profile;

  @override
  @JsonKey(name: 'rules')
  final List<BodyguardRule> rules;

  Map<String, dynamic> toJson() => _$AIAudioConfigResponseToJson(this);

  static AIAudioConfigResponse fromJson(Map<String, dynamic> json) => _$AIAudioConfigResponseFromJson(json);
}
