// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'ai_video_config.g.dart';
part 'ai_video_config.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class AIVideoConfig with _$AIVideoConfig {
  const AIVideoConfig({
    this.async,
    required this.enabled,
    required this.rules,
  });

  @override
  @JsonKey(name: 'async')
  final bool? async;

  @override
  @JsonKey(name: 'enabled')
  final bool enabled;

  @override
  @JsonKey(name: 'rules')
  final List<AWSRekognitionRule> rules;

  Map<String, dynamic> toJson() => _$AIVideoConfigToJson(this);

  static AIVideoConfig fromJson(Map<String, dynamic> json) => _$AIVideoConfigFromJson(json);
}
