// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'ai_video_config_request.g.dart';
part 'ai_video_config_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class AIVideoConfigRequest with _$AIVideoConfigRequest {
  const AIVideoConfigRequest({
    this.async,
    this.enabled,
    this.rules,
  });

  @override
  @JsonKey(name: 'async')
  final bool? async;

  @override
  @JsonKey(name: 'enabled')
  final bool? enabled;

  @override
  @JsonKey(name: 'rules')
  final List<AWSRekognitionRule>? rules;

  Map<String, dynamic> toJson() => _$AIVideoConfigRequestToJson(this);

  static AIVideoConfigRequest fromJson(Map<String, dynamic> json) => _$AIVideoConfigRequestFromJson(json);
}
