// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'app_event_response.g.dart';
part 'app_event_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class AppEventResponse with _$AppEventResponse {
  const AppEventResponse({
    this.asyncUrlEnrichEnabled,
    required this.autoTranslationEnabled,
    this.fileUploadConfig,
    this.imageUploadConfig,
    required this.name,
  });

  @override
  @JsonKey(name: 'async_url_enrich_enabled')
  final bool? asyncUrlEnrichEnabled;

  @override
  @JsonKey(name: 'auto_translation_enabled')
  final bool autoTranslationEnabled;

  @override
  @JsonKey(name: 'file_upload_config')
  final FileUploadConfig? fileUploadConfig;

  @override
  @JsonKey(name: 'image_upload_config')
  final FileUploadConfig? imageUploadConfig;

  @override
  @JsonKey(name: 'name')
  final String name;

  Map<String, dynamic> toJson() => _$AppEventResponseToJson(this);

  static AppEventResponse fromJson(Map<String, dynamic> json) => _$AppEventResponseFromJson(json);
}
