// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'appeal_item_response.g.dart';
part 'appeal_item_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class AppealItemResponse with _$AppealItemResponse {
  const AppealItemResponse({
    this.actions,
    this.aiTextSeverity,
    required this.appealReason,
    this.attachments,
    this.channelCid,
    this.configKey,
    required this.createdAt,
    this.decisionReason,
    this.entityContent,
    required this.entityId,
    required this.entityType,
    this.flagLabels,
    this.flagTypes,
    this.flags,
    required this.id,
    this.moderationAction,
    this.originalModerationAction,
    this.recommendedAction,
    this.reviewQueueItemId,
    this.severity,
    required this.status,
    required this.updatedAt,
    this.user,
  });

  @override
  @JsonKey(name: 'actions')
  final List<ActionLogResponse>? actions;

  @override
  @JsonKey(name: 'ai_text_severity')
  final String? aiTextSeverity;

  @override
  @JsonKey(name: 'appeal_reason')
  final String appealReason;

  @override
  @JsonKey(name: 'attachments')
  final List<String>? attachments;

  @override
  @JsonKey(name: 'channel_cid')
  final String? channelCid;

  @override
  @JsonKey(name: 'config_key')
  final String? configKey;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'decision_reason')
  final String? decisionReason;

  @override
  @JsonKey(name: 'entity_content')
  final ModerationPayload? entityContent;

  @override
  @JsonKey(name: 'entity_id')
  final String entityId;

  @override
  @JsonKey(name: 'entity_type')
  final String entityType;

  @override
  @JsonKey(name: 'flag_labels')
  final List<String>? flagLabels;

  @override
  @JsonKey(name: 'flag_types')
  final List<String>? flagTypes;

  @override
  @JsonKey(name: 'flags')
  final List<ModerationFlagResponse>? flags;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @JsonKey(name: 'moderation_action')
  final ActionLogResponse? moderationAction;

  @override
  @JsonKey(name: 'original_moderation_action')
  final ActionLogResponse? originalModerationAction;

  @override
  @JsonKey(name: 'recommended_action')
  final String? recommendedAction;

  @override
  @JsonKey(name: 'review_queue_item_id')
  final String? reviewQueueItemId;

  @override
  @JsonKey(name: 'severity')
  final int? severity;

  @override
  @JsonKey(name: 'status')
  final String status;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  @override
  @JsonKey(name: 'user')
  final UserResponse? user;

  Map<String, dynamic> toJson() => _$AppealItemResponseToJson(this);

  static AppealItemResponse fromJson(Map<String, dynamic> json) => _$AppealItemResponseFromJson(json);
}
