// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'appeal_request.g.dart';
part 'appeal_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class AppealRequest with _$AppealRequest {
  const AppealRequest({
    required this.appealReason,
    this.attachments,
    required this.entityId,
    required this.entityType,
    this.reviewQueueItemId,
  });

  @override
  @JsonKey(name: 'appeal_reason')
  final String appealReason;

  @override
  @JsonKey(name: 'attachments')
  final List<String>? attachments;

  @override
  @JsonKey(name: 'entity_id')
  final String entityId;

  @override
  @JsonKey(name: 'entity_type')
  final String entityType;

  @override
  @JsonKey(name: 'review_queue_item_id')
  final String? reviewQueueItemId;

  Map<String, dynamic> toJson() => _$AppealRequestToJson(this);

  static AppealRequest fromJson(Map<String, dynamic> json) => _$AppealRequestFromJson(json);
}
