// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'attachment.g.dart';
part 'attachment.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class Attachment with _$Attachment {
  const Attachment({
    this.actions,
    this.assetUrl,
    this.authorIcon,
    this.authorLink,
    this.authorName,
    this.color,
    required this.custom,
    this.fallback,
    this.fields,
    this.footer,
    this.footerIcon,
    this.giphy,
    this.imageUrl,
    this.ogScrapeUrl,
    this.originalHeight,
    this.originalWidth,
    this.pretext,
    this.text,
    this.thumbUrl,
    this.title,
    this.titleLink,
    this.type,
  });

  @override
  @JsonKey(name: 'actions')
  final List<Action>? actions;

  @override
  @JsonKey(name: 'asset_url')
  final String? assetUrl;

  @override
  @JsonKey(name: 'author_icon')
  final String? authorIcon;

  @override
  @JsonKey(name: 'author_link')
  final String? authorLink;

  @override
  @JsonKey(name: 'author_name')
  final String? authorName;

  @override
  @JsonKey(name: 'color')
  final String? color;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @JsonKey(name: 'fallback')
  final String? fallback;

  @override
  @JsonKey(name: 'fields')
  final List<Field>? fields;

  @override
  @JsonKey(name: 'footer')
  final String? footer;

  @override
  @JsonKey(name: 'footer_icon')
  final String? footerIcon;

  @override
  @JsonKey(name: 'giphy')
  final Images? giphy;

  @override
  @JsonKey(name: 'image_url')
  final String? imageUrl;

  @override
  @JsonKey(name: 'og_scrape_url')
  final String? ogScrapeUrl;

  @override
  @JsonKey(name: 'original_height')
  final int? originalHeight;

  @override
  @JsonKey(name: 'original_width')
  final int? originalWidth;

  @override
  @JsonKey(name: 'pretext')
  final String? pretext;

  @override
  @JsonKey(name: 'text')
  final String? text;

  @override
  @JsonKey(name: 'thumb_url')
  final String? thumbUrl;

  @override
  @JsonKey(name: 'title')
  final String? title;

  @override
  @JsonKey(name: 'title_link')
  final String? titleLink;

  @override
  @JsonKey(name: 'type')
  final String? type;

  Map<String, dynamic> toJson() => _$AttachmentToJson(this);

  static Attachment fromJson(Map<String, dynamic> json) => _$AttachmentFromJson(json);
}
