// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'automod_details_response.g.dart';
part 'automod_details_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class AutomodDetailsResponse with _$AutomodDetailsResponse {
  const AutomodDetailsResponse({
    this.action,
    this.imageLabels,
    this.messageDetails,
    this.originalMessageType,
    this.result,
  });

  @override
  @JsonKey(name: 'action')
  final String? action;

  @override
  @JsonKey(name: 'image_labels')
  final List<String>? imageLabels;

  @override
  @JsonKey(name: 'message_details')
  final FlagMessageDetailsResponse? messageDetails;

  @override
  @JsonKey(name: 'original_message_type')
  final String? originalMessageType;

  @override
  @JsonKey(name: 'result')
  final MessageModerationResult? result;

  Map<String, dynamic> toJson() => _$AutomodDetailsResponseToJson(this);

  static AutomodDetailsResponse fromJson(Map<String, dynamic> json) => _$AutomodDetailsResponseFromJson(json);
}
