// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'aws_rekognition_rule.g.dart';
part 'aws_rekognition_rule.freezed.dart';

extension type const AWSRekognitionRuleAction._(String _) implements String {
  static const bounce = AWSRekognitionRuleAction._('bounce');
  static const bounceFlag = AWSRekognitionRuleAction._('bounce_flag');
  static const bounceRemove = AWSRekognitionRuleAction._('bounce_remove');
  static const flag = AWSRekognitionRuleAction._('flag');
  static const remove = AWSRekognitionRuleAction._('remove');
  static const shadow = AWSRekognitionRuleAction._('shadow');

  factory AWSRekognitionRuleAction.fromJson(String json) => AWSRekognitionRuleAction._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class AWSRekognitionRule with _$AWSRekognitionRule {
  const AWSRekognitionRule({
    required this.action,
    required this.label,
    required this.minConfidence,
    this.subclassifications,
  });

  @override
  @JsonKey(name: 'action')
  final AWSRekognitionRuleAction action;

  @override
  @JsonKey(name: 'label')
  final String label;

  @override
  @JsonKey(name: 'min_confidence')
  final double minConfidence;

  @override
  @JsonKey(name: 'subclassifications')
  final Map<String, Object?>? subclassifications;

  Map<String, dynamic> toJson() => _$AWSRekognitionRuleToJson(this);

  static AWSRekognitionRule fromJson(Map<String, dynamic> json) => _$AWSRekognitionRuleFromJson(json);
}
