// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'ban_request.g.dart';
part 'ban_request.freezed.dart';

extension type const BanRequestDeleteMessages._(String _) implements String {
  static const hard = BanRequestDeleteMessages._('hard');
  static const pruning = BanRequestDeleteMessages._('pruning');
  static const soft = BanRequestDeleteMessages._('soft');

  factory BanRequestDeleteMessages.fromJson(String json) => BanRequestDeleteMessages._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class BanRequest with _$BanRequest {
  const BanRequest({
    this.bannedBy,
    this.bannedById,
    this.channelCid,
    this.deleteMessages,
    this.ipBan,
    this.reason,
    this.shadow,
    required this.targetUserId,
    this.timeout,
  });

  @override
  @JsonKey(name: 'banned_by')
  final UserRequest? bannedBy;

  @override
  @JsonKey(name: 'banned_by_id')
  final String? bannedById;

  @override
  @JsonKey(name: 'channel_cid')
  final String? channelCid;

  @override
  @JsonKey(name: 'delete_messages')
  final BanRequestDeleteMessages? deleteMessages;

  @override
  @JsonKey(name: 'ip_ban')
  final bool? ipBan;

  @override
  @JsonKey(name: 'reason')
  final String? reason;

  @override
  @JsonKey(name: 'shadow')
  final bool? shadow;

  @override
  @JsonKey(name: 'target_user_id')
  final String targetUserId;

  @override
  @JsonKey(name: 'timeout')
  final int? timeout;

  Map<String, dynamic> toJson() => _$BanRequestToJson(this);

  static BanRequest fromJson(Map<String, dynamic> json) => _$BanRequestFromJson(json);
}
