// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'ban_response.g.dart';
part 'ban_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class BanResponse with _$BanResponse {
  const BanResponse({
    this.bannedBy,
    this.channel,
    required this.createdAt,
    this.expires,
    this.reason,
    this.shadow,
    this.user,
  });

  @override
  @JsonKey(name: 'banned_by')
  final UserResponse? bannedBy;

  @override
  @JsonKey(name: 'channel')
  final ChannelResponse? channel;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'expires')
  final DateTime? expires;

  @override
  @JsonKey(name: 'reason')
  final String? reason;

  @override
  @JsonKey(name: 'shadow')
  final bool? shadow;

  @override
  @JsonKey(name: 'user')
  final UserResponse? user;

  Map<String, dynamic> toJson() => _$BanResponseToJson(this);

  static BanResponse fromJson(Map<String, dynamic> json) => _$BanResponseFromJson(json);
}
