// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'block_list_options.g.dart';
part 'block_list_options.freezed.dart';

extension type const BlockListOptionsBehavior._(String _) implements String {
  static const block = BlockListOptionsBehavior._('block');
  static const flag = BlockListOptionsBehavior._('flag');
  static const shadowBlock = BlockListOptionsBehavior._('shadow_block');

  factory BlockListOptionsBehavior.fromJson(String json) => BlockListOptionsBehavior._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class BlockListOptions with _$BlockListOptions {
  const BlockListOptions({
    required this.behavior,
    required this.blocklist,
  });

  @override
  @JsonKey(name: 'behavior')
  final BlockListOptionsBehavior behavior;

  @override
  @JsonKey(name: 'blocklist')
  final String blocklist;

  Map<String, dynamic> toJson() => _$BlockListOptionsToJson(this);

  static BlockListOptions fromJson(Map<String, dynamic> json) => _$BlockListOptionsFromJson(json);
}
