// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'block_users_request.g.dart';
part 'block_users_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class BlockUsersRequest with _$BlockUsersRequest {
  const BlockUsersRequest({
    required this.blockedUserId,
  });

  @override
  @JsonKey(name: 'blocked_user_id')
  final String blockedUserId;

  Map<String, dynamic> toJson() => _$BlockUsersRequestToJson(this);

  static BlockUsersRequest fromJson(Map<String, dynamic> json) => _$BlockUsersRequestFromJson(json);
}
