// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'bodyguard_rule.g.dart';
part 'bodyguard_rule.freezed.dart';

extension type const BodyguardRuleAction._(String _) implements String {
  static const bounce = BodyguardRuleAction._('bounce');
  static const bounceFlag = BodyguardRuleAction._('bounce_flag');
  static const bounceRemove = BodyguardRuleAction._('bounce_remove');
  static const flag = BodyguardRuleAction._('flag');
  static const keep = BodyguardRuleAction._('keep');
  static const mask = BodyguardRuleAction._('mask');
  static const maskFlag = BodyguardRuleAction._('mask_flag');
  static const remove = BodyguardRuleAction._('remove');
  static const shadow = BodyguardRuleAction._('shadow');

  factory BodyguardRuleAction.fromJson(String json) => BodyguardRuleAction._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class BodyguardRule with _$BodyguardRule {
  const BodyguardRule({
    required this.action,
    required this.label,
    required this.severityRules,
  });

  @override
  @JsonKey(name: 'action')
  final BodyguardRuleAction action;

  @override
  @JsonKey(name: 'label')
  final String label;

  @override
  @JsonKey(name: 'severity_rules')
  final List<BodyguardSeverityRule> severityRules;

  Map<String, dynamic> toJson() => _$BodyguardRuleToJson(this);

  static BodyguardRule fromJson(Map<String, dynamic> json) => _$BodyguardRuleFromJson(json);
}
