// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'bodyguard_severity_rule.g.dart';
part 'bodyguard_severity_rule.freezed.dart';

extension type const BodyguardSeverityRuleAction._(String _) implements String {
  static const bounce = BodyguardSeverityRuleAction._('bounce');
  static const bounceFlag = BodyguardSeverityRuleAction._('bounce_flag');
  static const bounceRemove = BodyguardSeverityRuleAction._('bounce_remove');
  static const flag = BodyguardSeverityRuleAction._('flag');
  static const keep = BodyguardSeverityRuleAction._('keep');
  static const mask = BodyguardSeverityRuleAction._('mask');
  static const remove = BodyguardSeverityRuleAction._('remove');
  static const shadow = BodyguardSeverityRuleAction._('shadow');

  factory BodyguardSeverityRuleAction.fromJson(String json) => BodyguardSeverityRuleAction._(json);

  String toJson() => this;
}

extension type const BodyguardSeverityRuleSeverity._(String _) implements String {
  static const critical = BodyguardSeverityRuleSeverity._('critical');
  static const high = BodyguardSeverityRuleSeverity._('high');
  static const low = BodyguardSeverityRuleSeverity._('low');
  static const medium = BodyguardSeverityRuleSeverity._('medium');

  factory BodyguardSeverityRuleSeverity.fromJson(String json) => BodyguardSeverityRuleSeverity._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class BodyguardSeverityRule with _$BodyguardSeverityRule {
  const BodyguardSeverityRule({
    required this.action,
    required this.severity,
  });

  @override
  @JsonKey(name: 'action')
  final BodyguardSeverityRuleAction action;

  @override
  @JsonKey(name: 'severity')
  final BodyguardSeverityRuleSeverity severity;

  Map<String, dynamic> toJson() => _$BodyguardSeverityRuleToJson(this);

  static BodyguardSeverityRule fromJson(Map<String, dynamic> json) => _$BodyguardSeverityRuleFromJson(json);
}
