// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'bulk_action_appeals_response.g.dart';
part 'bulk_action_appeals_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class BulkActionAppealsResponse with _$BulkActionAppealsResponse {
  const BulkActionAppealsResponse({
    required this.duration,
    required this.errors,
    required this.results,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'errors')
  final List<BulkAppealError> errors;

  @override
  @JsonKey(name: 'results')
  final List<BulkAppealResult> results;

  Map<String, dynamic> toJson() => _$BulkActionAppealsResponseToJson(this);

  static BulkActionAppealsResponse fromJson(Map<String, dynamic> json) => _$BulkActionAppealsResponseFromJson(json);
}
