// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'bulk_appeal_error.g.dart';
part 'bulk_appeal_error.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class BulkAppealError with _$BulkAppealError {
  const BulkAppealError({
    required this.appealId,
    required this.error,
  });

  @override
  @JsonKey(name: 'appeal_id')
  final String appealId;

  @override
  @JsonKey(name: 'error')
  final String error;

  Map<String, dynamic> toJson() => _$BulkAppealErrorToJson(this);

  static BulkAppealError fromJson(Map<String, dynamic> json) => _$BulkAppealErrorFromJson(json);
}
