// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'bypass_action_request.g.dart';
part 'bypass_action_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class BypassActionRequest with _$BypassActionRequest {
  const BypassActionRequest({
    this.enabled,
  });

  @override
  @JsonKey(name: 'enabled')
  final bool? enabled;

  Map<String, dynamic> toJson() => _$BypassActionRequestToJson(this);

  static BypassActionRequest fromJson(Map<String, dynamic> json) => _$BypassActionRequestFromJson(json);
}
