// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_action_options.g.dart';
part 'call_action_options.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallActionOptions with _$CallActionOptions {
  const CallActionOptions({
    this.duration,
    this.flagReason,
    this.kickReason,
    this.muteAudio,
    this.muteVideo,
    this.reason,
    this.warningText,
  });

  @override
  @JsonKey(name: 'duration')
  final int? duration;

  @override
  @JsonKey(name: 'flag_reason')
  final String? flagReason;

  @override
  @JsonKey(name: 'kick_reason')
  final String? kickReason;

  @override
  @JsonKey(name: 'mute_audio')
  final bool? muteAudio;

  @override
  @JsonKey(name: 'mute_video')
  final bool? muteVideo;

  @override
  @JsonKey(name: 'reason')
  final String? reason;

  @override
  @JsonKey(name: 'warning_text')
  final String? warningText;

  Map<String, dynamic> toJson() => _$CallActionOptionsToJson(this);

  static CallActionOptions fromJson(Map<String, dynamic> json) => _$CallActionOptionsFromJson(json);
}
