// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_rule_action_sequence.g.dart';
part 'call_rule_action_sequence.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallRuleActionSequence with _$CallRuleActionSequence {
  const CallRuleActionSequence({
    this.actions,
    this.callOptions,
    this.violationNumber,
  });

  @override
  @JsonKey(name: 'actions')
  final List<String>? actions;

  @override
  @JsonKey(name: 'call_options')
  final CallActionOptions? callOptions;

  @override
  @JsonKey(name: 'violation_number')
  final int? violationNumber;

  Map<String, dynamic> toJson() => _$CallRuleActionSequenceToJson(this);

  static CallRuleActionSequence fromJson(Map<String, dynamic> json) => _$CallRuleActionSequenceFromJson(json);
}
