// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'channel_context_response.g.dart';
part 'channel_context_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ChannelContextResponse with _$ChannelContextResponse {
  const ChannelContextResponse({
    required this.cid,
    this.createdBy,
    required this.id,
    required this.type,
  });

  @override
  @JsonKey(name: 'cid')
  final String cid;

  @override
  @JsonKey(name: 'created_by')
  final UserResponse? createdBy;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @JsonKey(name: 'type')
  final String type;

  Map<String, dynamic> toJson() => _$ChannelContextResponseToJson(this);

  static ChannelContextResponse fromJson(Map<String, dynamic> json) => _$ChannelContextResponseFromJson(json);
}
