// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'channel_input_request.g.dart';
part 'channel_input_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ChannelInputRequest with _$ChannelInputRequest {
  const ChannelInputRequest({
    this.autoTranslationEnabled,
    this.autoTranslationLanguage,
    this.configOverrides,
    this.createdBy,
    this.custom,
    this.disabled,
    this.frozen,
    this.invites,
    this.members,
    this.team,
  });

  @override
  @JsonKey(name: 'auto_translation_enabled')
  final bool? autoTranslationEnabled;

  @override
  @JsonKey(name: 'auto_translation_language')
  final String? autoTranslationLanguage;

  @override
  @JsonKey(name: 'config_overrides')
  final ConfigOverridesRequest? configOverrides;

  @override
  @JsonKey(name: 'created_by')
  final UserRequest? createdBy;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?>? custom;

  @override
  @JsonKey(name: 'disabled')
  final bool? disabled;

  @override
  @JsonKey(name: 'frozen')
  final bool? frozen;

  @override
  @JsonKey(name: 'invites')
  final List<ChannelMemberRequest>? invites;

  @override
  @JsonKey(name: 'members')
  final List<ChannelMemberRequest>? members;

  @override
  @JsonKey(name: 'team')
  final String? team;

  Map<String, dynamic> toJson() => _$ChannelInputRequestToJson(this);

  static ChannelInputRequest fromJson(Map<String, dynamic> json) => _$ChannelInputRequestFromJson(json);
}
