// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'channel_config_with_info.g.dart';
part 'channel_config_with_info.freezed.dart';

extension type const ChannelConfigWithInfoAutomod._(String _) implements String {
  static const aI = ChannelConfigWithInfoAutomod._('AI');
  static const disabled = ChannelConfigWithInfoAutomod._('disabled');
  static const simple = ChannelConfigWithInfoAutomod._('simple');

  factory ChannelConfigWithInfoAutomod.fromJson(String json) => ChannelConfigWithInfoAutomod._(json);

  String toJson() => this;
}

extension type const ChannelConfigWithInfoAutomodBehavior._(String _) implements String {
  static const block = ChannelConfigWithInfoAutomodBehavior._('block');
  static const flag = ChannelConfigWithInfoAutomodBehavior._('flag');
  static const shadowBlock = ChannelConfigWithInfoAutomodBehavior._('shadow_block');

  factory ChannelConfigWithInfoAutomodBehavior.fromJson(String json) => ChannelConfigWithInfoAutomodBehavior._(json);

  String toJson() => this;
}

extension type const ChannelConfigWithInfoBlocklistBehavior._(String _) implements String {
  static const block = ChannelConfigWithInfoBlocklistBehavior._('block');
  static const flag = ChannelConfigWithInfoBlocklistBehavior._('flag');
  static const shadowBlock = ChannelConfigWithInfoBlocklistBehavior._('shadow_block');

  factory ChannelConfigWithInfoBlocklistBehavior.fromJson(String json) =>
      ChannelConfigWithInfoBlocklistBehavior._(json);

  String toJson() => this;
}

extension type const ChannelConfigWithInfoPushLevel._(String _) implements String {
  static const all = ChannelConfigWithInfoPushLevel._('all');
  static const allMentions = ChannelConfigWithInfoPushLevel._('all_mentions');
  static const directMentions = ChannelConfigWithInfoPushLevel._('direct_mentions');
  static const mentions = ChannelConfigWithInfoPushLevel._('mentions');
  static const none = ChannelConfigWithInfoPushLevel._('none');

  factory ChannelConfigWithInfoPushLevel.fromJson(String json) => ChannelConfigWithInfoPushLevel._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class ChannelConfigWithInfo with _$ChannelConfigWithInfo {
  const ChannelConfigWithInfo({
    this.allowedFlagReasons,
    required this.automod,
    required this.automodBehavior,
    this.automodThresholds,
    this.blocklist,
    this.blocklistBehavior,
    this.blocklists,
    this.chatPreferences,
    required this.commands,
    required this.connectEvents,
    required this.countMessages,
    required this.createdAt,
    required this.customEvents,
    required this.deliveryEvents,
    this.grants,
    required this.markMessagesPending,
    required this.maxMessageLength,
    required this.messageRetention,
    required this.mutes,
    required this.name,
    this.partitionSize,
    this.partitionTtl,
    required this.polls,
    this.pushLevel,
    required this.pushNotifications,
    required this.quotes,
    required this.reactions,
    required this.readEvents,
    required this.reminders,
    required this.replies,
    required this.search,
    required this.sharedLocations,
    required this.skipLastMsgUpdateForSystemMsgs,
    required this.typingEvents,
    required this.updatedAt,
    required this.uploads,
    required this.urlEnrichment,
    required this.userMessageReminders,
  });

  @override
  @JsonKey(name: 'allowed_flag_reasons')
  final List<String>? allowedFlagReasons;

  @override
  @JsonKey(name: 'automod')
  final ChannelConfigWithInfoAutomod automod;

  @override
  @JsonKey(name: 'automod_behavior')
  final ChannelConfigWithInfoAutomodBehavior automodBehavior;

  @override
  @JsonKey(name: 'automod_thresholds')
  final Thresholds? automodThresholds;

  @override
  @JsonKey(name: 'blocklist')
  final String? blocklist;

  @override
  @JsonKey(name: 'blocklist_behavior')
  final ChannelConfigWithInfoBlocklistBehavior? blocklistBehavior;

  @override
  @JsonKey(name: 'blocklists')
  final List<BlockListOptions>? blocklists;

  @override
  @JsonKey(name: 'chat_preferences')
  final ChatPreferences? chatPreferences;

  @override
  @JsonKey(name: 'commands')
  final List<Command> commands;

  @override
  @JsonKey(name: 'connect_events')
  final bool connectEvents;

  @override
  @JsonKey(name: 'count_messages')
  final bool countMessages;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom_events')
  final bool customEvents;

  @override
  @JsonKey(name: 'delivery_events')
  final bool deliveryEvents;

  @override
  @JsonKey(name: 'grants')
  final Map<String, List<String>>? grants;

  @override
  @JsonKey(name: 'mark_messages_pending')
  final bool markMessagesPending;

  @override
  @JsonKey(name: 'max_message_length')
  final int maxMessageLength;

  @override
  @JsonKey(name: 'message_retention')
  final String messageRetention;

  @override
  @JsonKey(name: 'mutes')
  final bool mutes;

  @override
  @JsonKey(name: 'name')
  final String name;

  @override
  @JsonKey(name: 'partition_size')
  final int? partitionSize;

  @override
  @JsonKey(name: 'partition_ttl')
  final String? partitionTtl;

  @override
  @JsonKey(name: 'polls')
  final bool polls;

  @override
  @JsonKey(name: 'push_level')
  final ChannelConfigWithInfoPushLevel? pushLevel;

  @override
  @JsonKey(name: 'push_notifications')
  final bool pushNotifications;

  @override
  @JsonKey(name: 'quotes')
  final bool quotes;

  @override
  @JsonKey(name: 'reactions')
  final bool reactions;

  @override
  @JsonKey(name: 'read_events')
  final bool readEvents;

  @override
  @JsonKey(name: 'reminders')
  final bool reminders;

  @override
  @JsonKey(name: 'replies')
  final bool replies;

  @override
  @JsonKey(name: 'search')
  final bool search;

  @override
  @JsonKey(name: 'shared_locations')
  final bool sharedLocations;

  @override
  @JsonKey(name: 'skip_last_msg_update_for_system_msgs')
  final bool skipLastMsgUpdateForSystemMsgs;

  @override
  @JsonKey(name: 'typing_events')
  final bool typingEvents;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  @override
  @JsonKey(name: 'uploads')
  final bool uploads;

  @override
  @JsonKey(name: 'url_enrichment')
  final bool urlEnrichment;

  @override
  @JsonKey(name: 'user_message_reminders')
  final bool userMessageReminders;

  Map<String, dynamic> toJson() => _$ChannelConfigWithInfoToJson(this);

  static ChannelConfigWithInfo fromJson(Map<String, dynamic> json) => _$ChannelConfigWithInfoFromJson(json);
}
