// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'channel_response.g.dart';
part 'channel_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ChannelResponse with _$ChannelResponse {
  const ChannelResponse({
    this.autoTranslationEnabled,
    this.autoTranslationLanguage,
    this.blocked,
    required this.cid,
    this.config,
    this.cooldown,
    required this.createdAt,
    this.createdBy,
    required this.custom,
    this.deletedAt,
    required this.disabled,
    this.filterTags,
    required this.frozen,
    this.hidden,
    this.hideMessagesBefore,
    required this.id,
    this.lastMessageAt,
    this.memberCount,
    this.members,
    this.messageCount,
    this.muteExpiresAt,
    this.muted,
    this.ownCapabilities,
    this.team,
    this.truncatedAt,
    this.truncatedBy,
    required this.type,
    required this.updatedAt,
  });

  @override
  @JsonKey(name: 'auto_translation_enabled')
  final bool? autoTranslationEnabled;

  @override
  @JsonKey(name: 'auto_translation_language')
  final String? autoTranslationLanguage;

  @override
  @JsonKey(name: 'blocked')
  final bool? blocked;

  @override
  @JsonKey(name: 'cid')
  final String cid;

  @override
  @JsonKey(name: 'config')
  final ChannelConfigWithInfo? config;

  @override
  @JsonKey(name: 'cooldown')
  final int? cooldown;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'created_by')
  final UserResponse? createdBy;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'deleted_at')
  final DateTime? deletedAt;

  @override
  @JsonKey(name: 'disabled')
  final bool disabled;

  @override
  @JsonKey(name: 'filter_tags')
  final List<String>? filterTags;

  @override
  @JsonKey(name: 'frozen')
  final bool frozen;

  @override
  @JsonKey(name: 'hidden')
  final bool? hidden;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'hide_messages_before')
  final DateTime? hideMessagesBefore;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'last_message_at')
  final DateTime? lastMessageAt;

  @override
  @JsonKey(name: 'member_count')
  final int? memberCount;

  @override
  @JsonKey(name: 'members')
  final List<ChannelMemberResponse>? members;

  @override
  @JsonKey(name: 'message_count')
  final int? messageCount;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'mute_expires_at')
  final DateTime? muteExpiresAt;

  @override
  @JsonKey(name: 'muted')
  final bool? muted;

  @override
  @JsonKey(name: 'own_capabilities')
  final List<ChannelOwnCapability>? ownCapabilities;

  @override
  @JsonKey(name: 'team')
  final String? team;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'truncated_at')
  final DateTime? truncatedAt;

  @override
  @JsonKey(name: 'truncated_by')
  final UserResponse? truncatedBy;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  Map<String, dynamic> toJson() => _$ChannelResponseToJson(this);

  static ChannelResponse fromJson(Map<String, dynamic> json) => _$ChannelResponseFromJson(json);
}
