// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'channel_state_response_fields.g.dart';
part 'channel_state_response_fields.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ChannelStateResponseFields with _$ChannelStateResponseFields {
  const ChannelStateResponseFields({
    this.activeLiveLocations,
    this.channel,
    this.draft,
    this.hidden,
    this.hideMessagesBefore,
    required this.members,
    this.membership,
    required this.messages,
    this.pendingMessages,
    required this.pinnedMessages,
    this.pushPreferences,
    this.read,
    required this.threads,
    this.watcherCount,
    this.watchers,
  });

  @override
  @JsonKey(name: 'active_live_locations')
  final List<SharedLocationResponseData>? activeLiveLocations;

  @override
  @JsonKey(name: 'channel')
  final ChannelResponse? channel;

  @override
  @JsonKey(name: 'draft')
  final DraftResponse? draft;

  @override
  @JsonKey(name: 'hidden')
  final bool? hidden;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'hide_messages_before')
  final DateTime? hideMessagesBefore;

  @override
  @JsonKey(name: 'members')
  final List<ChannelMemberResponse> members;

  @override
  @JsonKey(name: 'membership')
  final ChannelMemberResponse? membership;

  @override
  @JsonKey(name: 'messages')
  final List<MessageResponse> messages;

  @override
  @JsonKey(name: 'pending_messages')
  final List<PendingMessageResponse>? pendingMessages;

  @override
  @JsonKey(name: 'pinned_messages')
  final List<MessageResponse> pinnedMessages;

  @override
  @JsonKey(name: 'push_preferences')
  final ChannelPushPreferencesResponse? pushPreferences;

  @override
  @JsonKey(name: 'read')
  final List<ReadStateResponse>? read;

  @override
  @JsonKey(name: 'threads')
  final List<ThreadStateResponse> threads;

  @override
  @JsonKey(name: 'watcher_count')
  final int? watcherCount;

  @override
  @JsonKey(name: 'watchers')
  final List<UserResponse>? watchers;

  Map<String, dynamic> toJson() => _$ChannelStateResponseFieldsToJson(this);

  static ChannelStateResponseFields fromJson(Map<String, dynamic> json) => _$ChannelStateResponseFieldsFromJson(json);
}
