// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'channel_push_preferences_response.g.dart';
part 'channel_push_preferences_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ChannelPushPreferencesResponse with _$ChannelPushPreferencesResponse {
  const ChannelPushPreferencesResponse({
    this.chatLevel,
    this.chatPreferences,
    this.disabledUntil,
  });

  @override
  @JsonKey(name: 'chat_level')
  final String? chatLevel;

  @override
  @JsonKey(name: 'chat_preferences')
  final ChatPreferencesResponse? chatPreferences;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'disabled_until')
  final DateTime? disabledUntil;

  Map<String, dynamic> toJson() => _$ChannelPushPreferencesResponseToJson(this);

  static ChannelPushPreferencesResponse fromJson(Map<String, dynamic> json) =>
      _$ChannelPushPreferencesResponseFromJson(json);
}
