// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'channel_mute.g.dart';
part 'channel_mute.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ChannelMute with _$ChannelMute {
  const ChannelMute({
    this.channel,
    required this.createdAt,
    this.expires,
    required this.updatedAt,
    this.user,
  });

  @override
  @JsonKey(name: 'channel')
  final ChannelResponse? channel;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'expires')
  final DateTime? expires;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  @override
  @JsonKey(name: 'user')
  final UserResponse? user;

  Map<String, dynamic> toJson() => _$ChannelMuteToJson(this);

  static ChannelMute fromJson(Map<String, dynamic> json) => _$ChannelMuteFromJson(json);
}
