// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'channel_metadata.g.dart';
part 'channel_metadata.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ChannelMetadata with _$ChannelMetadata {
  const ChannelMetadata({
    required this.cid,
    required this.custom,
    required this.id,
    this.lastMessageAt,
    this.memberCount,
    this.messageCount,
    this.pushLevel,
    this.team,
    required this.type,
  });

  @override
  @JsonKey(name: 'cid')
  final String cid;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'last_message_at')
  final DateTime? lastMessageAt;

  @override
  @JsonKey(name: 'member_count')
  final int? memberCount;

  @override
  @JsonKey(name: 'message_count')
  final int? messageCount;

  @override
  @JsonKey(name: 'push_level')
  final String? pushLevel;

  @override
  @JsonKey(name: 'team')
  final String? team;

  @override
  @JsonKey(name: 'type')
  final String type;

  Map<String, dynamic> toJson() => _$ChannelMetadataToJson(this);

  static ChannelMetadata fromJson(Map<String, dynamic> json) => _$ChannelMetadataFromJson(json);
}
