// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'channel_message_count_rule_parameters.g.dart';
part 'channel_message_count_rule_parameters.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ChannelMessageCountRuleParameters with _$ChannelMessageCountRuleParameters {
  const ChannelMessageCountRuleParameters({
    this.operator,
    this.threshold,
  });

  @override
  @JsonKey(name: 'operator')
  final String? operator;

  @override
  @JsonKey(name: 'threshold')
  final int? threshold;

  Map<String, dynamic> toJson() => _$ChannelMessageCountRuleParametersToJson(this);

  static ChannelMessageCountRuleParameters fromJson(Map<String, dynamic> json) =>
      _$ChannelMessageCountRuleParametersFromJson(json);
}
