// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import '../models.dart';

extension type const ChannelOwnCapability._(String _) implements String {
  static const banChannelMembers = ChannelOwnCapability._('ban-channel-members');
  static const castPollVote = ChannelOwnCapability._('cast-poll-vote');
  static const connectEvents = ChannelOwnCapability._('connect-events');
  static const createAttachment = ChannelOwnCapability._('create-attachment');
  static const createMention = ChannelOwnCapability._('create-mention');
  static const deleteAnyMessage = ChannelOwnCapability._('delete-any-message');
  static const deleteChannel = ChannelOwnCapability._('delete-channel');
  static const deleteOwnMessage = ChannelOwnCapability._('delete-own-message');
  static const deliveryEvents = ChannelOwnCapability._('delivery-events');
  static const flagMessage = ChannelOwnCapability._('flag-message');
  static const freezeChannel = ChannelOwnCapability._('freeze-channel');
  static const joinChannel = ChannelOwnCapability._('join-channel');
  static const leaveChannel = ChannelOwnCapability._('leave-channel');
  static const muteChannel = ChannelOwnCapability._('mute-channel');
  static const notifyChannel = ChannelOwnCapability._('notify-channel');
  static const notifyGroup = ChannelOwnCapability._('notify-group');
  static const notifyHere = ChannelOwnCapability._('notify-here');
  static const notifyRole = ChannelOwnCapability._('notify-role');
  static const pinMessage = ChannelOwnCapability._('pin-message');
  static const queryPollVotes = ChannelOwnCapability._('query-poll-votes');
  static const quoteMessage = ChannelOwnCapability._('quote-message');
  static const readEvents = ChannelOwnCapability._('read-events');
  static const searchMessages = ChannelOwnCapability._('search-messages');
  static const sendCustomEvents = ChannelOwnCapability._('send-custom-events');
  static const sendLinks = ChannelOwnCapability._('send-links');
  static const sendMessage = ChannelOwnCapability._('send-message');
  static const sendPoll = ChannelOwnCapability._('send-poll');
  static const sendReaction = ChannelOwnCapability._('send-reaction');
  static const sendReply = ChannelOwnCapability._('send-reply');
  static const sendRestrictedVisibilityMessage = ChannelOwnCapability._('send-restricted-visibility-message');
  static const sendTypingEvents = ChannelOwnCapability._('send-typing-events');
  static const setChannelCooldown = ChannelOwnCapability._('set-channel-cooldown');
  static const shareLocation = ChannelOwnCapability._('share-location');
  static const skipSlowMode = ChannelOwnCapability._('skip-slow-mode');
  static const slowMode = ChannelOwnCapability._('slow-mode');
  static const typingEvents = ChannelOwnCapability._('typing-events');
  static const updateAnyMessage = ChannelOwnCapability._('update-any-message');
  static const updateChannel = ChannelOwnCapability._('update-channel');
  static const updateChannelMembers = ChannelOwnCapability._('update-channel-members');
  static const updateOwnMessage = ChannelOwnCapability._('update-own-message');
  static const updateThread = ChannelOwnCapability._('update-thread');
  static const uploadFile = ChannelOwnCapability._('upload-file');

  factory ChannelOwnCapability.fromJson(String json) => ChannelOwnCapability._(json);

  String toJson() => this;
}
