// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'chat_preferences_input.g.dart';
part 'chat_preferences_input.freezed.dart';

extension type const ChatPreferencesInputChannelMentions._(String _) implements String {
  static const all = ChatPreferencesInputChannelMentions._('all');
  static const none = ChatPreferencesInputChannelMentions._('none');

  factory ChatPreferencesInputChannelMentions.fromJson(String json) => ChatPreferencesInputChannelMentions._(json);

  String toJson() => this;
}

extension type const ChatPreferencesInputDefaultPreference._(String _) implements String {
  static const all = ChatPreferencesInputDefaultPreference._('all');
  static const none = ChatPreferencesInputDefaultPreference._('none');

  factory ChatPreferencesInputDefaultPreference.fromJson(String json) => ChatPreferencesInputDefaultPreference._(json);

  String toJson() => this;
}

extension type const ChatPreferencesInputDirectMentions._(String _) implements String {
  static const all = ChatPreferencesInputDirectMentions._('all');
  static const none = ChatPreferencesInputDirectMentions._('none');

  factory ChatPreferencesInputDirectMentions.fromJson(String json) => ChatPreferencesInputDirectMentions._(json);

  String toJson() => this;
}

extension type const ChatPreferencesInputGroupMentions._(String _) implements String {
  static const all = ChatPreferencesInputGroupMentions._('all');
  static const none = ChatPreferencesInputGroupMentions._('none');

  factory ChatPreferencesInputGroupMentions.fromJson(String json) => ChatPreferencesInputGroupMentions._(json);

  String toJson() => this;
}

extension type const ChatPreferencesInputHereMentions._(String _) implements String {
  static const all = ChatPreferencesInputHereMentions._('all');
  static const none = ChatPreferencesInputHereMentions._('none');

  factory ChatPreferencesInputHereMentions.fromJson(String json) => ChatPreferencesInputHereMentions._(json);

  String toJson() => this;
}

extension type const ChatPreferencesInputRoleMentions._(String _) implements String {
  static const all = ChatPreferencesInputRoleMentions._('all');
  static const none = ChatPreferencesInputRoleMentions._('none');

  factory ChatPreferencesInputRoleMentions.fromJson(String json) => ChatPreferencesInputRoleMentions._(json);

  String toJson() => this;
}

extension type const ChatPreferencesInputThreadReplies._(String _) implements String {
  static const all = ChatPreferencesInputThreadReplies._('all');
  static const none = ChatPreferencesInputThreadReplies._('none');

  factory ChatPreferencesInputThreadReplies.fromJson(String json) => ChatPreferencesInputThreadReplies._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class ChatPreferencesInput with _$ChatPreferencesInput {
  const ChatPreferencesInput({
    this.channelMentions,
    this.defaultPreference,
    this.directMentions,
    this.groupMentions,
    this.hereMentions,
    this.roleMentions,
    this.threadReplies,
  });

  @override
  @JsonKey(name: 'channel_mentions')
  final ChatPreferencesInputChannelMentions? channelMentions;

  @override
  @JsonKey(name: 'default_preference')
  final ChatPreferencesInputDefaultPreference? defaultPreference;

  @override
  @JsonKey(name: 'direct_mentions')
  final ChatPreferencesInputDirectMentions? directMentions;

  @override
  @JsonKey(name: 'group_mentions')
  final ChatPreferencesInputGroupMentions? groupMentions;

  @override
  @JsonKey(name: 'here_mentions')
  final ChatPreferencesInputHereMentions? hereMentions;

  @override
  @JsonKey(name: 'role_mentions')
  final ChatPreferencesInputRoleMentions? roleMentions;

  @override
  @JsonKey(name: 'thread_replies')
  final ChatPreferencesInputThreadReplies? threadReplies;

  Map<String, dynamic> toJson() => _$ChatPreferencesInputToJson(this);

  static ChatPreferencesInput fromJson(Map<String, dynamic> json) => _$ChatPreferencesInputFromJson(json);
}
