// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'chat_moderation_v2_response.g.dart';
part 'chat_moderation_v2_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ChatModerationV2Response with _$ChatModerationV2Response {
  const ChatModerationV2Response({
    required this.action,
    this.blocklistMatched,
    this.blocklistsMatched,
    this.imageHarms,
    required this.originalText,
    this.platformCircumvented,
    this.semanticFilterMatched,
    this.textHarms,
  });

  @override
  @JsonKey(name: 'action')
  final String action;

  @override
  @JsonKey(name: 'blocklist_matched')
  final String? blocklistMatched;

  @override
  @JsonKey(name: 'blocklists_matched')
  final List<String>? blocklistsMatched;

  @override
  @JsonKey(name: 'image_harms')
  final List<String>? imageHarms;

  @override
  @JsonKey(name: 'original_text')
  final String originalText;

  @override
  @JsonKey(name: 'platform_circumvented')
  final bool? platformCircumvented;

  @override
  @JsonKey(name: 'semantic_filter_matched')
  final String? semanticFilterMatched;

  @override
  @JsonKey(name: 'text_harms')
  final List<String>? textHarms;

  Map<String, dynamic> toJson() => _$ChatModerationV2ResponseToJson(this);

  static ChatModerationV2Response fromJson(Map<String, dynamic> json) => _$ChatModerationV2ResponseFromJson(json);
}
