// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'chat_draft_response.g.dart';
part 'chat_draft_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ChatDraftResponse with _$ChatDraftResponse {
  const ChatDraftResponse({
    required this.channelCid,
    required this.createdAt,
    required this.message,
    this.parentId,
    this.parentMessage,
    this.quotedMessage,
  });

  @override
  @JsonKey(name: 'channel_cid')
  final String channelCid;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'message')
  final ChatDraftPayloadResponse message;

  @override
  @JsonKey(name: 'parent_id')
  final String? parentId;

  @override
  @JsonKey(name: 'parent_message')
  final ChatMessageResponse? parentMessage;

  @override
  @JsonKey(name: 'quoted_message')
  final ChatMessageResponse? quotedMessage;

  Map<String, dynamic> toJson() => _$ChatDraftResponseToJson(this);

  static ChatDraftResponse fromJson(Map<String, dynamic> json) => _$ChatDraftResponseFromJson(json);
}
