// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'chat_reaction_response.g.dart';
part 'chat_reaction_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ChatReactionResponse with _$ChatReactionResponse {
  const ChatReactionResponse({
    required this.createdAt,
    required this.custom,
    required this.messageId,
    required this.score,
    required this.type,
    required this.updatedAt,
    required this.user,
    required this.userId,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @JsonKey(name: 'message_id')
  final String messageId;

  @override
  @JsonKey(name: 'score')
  final int score;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  @override
  @JsonKey(name: 'user')
  final UserResponse user;

  @override
  @JsonKey(name: 'user_id')
  final String userId;

  Map<String, dynamic> toJson() => _$ChatReactionResponseToJson(this);

  static ChatReactionResponse fromJson(Map<String, dynamic> json) => _$ChatReactionResponseFromJson(json);
}
