// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'chat_preferences_response.g.dart';
part 'chat_preferences_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ChatPreferencesResponse with _$ChatPreferencesResponse {
  const ChatPreferencesResponse({
    this.channelMentions,
    this.defaultPreference,
    this.directMentions,
    this.groupMentions,
    this.hereMentions,
    this.roleMentions,
    this.threadReplies,
  });

  @override
  @JsonKey(name: 'channel_mentions')
  final String? channelMentions;

  @override
  @JsonKey(name: 'default_preference')
  final String? defaultPreference;

  @override
  @JsonKey(name: 'direct_mentions')
  final String? directMentions;

  @override
  @JsonKey(name: 'group_mentions')
  final String? groupMentions;

  @override
  @JsonKey(name: 'here_mentions')
  final String? hereMentions;

  @override
  @JsonKey(name: 'role_mentions')
  final String? roleMentions;

  @override
  @JsonKey(name: 'thread_replies')
  final String? threadReplies;

  Map<String, dynamic> toJson() => _$ChatPreferencesResponseToJson(this);

  static ChatPreferencesResponse fromJson(Map<String, dynamic> json) => _$ChatPreferencesResponseFromJson(json);
}
