// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'closed_caption_rule_parameters.g.dart';
part 'closed_caption_rule_parameters.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ClosedCaptionRuleParameters with _$ClosedCaptionRuleParameters {
  const ClosedCaptionRuleParameters({
    this.harmLabels,
    this.llmHarmLabels,
    this.severity,
    this.threshold,
    this.timeWindow,
  });

  @override
  @JsonKey(name: 'harm_labels')
  final List<String>? harmLabels;

  @override
  @JsonKey(name: 'llm_harm_labels')
  final Map<String, String>? llmHarmLabels;

  @override
  @JsonKey(name: 'severity')
  final String? severity;

  @override
  @JsonKey(name: 'threshold')
  final int? threshold;

  @override
  @JsonKey(name: 'time_window')
  final String? timeWindow;

  Map<String, dynamic> toJson() => _$ClosedCaptionRuleParametersToJson(this);

  static ClosedCaptionRuleParameters fromJson(Map<String, dynamic> json) => _$ClosedCaptionRuleParametersFromJson(json);
}
