// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'config_overrides_request.g.dart';
part 'config_overrides_request.freezed.dart';

extension type const ConfigOverridesRequestBlocklistBehavior._(String _) implements String {
  static const block = ConfigOverridesRequestBlocklistBehavior._('block');
  static const flag = ConfigOverridesRequestBlocklistBehavior._('flag');

  factory ConfigOverridesRequestBlocklistBehavior.fromJson(String json) =>
      ConfigOverridesRequestBlocklistBehavior._(json);

  String toJson() => this;
}

extension type const ConfigOverridesRequestPushLevel._(String _) implements String {
  static const all = ConfigOverridesRequestPushLevel._('all');
  static const allMentions = ConfigOverridesRequestPushLevel._('all_mentions');
  static const directMentions = ConfigOverridesRequestPushLevel._('direct_mentions');
  static const mentions = ConfigOverridesRequestPushLevel._('mentions');
  static const none = ConfigOverridesRequestPushLevel._('none');

  factory ConfigOverridesRequestPushLevel.fromJson(String json) => ConfigOverridesRequestPushLevel._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class ConfigOverridesRequest with _$ConfigOverridesRequest {
  const ConfigOverridesRequest({
    this.blocklist,
    this.blocklistBehavior,
    this.chatPreferences,
    this.commands,
    this.countMessages,
    this.grants,
    this.maxMessageLength,
    this.pushLevel,
    this.quotes,
    this.reactions,
    this.replies,
    this.sharedLocations,
    this.typingEvents,
    this.uploads,
    this.urlEnrichment,
    this.userMessageReminders,
  });

  @override
  @JsonKey(name: 'blocklist')
  final String? blocklist;

  @override
  @JsonKey(name: 'blocklist_behavior')
  final ConfigOverridesRequestBlocklistBehavior? blocklistBehavior;

  @override
  @JsonKey(name: 'chat_preferences')
  final ChatPreferences? chatPreferences;

  @override
  @JsonKey(name: 'commands')
  final List<String>? commands;

  @override
  @JsonKey(name: 'count_messages')
  final bool? countMessages;

  @override
  @JsonKey(name: 'grants')
  final Map<String, List<String>>? grants;

  @override
  @JsonKey(name: 'max_message_length')
  final int? maxMessageLength;

  @override
  @JsonKey(name: 'push_level')
  final ConfigOverridesRequestPushLevel? pushLevel;

  @override
  @JsonKey(name: 'quotes')
  final bool? quotes;

  @override
  @JsonKey(name: 'reactions')
  final bool? reactions;

  @override
  @JsonKey(name: 'replies')
  final bool? replies;

  @override
  @JsonKey(name: 'shared_locations')
  final bool? sharedLocations;

  @override
  @JsonKey(name: 'typing_events')
  final bool? typingEvents;

  @override
  @JsonKey(name: 'uploads')
  final bool? uploads;

  @override
  @JsonKey(name: 'url_enrichment')
  final bool? urlEnrichment;

  @override
  @JsonKey(name: 'user_message_reminders')
  final bool? userMessageReminders;

  Map<String, dynamic> toJson() => _$ConfigOverridesRequestToJson(this);

  static ConfigOverridesRequest fromJson(Map<String, dynamic> json) => _$ConfigOverridesRequestFromJson(json);
}
