// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'config_response.g.dart';
part 'config_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ConfigResponse with _$ConfigResponse {
  const ConfigResponse({
    this.aiAudioConfig,
    this.aiImageConfig,
    this.aiImageLabelDefinitions,
    this.aiImageSubclassifications,
    this.aiTextConfig,
    this.aiVideoConfig,
    required this.async,
    this.automodPlatformCircumventionConfig,
    this.automodSemanticFiltersConfig,
    this.automodToxicityConfig,
    this.availableBodyguardProfiles,
    this.blockListConfig,
    required this.createdAt,
    this.floodConfig,
    required this.key,
    this.llmConfig,
    required this.supportedVideoCallHarmTypes,
    required this.team,
    required this.updatedAt,
    this.velocityFilterConfig,
    this.videoCallRuleConfig,
  });

  @override
  @JsonKey(name: 'ai_audio_config')
  final AIAudioConfigResponse? aiAudioConfig;

  @override
  @JsonKey(name: 'ai_image_config')
  final AIImageConfig? aiImageConfig;

  @override
  @JsonKey(name: 'ai_image_label_definitions')
  final List<AIImageLabelDefinition>? aiImageLabelDefinitions;

  @override
  @JsonKey(name: 'ai_image_subclassifications')
  final Map<String, List<String>>? aiImageSubclassifications;

  @override
  @JsonKey(name: 'ai_text_config')
  final AITextConfig? aiTextConfig;

  @override
  @JsonKey(name: 'ai_video_config')
  final AIVideoConfig? aiVideoConfig;

  @override
  @JsonKey(name: 'async')
  final bool async;

  @override
  @JsonKey(name: 'automod_platform_circumvention_config')
  final AutomodPlatformCircumventionConfig? automodPlatformCircumventionConfig;

  @override
  @JsonKey(name: 'automod_semantic_filters_config')
  final AutomodSemanticFiltersConfig? automodSemanticFiltersConfig;

  @override
  @JsonKey(name: 'automod_toxicity_config')
  final AutomodToxicityConfig? automodToxicityConfig;

  @override
  @JsonKey(name: 'available_bodyguard_profiles')
  final List<BodyguardProfileSummary>? availableBodyguardProfiles;

  @override
  @JsonKey(name: 'block_list_config')
  final BlockListConfig? blockListConfig;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'flood_config')
  final FloodConfig? floodConfig;

  @override
  @JsonKey(name: 'key')
  final String key;

  @override
  @JsonKey(name: 'llm_config')
  final LLMConfig? llmConfig;

  @override
  @JsonKey(name: 'supported_video_call_harm_types')
  final List<String> supportedVideoCallHarmTypes;

  @override
  @JsonKey(name: 'team')
  final String team;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  @override
  @JsonKey(name: 'velocity_filter_config')
  final VelocityFilterConfig? velocityFilterConfig;

  @override
  @JsonKey(name: 'video_call_rule_config')
  final VideoCallRuleConfig? videoCallRuleConfig;

  Map<String, dynamic> toJson() => _$ConfigResponseToJson(this);

  static ConfigResponse fromJson(Map<String, dynamic> json) => _$ConfigResponseFromJson(json);
}
