// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'content_custom_property_count_parameters.g.dart';
part 'content_custom_property_count_parameters.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ContentCustomPropertyCountParameters with _$ContentCustomPropertyCountParameters {
  const ContentCustomPropertyCountParameters({
    this.operator,
    this.propertyKey,
    this.threshold,
    this.timeWindow,
  });

  @override
  @JsonKey(name: 'operator')
  final String? operator;

  @override
  @JsonKey(name: 'property_key')
  final String? propertyKey;

  @override
  @JsonKey(name: 'threshold')
  final int? threshold;

  @override
  @JsonKey(name: 'time_window')
  final String? timeWindow;

  Map<String, dynamic> toJson() => _$ContentCustomPropertyCountParametersToJson(this);

  static ContentCustomPropertyCountParameters fromJson(Map<String, dynamic> json) =>
      _$ContentCustomPropertyCountParametersFromJson(json);
}
