// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'create_reminder_response.g.dart';
part 'create_reminder_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CreateReminderResponse with _$CreateReminderResponse {
  const CreateReminderResponse({
    required this.duration,
    required this.reminder,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'reminder')
  final ReminderResponseData reminder;

  Map<String, dynamic> toJson() => _$CreateReminderResponseToJson(this);

  static CreateReminderResponse fromJson(Map<String, dynamic> json) => _$CreateReminderResponseFromJson(json);
}
