// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'create_user_group_request.g.dart';
part 'create_user_group_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CreateUserGroupRequest with _$CreateUserGroupRequest {
  const CreateUserGroupRequest({
    this.description,
    this.id,
    this.memberIds,
    required this.name,
    this.teamId,
  });

  @override
  @JsonKey(name: 'description')
  final String? description;

  @override
  @JsonKey(name: 'id')
  final String? id;

  @override
  @JsonKey(name: 'member_ids')
  final List<String>? memberIds;

  @override
  @JsonKey(name: 'name')
  final String name;

  @override
  @JsonKey(name: 'team_id')
  final String? teamId;

  Map<String, dynamic> toJson() => _$CreateUserGroupRequestToJson(this);

  static CreateUserGroupRequest fromJson(Map<String, dynamic> json) => _$CreateUserGroupRequestFromJson(json);
}
