// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'create_queue_request.g.dart';
part 'create_queue_request.freezed.dart';

extension type const CreateQueueRequestType._(String _) implements String {
  static const operationalQueue = CreateQueueRequestType._('operational_queue');
  static const personalView = CreateQueueRequestType._('personal_view');

  factory CreateQueueRequestType.fromJson(String json) => CreateQueueRequestType._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class CreateQueueRequest with _$CreateQueueRequest {
  const CreateQueueRequest({
    this.description,
    this.filters,
    required this.name,
    this.sort,
    required this.type,
  });

  @override
  @JsonKey(name: 'description')
  final String? description;

  @override
  @JsonKey(name: 'filters')
  final Map<String, Object?>? filters;

  @override
  @JsonKey(name: 'name')
  final String name;

  @override
  @JsonKey(name: 'sort')
  final List<Map<String, Object?>>? sort;

  @override
  @JsonKey(name: 'type')
  final CreateQueueRequestType type;

  Map<String, dynamic> toJson() => _$CreateQueueRequestToJson(this);

  static CreateQueueRequest fromJson(Map<String, dynamic> json) => _$CreateQueueRequestFromJson(json);
}
