// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'create_poll_request.g.dart';
part 'create_poll_request.freezed.dart';

extension type const CreatePollRequestVotingVisibility._(String _) implements String {
  static const anonymous = CreatePollRequestVotingVisibility._('anonymous');
  static const public = CreatePollRequestVotingVisibility._('public');

  factory CreatePollRequestVotingVisibility.fromJson(String json) => CreatePollRequestVotingVisibility._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class CreatePollRequest with _$CreatePollRequest {
  const CreatePollRequest({
    this.allowAnswers,
    this.allowUserSuggestedOptions,
    this.custom,
    this.description,
    this.enforceUniqueVote,
    this.id,
    this.isClosed,
    this.maxVotesAllowed,
    required this.name,
    this.options,
    this.votingVisibility,
  });

  @override
  @JsonKey(name: 'allow_answers')
  final bool? allowAnswers;

  @override
  @JsonKey(name: 'allow_user_suggested_options')
  final bool? allowUserSuggestedOptions;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?>? custom;

  @override
  @JsonKey(name: 'description')
  final String? description;

  @override
  @JsonKey(name: 'enforce_unique_vote')
  final bool? enforceUniqueVote;

  @override
  @JsonKey(name: 'id')
  final String? id;

  @override
  @JsonKey(name: 'is_closed')
  final bool? isClosed;

  @override
  @JsonKey(name: 'max_votes_allowed')
  final int? maxVotesAllowed;

  @override
  @JsonKey(name: 'name')
  final String name;

  @override
  @JsonKey(name: 'options')
  final List<PollOptionInput>? options;

  @override
  @JsonKey(name: 'voting_visibility')
  final CreatePollRequestVotingVisibility? votingVisibility;

  Map<String, dynamic> toJson() => _$CreatePollRequestToJson(this);

  static CreatePollRequest fromJson(Map<String, dynamic> json) => _$CreatePollRequestFromJson(json);
}
