// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'create_draft_response.g.dart';
part 'create_draft_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CreateDraftResponse with _$CreateDraftResponse {
  const CreateDraftResponse({
    required this.draft,
    required this.duration,
  });

  @override
  @JsonKey(name: 'draft')
  final DraftResponse draft;

  @override
  @JsonKey(name: 'duration')
  final String duration;

  Map<String, dynamic> toJson() => _$CreateDraftResponseToJson(this);

  static CreateDraftResponse fromJson(Map<String, dynamic> json) => _$CreateDraftResponseFromJson(json);
}
