// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'delete_user_messages_request_payload.g.dart';
part 'delete_user_messages_request_payload.freezed.dart';

extension type const DeleteUserMessagesRequestPayloadDeleteMessages._(String _) implements String {
  static const hard = DeleteUserMessagesRequestPayloadDeleteMessages._('hard');
  static const pruning = DeleteUserMessagesRequestPayloadDeleteMessages._('pruning');
  static const soft = DeleteUserMessagesRequestPayloadDeleteMessages._('soft');

  factory DeleteUserMessagesRequestPayloadDeleteMessages.fromJson(String json) =>
      DeleteUserMessagesRequestPayloadDeleteMessages._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class DeleteUserMessagesRequestPayload with _$DeleteUserMessagesRequestPayload {
  const DeleteUserMessagesRequestPayload({
    this.channelCid,
    required this.deleteMessages,
    this.deleteReactions,
    this.entityId,
    this.entityType,
    this.reason,
  });

  @override
  @JsonKey(name: 'channel_cid')
  final String? channelCid;

  @override
  @JsonKey(name: 'delete_messages')
  final DeleteUserMessagesRequestPayloadDeleteMessages deleteMessages;

  @override
  @JsonKey(name: 'delete_reactions')
  final bool? deleteReactions;

  @override
  @JsonKey(name: 'entity_id')
  final String? entityId;

  @override
  @JsonKey(name: 'entity_type')
  final String? entityType;

  @override
  @JsonKey(name: 'reason')
  final String? reason;

  Map<String, dynamic> toJson() => _$DeleteUserMessagesRequestPayloadToJson(this);

  static DeleteUserMessagesRequestPayload fromJson(Map<String, dynamic> json) =>
      _$DeleteUserMessagesRequestPayloadFromJson(json);
}
