// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'delete_user_request_payload.g.dart';
part 'delete_user_request_payload.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class DeleteUserRequestPayload with _$DeleteUserRequestPayload {
  const DeleteUserRequestPayload({
    this.deleteConversationChannels,
    this.deleteFeedsContent,
    this.entityId,
    this.entityType,
    this.hardDelete,
    this.markMessagesDeleted,
    this.reason,
  });

  @override
  @JsonKey(name: 'delete_conversation_channels')
  final bool? deleteConversationChannels;

  @override
  @JsonKey(name: 'delete_feeds_content')
  final bool? deleteFeedsContent;

  @override
  @JsonKey(name: 'entity_id')
  final String? entityId;

  @override
  @JsonKey(name: 'entity_type')
  final String? entityType;

  @override
  @JsonKey(name: 'hard_delete')
  final bool? hardDelete;

  @override
  @JsonKey(name: 'mark_messages_deleted')
  final bool? markMessagesDeleted;

  @override
  @JsonKey(name: 'reason')
  final String? reason;

  Map<String, dynamic> toJson() => _$DeleteUserRequestPayloadToJson(this);

  static DeleteUserRequestPayload fromJson(Map<String, dynamic> json) => _$DeleteUserRequestPayloadFromJson(json);
}
