// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'delivered_message_payload.g.dart';
part 'delivered_message_payload.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class DeliveredMessagePayload with _$DeliveredMessagePayload {
  const DeliveredMessagePayload({
    this.cid,
    this.id,
  });

  @override
  @JsonKey(name: 'cid')
  final String? cid;

  @override
  @JsonKey(name: 'id')
  final String? id;

  Map<String, dynamic> toJson() => _$DeliveredMessagePayloadToJson(this);

  static DeliveredMessagePayload fromJson(Map<String, dynamic> json) => _$DeliveredMessagePayloadFromJson(json);
}
