// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'delivery_receipts_response.g.dart';
part 'delivery_receipts_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class DeliveryReceiptsResponse with _$DeliveryReceiptsResponse {
  const DeliveryReceiptsResponse({
    required this.enabled,
  });

  @override
  @JsonKey(name: 'enabled')
  final bool enabled;

  Map<String, dynamic> toJson() => _$DeliveryReceiptsResponseToJson(this);

  static DeliveryReceiptsResponse fromJson(Map<String, dynamic> json) => _$DeliveryReceiptsResponseFromJson(json);
}
