// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'enriched_reaction.g.dart';
part 'enriched_reaction.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class EnrichedReaction with _$EnrichedReaction {
  const EnrichedReaction({
    required this.activityId,
    this.childrenCounts,
    this.data,
    this.id,
    required this.kind,
    this.latestChildren,
    this.ownChildren,
    this.parent,
    this.targetFeeds,
    this.user,
    required this.userId,
  });

  @override
  @JsonKey(name: 'activity_id')
  final String activityId;

  @override
  @JsonKey(name: 'children_counts')
  final Map<String, int>? childrenCounts;

  @override
  @JsonKey(name: 'data')
  final Map<String, Object?>? data;

  @override
  @JsonKey(name: 'id')
  final String? id;

  @override
  @JsonKey(name: 'kind')
  final String kind;

  @override
  @JsonKey(name: 'latest_children')
  final Map<String, List<EnrichedReaction>>? latestChildren;

  @override
  @JsonKey(name: 'own_children')
  final Map<String, List<EnrichedReaction>>? ownChildren;

  @override
  @JsonKey(name: 'parent')
  final String? parent;

  @override
  @JsonKey(name: 'target_feeds')
  final List<String>? targetFeeds;

  @override
  @JsonKey(name: 'user')
  final Data? user;

  @override
  @JsonKey(name: 'user_id')
  final String userId;

  Map<String, dynamic> toJson() => _$EnrichedReactionToJson(this);

  static EnrichedReaction fromJson(Map<String, dynamic> json) => _$EnrichedReactionFromJson(json);
}
