// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'feeds_activity_location.g.dart';
part 'feeds_activity_location.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FeedsActivityLocation with _$FeedsActivityLocation {
  const FeedsActivityLocation({
    required this.lat,
    required this.lng,
  });

  @override
  @JsonKey(name: 'lat')
  final double lat;

  @override
  @JsonKey(name: 'lng')
  final double lng;

  Map<String, dynamic> toJson() => _$FeedsActivityLocationToJson(this);

  static FeedsActivityLocation fromJson(Map<String, dynamic> json) => _$FeedsActivityLocationFromJson(json);
}
