// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'feeds_reaction_response.g.dart';
part 'feeds_reaction_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FeedsReactionResponse with _$FeedsReactionResponse {
  const FeedsReactionResponse({
    required this.activityId,
    this.commentId,
    required this.createdAt,
    this.custom,
    required this.type,
    required this.updatedAt,
    required this.user,
  });

  @override
  @JsonKey(name: 'activity_id')
  final String activityId;

  @override
  @JsonKey(name: 'comment_id')
  final String? commentId;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?>? custom;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  @override
  @JsonKey(name: 'user')
  final UserResponse user;

  Map<String, dynamic> toJson() => _$FeedsReactionResponseToJson(this);

  static FeedsReactionResponse fromJson(Map<String, dynamic> json) => _$FeedsReactionResponseFromJson(json);
}
