// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'feeds_reaction_group_response.g.dart';
part 'feeds_reaction_group_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FeedsReactionGroupResponse with _$FeedsReactionGroupResponse {
  const FeedsReactionGroupResponse({
    required this.count,
    required this.firstReactionAt,
    required this.lastReactionAt,
  });

  @override
  @JsonKey(name: 'count')
  final int count;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'first_reaction_at')
  final DateTime firstReactionAt;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'last_reaction_at')
  final DateTime lastReactionAt;

  Map<String, dynamic> toJson() => _$FeedsReactionGroupResponseToJson(this);

  static FeedsReactionGroupResponse fromJson(Map<String, dynamic> json) => _$FeedsReactionGroupResponseFromJson(json);
}
