// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'feeds_feed_response.g.dart';
part 'feeds_feed_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FeedsFeedResponse with _$FeedsFeedResponse {
  const FeedsFeedResponse({
    required this.activityCount,
    required this.createdAt,
    required this.createdBy,
    this.custom,
    this.deletedAt,
    required this.description,
    required this.feed,
    this.filterTags,
    required this.followerCount,
    required this.followingCount,
    required this.groupId,
    required this.id,
    this.location,
    required this.memberCount,
    required this.name,
    required this.pinCount,
    required this.updatedAt,
    this.visibility,
  });

  @override
  @JsonKey(name: 'activity_count')
  final int activityCount;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'created_by')
  final UserResponse createdBy;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?>? custom;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'deleted_at')
  final DateTime? deletedAt;

  @override
  @JsonKey(name: 'description')
  final String description;

  @override
  @JsonKey(name: 'feed')
  final String feed;

  @override
  @JsonKey(name: 'filter_tags')
  final List<String>? filterTags;

  @override
  @JsonKey(name: 'follower_count')
  final int followerCount;

  @override
  @JsonKey(name: 'following_count')
  final int followingCount;

  @override
  @JsonKey(name: 'group_id')
  final String groupId;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @JsonKey(name: 'location')
  final FeedsActivityLocation? location;

  @override
  @JsonKey(name: 'member_count')
  final int memberCount;

  @override
  @JsonKey(name: 'name')
  final String name;

  @override
  @JsonKey(name: 'pin_count')
  final int pinCount;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  @override
  @JsonKey(name: 'visibility')
  final String? visibility;

  Map<String, dynamic> toJson() => _$FeedsFeedResponseToJson(this);

  static FeedsFeedResponse fromJson(Map<String, dynamic> json) => _$FeedsFeedResponseFromJson(json);
}
