// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'feeds_notification_comment.g.dart';
part 'feeds_notification_comment.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FeedsNotificationComment with _$FeedsNotificationComment {
  const FeedsNotificationComment({
    this.attachments,
    required this.comment,
    required this.id,
    required this.userId,
  });

  @override
  @JsonKey(name: 'attachments')
  final List<Attachment>? attachments;

  @override
  @JsonKey(name: 'comment')
  final String comment;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @JsonKey(name: 'user_id')
  final String userId;

  Map<String, dynamic> toJson() => _$FeedsNotificationCommentToJson(this);

  static FeedsNotificationComment fromJson(Map<String, dynamic> json) => _$FeedsNotificationCommentFromJson(json);
}
