// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'feeds_notification_parent_activity.g.dart';
part 'feeds_notification_parent_activity.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FeedsNotificationParentActivity with _$FeedsNotificationParentActivity {
  const FeedsNotificationParentActivity({
    this.attachments,
    required this.id,
    this.text,
    this.type,
    this.userId,
  });

  @override
  @JsonKey(name: 'attachments')
  final List<Attachment>? attachments;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @JsonKey(name: 'text')
  final String? text;

  @override
  @JsonKey(name: 'type')
  final String? type;

  @override
  @JsonKey(name: 'user_id')
  final String? userId;

  Map<String, dynamic> toJson() => _$FeedsNotificationParentActivityToJson(this);

  static FeedsNotificationParentActivity fromJson(Map<String, dynamic> json) =>
      _$FeedsNotificationParentActivityFromJson(json);
}
