// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'feeds_preferences.g.dart';
part 'feeds_preferences.freezed.dart';

extension type const FeedsPreferencesComment._(String _) implements String {
  static const all = FeedsPreferencesComment._('all');
  static const none = FeedsPreferencesComment._('none');

  factory FeedsPreferencesComment.fromJson(String json) => FeedsPreferencesComment._(json);

  String toJson() => this;
}

extension type const FeedsPreferencesCommentMention._(String _) implements String {
  static const all = FeedsPreferencesCommentMention._('all');
  static const none = FeedsPreferencesCommentMention._('none');

  factory FeedsPreferencesCommentMention.fromJson(String json) => FeedsPreferencesCommentMention._(json);

  String toJson() => this;
}

extension type const FeedsPreferencesCommentReaction._(String _) implements String {
  static const all = FeedsPreferencesCommentReaction._('all');
  static const none = FeedsPreferencesCommentReaction._('none');

  factory FeedsPreferencesCommentReaction.fromJson(String json) => FeedsPreferencesCommentReaction._(json);

  String toJson() => this;
}

extension type const FeedsPreferencesCommentReply._(String _) implements String {
  static const all = FeedsPreferencesCommentReply._('all');
  static const none = FeedsPreferencesCommentReply._('none');

  factory FeedsPreferencesCommentReply.fromJson(String json) => FeedsPreferencesCommentReply._(json);

  String toJson() => this;
}

extension type const FeedsPreferencesFollow._(String _) implements String {
  static const all = FeedsPreferencesFollow._('all');
  static const none = FeedsPreferencesFollow._('none');

  factory FeedsPreferencesFollow.fromJson(String json) => FeedsPreferencesFollow._(json);

  String toJson() => this;
}

extension type const FeedsPreferencesMention._(String _) implements String {
  static const all = FeedsPreferencesMention._('all');
  static const none = FeedsPreferencesMention._('none');

  factory FeedsPreferencesMention.fromJson(String json) => FeedsPreferencesMention._(json);

  String toJson() => this;
}

extension type const FeedsPreferencesReaction._(String _) implements String {
  static const all = FeedsPreferencesReaction._('all');
  static const none = FeedsPreferencesReaction._('none');

  factory FeedsPreferencesReaction.fromJson(String json) => FeedsPreferencesReaction._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class FeedsPreferences with _$FeedsPreferences {
  const FeedsPreferences({
    this.comment,
    this.commentMention,
    this.commentReaction,
    this.commentReply,
    this.customActivityTypes,
    this.follow,
    this.mention,
    this.reaction,
  });

  @override
  @JsonKey(name: 'comment')
  final FeedsPreferencesComment? comment;

  @override
  @JsonKey(name: 'comment_mention')
  final FeedsPreferencesCommentMention? commentMention;

  @override
  @JsonKey(name: 'comment_reaction')
  final FeedsPreferencesCommentReaction? commentReaction;

  @override
  @JsonKey(name: 'comment_reply')
  final FeedsPreferencesCommentReply? commentReply;

  @override
  @JsonKey(name: 'custom_activity_types')
  final Map<String, String>? customActivityTypes;

  @override
  @JsonKey(name: 'follow')
  final FeedsPreferencesFollow? follow;

  @override
  @JsonKey(name: 'mention')
  final FeedsPreferencesMention? mention;

  @override
  @JsonKey(name: 'reaction')
  final FeedsPreferencesReaction? reaction;

  Map<String, dynamic> toJson() => _$FeedsPreferencesToJson(this);

  static FeedsPreferences fromJson(Map<String, dynamic> json) => _$FeedsPreferencesFromJson(json);
}
