// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'feeds_enriched_collection_response.g.dart';
part 'feeds_enriched_collection_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FeedsEnrichedCollectionResponse with _$FeedsEnrichedCollectionResponse {
  const FeedsEnrichedCollectionResponse({
    required this.createdAt,
    required this.custom,
    required this.id,
    required this.name,
    required this.status,
    required this.updatedAt,
    required this.userId,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @JsonKey(name: 'name')
  final String name;

  @override
  @JsonKey(name: 'status')
  final String status;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  @override
  @JsonKey(name: 'user_id')
  final String userId;

  Map<String, dynamic> toJson() => _$FeedsEnrichedCollectionResponseToJson(this);

  static FeedsEnrichedCollectionResponse fromJson(Map<String, dynamic> json) =>
      _$FeedsEnrichedCollectionResponseFromJson(json);
}
