// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'filter_config_response.g.dart';
part 'filter_config_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FilterConfigResponse with _$FilterConfigResponse {
  const FilterConfigResponse({
    this.aiImageLabels,
    this.aiImageTaxonomy,
    this.aiTextLabels,
    this.configKeys,
    this.filterableCustomKeys,
    required this.llmLabels,
  });

  @override
  @JsonKey(name: 'ai_image_labels')
  final List<String>? aiImageLabels;

  @override
  @JsonKey(name: 'ai_image_taxonomy')
  final Map<String, List<String>>? aiImageTaxonomy;

  @override
  @JsonKey(name: 'ai_text_labels')
  final List<String>? aiTextLabels;

  @override
  @JsonKey(name: 'config_keys')
  final List<String>? configKeys;

  @override
  @JsonKey(name: 'filterable_custom_keys')
  final List<String>? filterableCustomKeys;

  @override
  @JsonKey(name: 'llm_labels')
  final List<String> llmLabels;

  Map<String, dynamic> toJson() => _$FilterConfigResponseToJson(this);

  static FilterConfigResponse fromJson(Map<String, dynamic> json) => _$FilterConfigResponseFromJson(json);
}
