// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'flag_details_response.g.dart';
part 'flag_details_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FlagDetailsResponse with _$FlagDetailsResponse {
  const FlagDetailsResponse({
    this.automod,
    this.extra,
    required this.originalText,
  });

  @override
  @JsonKey(name: 'automod')
  final AutomodDetailsResponse? automod;

  @override
  @JsonKey(name: 'extra')
  final Map<String, Object?>? extra;

  @override
  @JsonKey(name: 'original_text')
  final String originalText;

  Map<String, dynamic> toJson() => _$FlagDetailsResponseToJson(this);

  static FlagDetailsResponse fromJson(Map<String, dynamic> json) => _$FlagDetailsResponseFromJson(json);
}
