// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'flag_request.g.dart';
part 'flag_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FlagRequest with _$FlagRequest {
  const FlagRequest({
    this.custom,
    this.entityCreatorId,
    required this.entityId,
    required this.entityType,
    this.moderationPayload,
    this.reason,
  });

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?>? custom;

  @override
  @JsonKey(name: 'entity_creator_id')
  final String? entityCreatorId;

  @override
  @JsonKey(name: 'entity_id')
  final String entityId;

  @override
  @JsonKey(name: 'entity_type')
  final String entityType;

  @override
  @JsonKey(name: 'moderation_payload')
  final ModerationPayload? moderationPayload;

  @override
  @JsonKey(name: 'reason')
  final String? reason;

  Map<String, dynamic> toJson() => _$FlagRequestToJson(this);

  static FlagRequest fromJson(Map<String, dynamic> json) => _$FlagRequestFromJson(json);
}
