// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'flood_identical_config.g.dart';
part 'flood_identical_config.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FloodIdenticalConfig with _$FloodIdenticalConfig {
  const FloodIdenticalConfig({
    required this.action,
    required this.enabled,
    required this.threshold,
    required this.timeWindow,
  });

  @override
  @JsonKey(name: 'action')
  final String action;

  @override
  @JsonKey(name: 'enabled')
  final bool enabled;

  @override
  @JsonKey(name: 'threshold')
  final int threshold;

  @override
  @JsonKey(name: 'time_window')
  final String timeWindow;

  Map<String, dynamic> toJson() => _$FloodIdenticalConfigToJson(this);

  static FloodIdenticalConfig fromJson(Map<String, dynamic> json) => _$FloodIdenticalConfigFromJson(json);
}
