// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'flood_config.g.dart';
part 'flood_config.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FloodConfig with _$FloodConfig {
  const FloodConfig({
    this.allowlist,
    this.identical_,
    this.similar,
  });

  @override
  @JsonKey(name: 'allowlist')
  final List<String>? allowlist;

  @override
  @JsonKey(name: 'identical')
  final FloodIdenticalConfig? identical_;

  @override
  @JsonKey(name: 'similar')
  final FloodSimilarConfig? similar;

  Map<String, dynamic> toJson() => _$FloodConfigToJson(this);

  static FloodConfig fromJson(Map<String, dynamic> json) => _$FloodConfigFromJson(json);
}
