// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'full_user_response.g.dart';
part 'full_user_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FullUserResponse with _$FullUserResponse {
  const FullUserResponse({
    this.avgResponseTime,
    this.banExpires,
    required this.banned,
    required this.blockedUserIds,
    required this.channelMutes,
    required this.createdAt,
    required this.custom,
    this.deactivatedAt,
    this.deletedAt,
    required this.devices,
    required this.id,
    this.image,
    required this.invisible,
    required this.language,
    this.lastActive,
    this.latestHiddenChannels,
    required this.mutes,
    this.name,
    required this.online,
    this.privacySettings,
    this.revokeTokensIssuedBefore,
    required this.role,
    required this.shadowBanned,
    required this.teams,
    this.teamsRole,
    required this.totalUnreadCount,
    required this.unreadChannels,
    required this.unreadCount,
    required this.unreadThreads,
    required this.updatedAt,
  });

  @override
  @JsonKey(name: 'avg_response_time')
  final int? avgResponseTime;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'ban_expires')
  final DateTime? banExpires;

  @override
  @JsonKey(name: 'banned')
  final bool banned;

  @override
  @JsonKey(name: 'blocked_user_ids')
  final List<String> blockedUserIds;

  @override
  @JsonKey(name: 'channel_mutes')
  final List<ChannelMute> channelMutes;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'deactivated_at')
  final DateTime? deactivatedAt;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'deleted_at')
  final DateTime? deletedAt;

  @override
  @JsonKey(name: 'devices')
  final List<DeviceResponse> devices;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @JsonKey(name: 'image')
  final String? image;

  @override
  @JsonKey(name: 'invisible')
  final bool invisible;

  @override
  @JsonKey(name: 'language')
  final String language;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'last_active')
  final DateTime? lastActive;

  @override
  @JsonKey(name: 'latest_hidden_channels')
  final List<String>? latestHiddenChannels;

  @override
  @JsonKey(name: 'mutes')
  final List<UserMuteResponse> mutes;

  @override
  @JsonKey(name: 'name')
  final String? name;

  @override
  @JsonKey(name: 'online')
  final bool online;

  @override
  @JsonKey(name: 'privacy_settings')
  final PrivacySettingsResponse? privacySettings;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'revoke_tokens_issued_before')
  final DateTime? revokeTokensIssuedBefore;

  @override
  @JsonKey(name: 'role')
  final String role;

  @override
  @JsonKey(name: 'shadow_banned')
  final bool shadowBanned;

  @override
  @JsonKey(name: 'teams')
  final List<String> teams;

  @override
  @JsonKey(name: 'teams_role')
  final Map<String, String>? teamsRole;

  @override
  @JsonKey(name: 'total_unread_count')
  final int totalUnreadCount;

  @override
  @JsonKey(name: 'unread_channels')
  final int unreadChannels;

  @override
  @JsonKey(name: 'unread_count')
  final int unreadCount;

  @override
  @JsonKey(name: 'unread_threads')
  final int unreadThreads;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  Map<String, dynamic> toJson() => _$FullUserResponseToJson(this);

  static FullUserResponse fromJson(Map<String, dynamic> json) => _$FullUserResponseFromJson(json);
}
