// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'get_application_response.g.dart';
part 'get_application_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class GetApplicationResponse with _$GetApplicationResponse {
  const GetApplicationResponse({
    required this.app,
    required this.duration,
  });

  @override
  @JsonKey(name: 'app')
  final AppResponseFields app;

  @override
  @JsonKey(name: 'duration')
  final String duration;

  Map<String, dynamic> toJson() => _$GetApplicationResponseToJson(this);

  static GetApplicationResponse fromJson(Map<String, dynamic> json) => _$GetApplicationResponseFromJson(json);
}
