// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'get_replies_response.g.dart';
part 'get_replies_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class GetRepliesResponse with _$GetRepliesResponse {
  const GetRepliesResponse({
    required this.duration,
    required this.messages,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'messages')
  final List<MessageResponse> messages;

  Map<String, dynamic> toJson() => _$GetRepliesResponseToJson(this);

  static GetRepliesResponse fromJson(Map<String, dynamic> json) => _$GetRepliesResponseFromJson(json);
}
