// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'grouped_channels_bucket.g.dart';
part 'grouped_channels_bucket.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class GroupedChannelsBucket with _$GroupedChannelsBucket {
  const GroupedChannelsBucket({
    required this.channels,
    this.next,
    this.prev,
    this.unreadChannels,
  });

  @override
  @JsonKey(name: 'channels')
  final List<ChannelStateResponseFields> channels;

  @override
  @JsonKey(name: 'next')
  final String? next;

  @override
  @JsonKey(name: 'prev')
  final String? prev;

  @override
  @JsonKey(name: 'unread_channels')
  final int? unreadChannels;

  Map<String, dynamic> toJson() => _$GroupedChannelsBucketToJson(this);

  static GroupedChannelsBucket fromJson(Map<String, dynamic> json) => _$GroupedChannelsBucketFromJson(json);
}
