// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'grouped_query_channels_response.g.dart';
part 'grouped_query_channels_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class GroupedQueryChannelsResponse with _$GroupedQueryChannelsResponse {
  const GroupedQueryChannelsResponse({
    required this.duration,
    required this.groups,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'groups')
  final Map<String, GroupedChannelsBucket> groups;

  Map<String, dynamic> toJson() => _$GroupedQueryChannelsResponseToJson(this);

  static GroupedQueryChannelsResponse fromJson(Map<String, dynamic> json) =>
      _$GroupedQueryChannelsResponseFromJson(json);
}
