// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'hide_channel_request.g.dart';
part 'hide_channel_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class HideChannelRequest with _$HideChannelRequest {
  const HideChannelRequest({
    this.clearHistory,
  });

  @override
  @JsonKey(name: 'clear_history')
  final bool? clearHistory;

  Map<String, dynamic> toJson() => _$HideChannelRequestToJson(this);

  static HideChannelRequest fromJson(Map<String, dynamic> json) => _$HideChannelRequestFromJson(json);
}
