// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'image_data.g.dart';
part 'image_data.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ImageData with _$ImageData {
  const ImageData({
    required this.frames,
    required this.height,
    required this.size,
    required this.url,
    required this.width,
  });

  @override
  @JsonKey(name: 'frames')
  final String frames;

  @override
  @JsonKey(name: 'height')
  final String height;

  @override
  @JsonKey(name: 'size')
  final String size;

  @override
  @JsonKey(name: 'url')
  final String url;

  @override
  @JsonKey(name: 'width')
  final String width;

  Map<String, dynamic> toJson() => _$ImageDataToJson(this);

  static ImageData fromJson(Map<String, dynamic> json) => _$ImageDataFromJson(json);
}
