// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'images.g.dart';
part 'images.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class Images with _$Images {
  const Images({
    required this.fixedHeight,
    required this.fixedHeightDownsampled,
    required this.fixedHeightStill,
    required this.fixedWidth,
    required this.fixedWidthDownsampled,
    required this.fixedWidthStill,
    required this.original,
  });

  @override
  @JsonKey(name: 'fixed_height')
  final ImageData fixedHeight;

  @override
  @JsonKey(name: 'fixed_height_downsampled')
  final ImageData fixedHeightDownsampled;

  @override
  @JsonKey(name: 'fixed_height_still')
  final ImageData fixedHeightStill;

  @override
  @JsonKey(name: 'fixed_width')
  final ImageData fixedWidth;

  @override
  @JsonKey(name: 'fixed_width_downsampled')
  final ImageData fixedWidthDownsampled;

  @override
  @JsonKey(name: 'fixed_width_still')
  final ImageData fixedWidthStill;

  @override
  @JsonKey(name: 'original')
  final ImageData original;

  Map<String, dynamic> toJson() => _$ImagesToJson(this);

  static Images fromJson(Map<String, dynamic> json) => _$ImagesFromJson(json);
}
