// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'import_block_list_request.g.dart';
part 'import_block_list_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ImportBlockListRequest with _$ImportBlockListRequest {
  const ImportBlockListRequest({
    this.chunkSize,
    required this.items,
  });

  @override
  @JsonKey(name: 'chunk_size')
  final int? chunkSize;

  @override
  @JsonKey(name: 'items')
  final List<String> items;

  Map<String, dynamic> toJson() => _$ImportBlockListRequestToJson(this);

  static ImportBlockListRequest fromJson(Map<String, dynamic> json) => _$ImportBlockListRequestFromJson(json);
}
