// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'list_queues_response.g.dart';
part 'list_queues_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ListQueuesResponse with _$ListQueuesResponse {
  const ListQueuesResponse({
    required this.duration,
    required this.queues,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'queues')
  final List<ModerationQueueResponse> queues;

  Map<String, dynamic> toJson() => _$ListQueuesResponseToJson(this);

  static ListQueuesResponse fromJson(Map<String, dynamic> json) => _$ListQueuesResponseFromJson(json);
}
