// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'mark_channels_read_request.g.dart';
part 'mark_channels_read_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class MarkChannelsReadRequest with _$MarkChannelsReadRequest {
  const MarkChannelsReadRequest({
    this.readByChannel,
  });

  @override
  @JsonKey(name: 'read_by_channel')
  final Map<String, String>? readByChannel;

  Map<String, dynamic> toJson() => _$MarkChannelsReadRequestToJson(this);

  static MarkChannelsReadRequest fromJson(Map<String, dynamic> json) => _$MarkChannelsReadRequestFromJson(json);
}
