// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'mark_unread_request.g.dart';
part 'mark_unread_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class MarkUnreadRequest with _$MarkUnreadRequest {
  const MarkUnreadRequest({
    this.messageId,
    this.messageTimestamp,
    this.threadId,
  });

  @override
  @JsonKey(name: 'message_id')
  final String? messageId;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'message_timestamp')
  final DateTime? messageTimestamp;

  @override
  @JsonKey(name: 'thread_id')
  final String? threadId;

  Map<String, dynamic> toJson() => _$MarkUnreadRequestToJson(this);

  static MarkUnreadRequest fromJson(Map<String, dynamic> json) => _$MarkUnreadRequestFromJson(json);
}
