// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'mark_reviewed_request_payload.g.dart';
part 'mark_reviewed_request_payload.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class MarkReviewedRequestPayload with _$MarkReviewedRequestPayload {
  const MarkReviewedRequestPayload({
    this.contentToMarkAsReviewedLimit,
    this.decisionReason,
    this.disableMarkingContentAsReviewed,
  });

  @override
  @JsonKey(name: 'content_to_mark_as_reviewed_limit')
  final int? contentToMarkAsReviewedLimit;

  @override
  @JsonKey(name: 'decision_reason')
  final String? decisionReason;

  @override
  @JsonKey(name: 'disable_marking_content_as_reviewed')
  final bool? disableMarkingContentAsReviewed;

  Map<String, dynamic> toJson() => _$MarkReviewedRequestPayloadToJson(this);

  static MarkReviewedRequestPayload fromJson(Map<String, dynamic> json) => _$MarkReviewedRequestPayloadFromJson(json);
}
