// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'members_response.g.dart';
part 'members_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class MembersResponse with _$MembersResponse {
  const MembersResponse({
    required this.duration,
    required this.members,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'members')
  final List<ChannelMemberResponse> members;

  Map<String, dynamic> toJson() => _$MembersResponseToJson(this);

  static MembersResponse fromJson(Map<String, dynamic> json) => _$MembersResponseFromJson(json);
}
