// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'message_pagination_params.g.dart';
part 'message_pagination_params.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class MessagePaginationParams with _$MessagePaginationParams {
  const MessagePaginationParams({
    this.createdAtAfter,
    this.createdAtAfterOrEqual,
    this.createdAtAround,
    this.createdAtBefore,
    this.createdAtBeforeOrEqual,
    this.idAround,
    this.idGt,
    this.idGte,
    this.idLt,
    this.idLte,
    this.limit,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at_after')
  final DateTime? createdAtAfter;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at_after_or_equal')
  final DateTime? createdAtAfterOrEqual;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at_around')
  final DateTime? createdAtAround;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at_before')
  final DateTime? createdAtBefore;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at_before_or_equal')
  final DateTime? createdAtBeforeOrEqual;

  @override
  @JsonKey(name: 'id_around')
  final String? idAround;

  @override
  @JsonKey(name: 'id_gt')
  final String? idGt;

  @override
  @JsonKey(name: 'id_gte')
  final String? idGte;

  @override
  @JsonKey(name: 'id_lt')
  final String? idLt;

  @override
  @JsonKey(name: 'id_lte')
  final String? idLte;

  @override
  @JsonKey(name: 'limit')
  final int? limit;

  Map<String, dynamic> toJson() => _$MessagePaginationParamsToJson(this);

  static MessagePaginationParams fromJson(Map<String, dynamic> json) => _$MessagePaginationParamsFromJson(json);
}
