// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'message_response.g.dart';
part 'message_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class MessageResponse with _$MessageResponse {
  const MessageResponse({
    required this.attachments,
    required this.cid,
    this.command,
    required this.createdAt,
    required this.custom,
    this.deletedAt,
    this.deletedForMe,
    required this.deletedReplyCount,
    this.draft,
    required this.html,
    this.i18n,
    required this.id,
    this.imageLabels,
    required this.latestReactions,
    this.member,
    required this.mentionedChannel,
    this.mentionedChannelMembers,
    this.mentionedGroupIds,
    this.mentionedGroups,
    required this.mentionedHere,
    this.mentionedRoles,
    required this.mentionedUsers,
    this.messageTextUpdatedAt,
    this.mml,
    this.moderation,
    required this.ownReactions,
    this.parentId,
    this.pinExpires,
    required this.pinned,
    this.pinnedAt,
    this.pinnedBy,
    this.poll,
    this.pollId,
    this.quotedMessage,
    this.quotedMessageId,
    required this.reactionCounts,
    this.reactionGroups,
    required this.reactionScores,
    this.reminder,
    required this.replyCount,
    required this.restrictedVisibility,
    required this.shadowed,
    this.sharedLocation,
    this.showInChannel,
    required this.silent,
    required this.text,
    this.threadParticipants,
    required this.type,
    required this.updatedAt,
    required this.user,
  });

  @override
  @JsonKey(name: 'attachments')
  final List<Attachment> attachments;

  @override
  @JsonKey(name: 'cid')
  final String cid;

  @override
  @JsonKey(name: 'command')
  final String? command;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'deleted_at')
  final DateTime? deletedAt;

  @override
  @JsonKey(name: 'deleted_for_me')
  final bool? deletedForMe;

  @override
  @JsonKey(name: 'deleted_reply_count')
  final int deletedReplyCount;

  @override
  @JsonKey(name: 'draft')
  final DraftResponse? draft;

  @override
  @JsonKey(name: 'html')
  final String html;

  @override
  @JsonKey(name: 'i18n')
  final Map<String, String>? i18n;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @JsonKey(name: 'image_labels')
  final Map<String, List<String>>? imageLabels;

  @override
  @JsonKey(name: 'latest_reactions')
  final List<ReactionResponse> latestReactions;

  @override
  @JsonKey(name: 'member')
  final ChannelMemberPartialResponse? member;

  @override
  @JsonKey(name: 'mentioned_channel')
  final bool mentionedChannel;

  @override
  @JsonKey(name: 'mentioned_channel_members')
  final Map<String, ChannelMemberPartialResponse>? mentionedChannelMembers;

  @override
  @JsonKey(name: 'mentioned_group_ids')
  final List<String>? mentionedGroupIds;

  @override
  @JsonKey(name: 'mentioned_groups')
  final List<UserGroupResponse>? mentionedGroups;

  @override
  @JsonKey(name: 'mentioned_here')
  final bool mentionedHere;

  @override
  @JsonKey(name: 'mentioned_roles')
  final List<String>? mentionedRoles;

  @override
  @JsonKey(name: 'mentioned_users')
  final List<UserResponse> mentionedUsers;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'message_text_updated_at')
  final DateTime? messageTextUpdatedAt;

  @override
  @JsonKey(name: 'mml')
  final String? mml;

  @override
  @JsonKey(name: 'moderation')
  final ModerationV2Response? moderation;

  @override
  @JsonKey(name: 'own_reactions')
  final List<ReactionResponse> ownReactions;

  @override
  @JsonKey(name: 'parent_id')
  final String? parentId;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'pin_expires')
  final DateTime? pinExpires;

  @override
  @JsonKey(name: 'pinned')
  final bool pinned;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'pinned_at')
  final DateTime? pinnedAt;

  @override
  @JsonKey(name: 'pinned_by')
  final UserResponse? pinnedBy;

  @override
  @JsonKey(name: 'poll')
  final PollResponseData? poll;

  @override
  @JsonKey(name: 'poll_id')
  final String? pollId;

  @override
  @JsonKey(name: 'quoted_message')
  final MessageResponse? quotedMessage;

  @override
  @JsonKey(name: 'quoted_message_id')
  final String? quotedMessageId;

  @override
  @JsonKey(name: 'reaction_counts')
  final Map<String, int> reactionCounts;

  @override
  @JsonKey(name: 'reaction_groups')
  final Map<String, ReactionGroupResponse>? reactionGroups;

  @override
  @JsonKey(name: 'reaction_scores')
  final Map<String, int> reactionScores;

  @override
  @JsonKey(name: 'reminder')
  final ReminderResponseData? reminder;

  @override
  @JsonKey(name: 'reply_count')
  final int replyCount;

  @override
  @JsonKey(name: 'restricted_visibility')
  final List<String> restrictedVisibility;

  @override
  @JsonKey(name: 'shadowed')
  final bool shadowed;

  @override
  @JsonKey(name: 'shared_location')
  final SharedLocationResponseData? sharedLocation;

  @override
  @JsonKey(name: 'show_in_channel')
  final bool? showInChannel;

  @override
  @JsonKey(name: 'silent')
  final bool silent;

  @override
  @JsonKey(name: 'text')
  final String text;

  @override
  @JsonKey(name: 'thread_participants')
  final List<UserResponse>? threadParticipants;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  @override
  @JsonKey(name: 'user')
  final UserResponse user;

  Map<String, dynamic> toJson() => _$MessageResponseToJson(this);

  static MessageResponse fromJson(Map<String, dynamic> json) => _$MessageResponseFromJson(json);
}
