// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'message_action_request.g.dart';
part 'message_action_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class MessageActionRequest with _$MessageActionRequest {
  const MessageActionRequest({
    required this.formData,
  });

  @override
  @JsonKey(name: 'form_data')
  final Map<String, String> formData;

  Map<String, dynamic> toJson() => _$MessageActionRequestToJson(this);

  static MessageActionRequest fromJson(Map<String, dynamic> json) => _$MessageActionRequestFromJson(json);
}
