// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'message_flag_response.g.dart';
part 'message_flag_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class MessageFlagResponse with _$MessageFlagResponse {
  const MessageFlagResponse({
    this.approvedAt,
    required this.createdAt,
    required this.createdByAutomod,
    this.custom,
    this.details,
    this.message,
    this.moderationFeedback,
    this.moderationResult,
    this.reason,
    this.rejectedAt,
    this.reviewedAt,
    this.reviewedBy,
    required this.updatedAt,
    this.user,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'approved_at')
  final DateTime? approvedAt;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'created_by_automod')
  final bool createdByAutomod;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?>? custom;

  @override
  @JsonKey(name: 'details')
  final FlagDetailsResponse? details;

  @override
  @JsonKey(name: 'message')
  final MessageResponse? message;

  @override
  @JsonKey(name: 'moderation_feedback')
  final FlagFeedbackResponse? moderationFeedback;

  @override
  @JsonKey(name: 'moderation_result')
  final MessageModerationResult? moderationResult;

  @override
  @JsonKey(name: 'reason')
  final String? reason;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'rejected_at')
  final DateTime? rejectedAt;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'reviewed_at')
  final DateTime? reviewedAt;

  @override
  @JsonKey(name: 'reviewed_by')
  final UserResponse? reviewedBy;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  @override
  @JsonKey(name: 'user')
  final UserResponse? user;

  Map<String, dynamic> toJson() => _$MessageFlagResponseToJson(this);

  static MessageFlagResponse fromJson(Map<String, dynamic> json) => _$MessageFlagResponseFromJson(json);
}
