// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'message_delivered_event.g.dart';
part 'message_delivered_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class MessageDeliveredEvent extends core.WsEvent with _$MessageDeliveredEvent {
  const MessageDeliveredEvent({
    this.channel,
    this.channelCustom,
    this.channelId,
    this.channelMemberCount,
    this.channelMessageCount,
    this.channelType,
    this.cid,
    required this.createdAt,
    required this.custom,
    this.lastDeliveredAt,
    this.lastDeliveredMessageId,
    this.receivedAt,
    this.team,
    required this.type,
    this.user,
  });

  @override
  @JsonKey(name: 'channel')
  final ChannelResponse? channel;

  @override
  @JsonKey(name: 'channel_custom')
  final Map<String, Object?>? channelCustom;

  @override
  @JsonKey(name: 'channel_id')
  final String? channelId;

  @override
  @JsonKey(name: 'channel_member_count')
  final int? channelMemberCount;

  @override
  @JsonKey(name: 'channel_message_count')
  final int? channelMessageCount;

  @override
  @JsonKey(name: 'channel_type')
  final String? channelType;

  @override
  @JsonKey(name: 'cid')
  final String? cid;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @JsonKey(name: 'last_delivered_at')
  final String? lastDeliveredAt;

  @override
  @JsonKey(name: 'last_delivered_message_id')
  final String? lastDeliveredMessageId;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'received_at')
  final DateTime? receivedAt;

  @override
  @JsonKey(name: 'team')
  final String? team;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @JsonKey(name: 'user')
  final UserResponseCommonFields? user;

  Map<String, dynamic> toJson() => _$MessageDeliveredEventToJson(this);

  static MessageDeliveredEvent fromJson(Map<String, dynamic> json) => _$MessageDeliveredEventFromJson(json);
}
