// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'moderation_action_config_response.g.dart';
part 'moderation_action_config_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ModerationActionConfigResponse with _$ModerationActionConfigResponse {
  const ModerationActionConfigResponse({
    required this.action,
    this.custom,
    required this.description,
    required this.entityType,
    required this.icon,
    this.id,
    required this.order,
    this.queueType,
  });

  @override
  @JsonKey(name: 'action')
  final String action;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?>? custom;

  @override
  @JsonKey(name: 'description')
  final String description;

  @override
  @JsonKey(name: 'entity_type')
  final String entityType;

  @override
  @JsonKey(name: 'icon')
  final String icon;

  @override
  @JsonKey(name: 'id')
  final String? id;

  @override
  @JsonKey(name: 'order')
  final int order;

  @override
  @JsonKey(name: 'queue_type')
  final String? queueType;

  Map<String, dynamic> toJson() => _$ModerationActionConfigResponseToJson(this);

  static ModerationActionConfigResponse fromJson(Map<String, dynamic> json) =>
      _$ModerationActionConfigResponseFromJson(json);
}
