// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'moderation_mark_reviewed_event.g.dart';
part 'moderation_mark_reviewed_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ModerationMarkReviewedEvent extends core.WsEvent with _$ModerationMarkReviewedEvent {
  const ModerationMarkReviewedEvent({
    required this.createdAt,
    required this.custom,
    required this.item,
    this.message,
    this.receivedAt,
    required this.type,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @JsonKey(name: 'item')
  final ReviewQueueItemResponse item;

  @override
  @JsonKey(name: 'message')
  final MessageResponse? message;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'received_at')
  final DateTime? receivedAt;

  @override
  @JsonKey(name: 'type')
  final String type;

  Map<String, dynamic> toJson() => _$ModerationMarkReviewedEventToJson(this);

  static ModerationMarkReviewedEvent fromJson(Map<String, dynamic> json) => _$ModerationMarkReviewedEventFromJson(json);
}
