// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'moderation_queue_response.g.dart';
part 'moderation_queue_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ModerationQueueResponse with _$ModerationQueueResponse {
  const ModerationQueueResponse({
    required this.createdAt,
    required this.createdBy,
    required this.description,
    required this.filters,
    required this.id,
    required this.itemCount,
    required this.name,
    required this.sort,
    required this.type,
    required this.updatedAt,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'created_by')
  final String createdBy;

  @override
  @JsonKey(name: 'description')
  final String description;

  @override
  @JsonKey(name: 'filters')
  final Map<String, Object?> filters;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @JsonKey(name: 'item_count')
  final int itemCount;

  @override
  @JsonKey(name: 'name')
  final String name;

  @override
  @JsonKey(name: 'sort')
  final List<Map<String, Object?>> sort;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  Map<String, dynamic> toJson() => _$ModerationQueueResponseToJson(this);

  static ModerationQueueResponse fromJson(Map<String, dynamic> json) => _$ModerationQueueResponseFromJson(json);
}
