// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'moderation_flag_response.g.dart';
part 'moderation_flag_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ModerationFlagResponse with _$ModerationFlagResponse {
  const ModerationFlagResponse({
    required this.createdAt,
    this.custom,
    this.entityCreatorId,
    required this.entityId,
    required this.entityType,
    this.labels,
    this.moderationPayload,
    this.reason,
    required this.result,
    this.reviewQueueItem,
    this.reviewQueueItemId,
    required this.type,
    required this.updatedAt,
    this.user,
    required this.userId,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?>? custom;

  @override
  @JsonKey(name: 'entity_creator_id')
  final String? entityCreatorId;

  @override
  @JsonKey(name: 'entity_id')
  final String entityId;

  @override
  @JsonKey(name: 'entity_type')
  final String entityType;

  @override
  @JsonKey(name: 'labels')
  final List<String>? labels;

  @override
  @JsonKey(name: 'moderation_payload')
  final ModerationPayloadResponse? moderationPayload;

  @override
  @JsonKey(name: 'reason')
  final String? reason;

  @override
  @JsonKey(name: 'result')
  final List<Map<String, Object?>> result;

  @override
  @JsonKey(name: 'review_queue_item')
  final ReviewQueueItemResponse? reviewQueueItem;

  @override
  @JsonKey(name: 'review_queue_item_id')
  final String? reviewQueueItemId;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  @override
  @JsonKey(name: 'user')
  final UserResponse? user;

  @override
  @JsonKey(name: 'user_id')
  final String userId;

  Map<String, dynamic> toJson() => _$ModerationFlagResponseToJson(this);

  static ModerationFlagResponse fromJson(Map<String, dynamic> json) => _$ModerationFlagResponseFromJson(json);
}
