// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'mute_response.g.dart';
part 'mute_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class MuteResponse with _$MuteResponse {
  const MuteResponse({
    required this.duration,
    this.mutes,
    this.nonExistingUsers,
    this.ownUser,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'mutes')
  final List<UserMuteResponse>? mutes;

  @override
  @JsonKey(name: 'non_existing_users')
  final List<String>? nonExistingUsers;

  @override
  @JsonKey(name: 'own_user')
  final OwnUserResponse? ownUser;

  Map<String, dynamic> toJson() => _$MuteResponseToJson(this);

  static MuteResponse fromJson(Map<String, dynamic> json) => _$MuteResponseFromJson(json);
}
