// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'mute_channel_response.g.dart';
part 'mute_channel_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class MuteChannelResponse with _$MuteChannelResponse {
  const MuteChannelResponse({
    this.channelMute,
    this.channelMutes,
    required this.duration,
    this.ownUser,
  });

  @override
  @JsonKey(name: 'channel_mute')
  final ChannelMute? channelMute;

  @override
  @JsonKey(name: 'channel_mutes')
  final List<ChannelMute>? channelMutes;

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'own_user')
  final OwnUserResponse? ownUser;

  Map<String, dynamic> toJson() => _$MuteChannelResponseToJson(this);

  static MuteChannelResponse fromJson(Map<String, dynamic> json) => _$MuteChannelResponseFromJson(json);
}
