// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'mute_channel_request.g.dart';
part 'mute_channel_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class MuteChannelRequest with _$MuteChannelRequest {
  const MuteChannelRequest({
    this.channelCids,
    this.expiration,
  });

  @override
  @JsonKey(name: 'channel_cids')
  final List<String>? channelCids;

  @override
  @JsonKey(name: 'expiration')
  final int? expiration;

  Map<String, dynamic> toJson() => _$MuteChannelRequestToJson(this);

  static MuteChannelRequest fromJson(Map<String, dynamic> json) => _$MuteChannelRequestFromJson(json);
}
