// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'notification_thread_message_new_event.g.dart';
part 'notification_thread_message_new_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class NotificationThreadMessageNewEvent extends core.WsEvent with _$NotificationThreadMessageNewEvent {
  const NotificationThreadMessageNewEvent({
    required this.channel,
    this.channelCustom,
    this.channelId,
    this.channelMemberCount,
    this.channelMessageCount,
    this.channelType,
    this.cid,
    required this.createdAt,
    required this.custom,
    required this.message,
    required this.messageId,
    this.parentAuthor,
    this.receivedAt,
    this.team,
    required this.threadId,
    this.threadParticipants,
    required this.type,
    this.unreadThreadMessages,
    this.unreadThreads,
    required this.watcherCount,
  });

  @override
  @JsonKey(name: 'channel')
  final ChannelResponse channel;

  @override
  @JsonKey(name: 'channel_custom')
  final Map<String, Object?>? channelCustom;

  @override
  @JsonKey(name: 'channel_id')
  final String? channelId;

  @override
  @JsonKey(name: 'channel_member_count')
  final int? channelMemberCount;

  @override
  @JsonKey(name: 'channel_message_count')
  final int? channelMessageCount;

  @override
  @JsonKey(name: 'channel_type')
  final String? channelType;

  @override
  @JsonKey(name: 'cid')
  final String? cid;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @JsonKey(name: 'message')
  final MessageResponse message;

  @override
  @JsonKey(name: 'message_id')
  final String messageId;

  @override
  @JsonKey(name: 'parent_author')
  final String? parentAuthor;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'received_at')
  final DateTime? receivedAt;

  @override
  @JsonKey(name: 'team')
  final String? team;

  @override
  @JsonKey(name: 'thread_id')
  final String threadId;

  @override
  @JsonKey(name: 'thread_participants')
  final List<UserResponseCommonFields>? threadParticipants;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @JsonKey(name: 'unread_thread_messages')
  final int? unreadThreadMessages;

  @override
  @JsonKey(name: 'unread_threads')
  final int? unreadThreads;

  @override
  @JsonKey(name: 'watcher_count')
  final int watcherCount;

  Map<String, dynamic> toJson() => _$NotificationThreadMessageNewEventToJson(this);

  static NotificationThreadMessageNewEvent fromJson(Map<String, dynamic> json) =>
      _$NotificationThreadMessageNewEventFromJson(json);
}
