// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'notification_channel_truncated_event.g.dart';
part 'notification_channel_truncated_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class NotificationChannelTruncatedEvent extends core.WsEvent with _$NotificationChannelTruncatedEvent {
  const NotificationChannelTruncatedEvent({
    required this.channel,
    this.channelCustom,
    this.channelId,
    this.channelMemberCount,
    this.channelMessageCount,
    this.channelType,
    this.cid,
    required this.createdAt,
    required this.custom,
    this.groupedUnreadChannels,
    this.message,
    this.messageId,
    this.receivedAt,
    this.team,
    this.totalUnreadCount,
    required this.type,
    this.unreadChannels,
    this.unreadCount,
  });

  @override
  @JsonKey(name: 'channel')
  final ChannelResponse channel;

  @override
  @JsonKey(name: 'channel_custom')
  final Map<String, Object?>? channelCustom;

  @override
  @JsonKey(name: 'channel_id')
  final String? channelId;

  @override
  @JsonKey(name: 'channel_member_count')
  final int? channelMemberCount;

  @override
  @JsonKey(name: 'channel_message_count')
  final int? channelMessageCount;

  @override
  @JsonKey(name: 'channel_type')
  final String? channelType;

  @override
  @JsonKey(name: 'cid')
  final String? cid;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @JsonKey(name: 'grouped_unread_channels')
  final Map<String, int>? groupedUnreadChannels;

  @override
  @JsonKey(name: 'message')
  final MessageResponse? message;

  @override
  @JsonKey(name: 'message_id')
  final String? messageId;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'received_at')
  final DateTime? receivedAt;

  @override
  @JsonKey(name: 'team')
  final String? team;

  @override
  @JsonKey(name: 'total_unread_count')
  final int? totalUnreadCount;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @JsonKey(name: 'unread_channels')
  final int? unreadChannels;

  @override
  @JsonKey(name: 'unread_count')
  final int? unreadCount;

  Map<String, dynamic> toJson() => _$NotificationChannelTruncatedEventToJson(this);

  static NotificationChannelTruncatedEvent fromJson(Map<String, dynamic> json) =>
      _$NotificationChannelTruncatedEventFromJson(json);
}
