// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'ocr_rule.g.dart';
part 'ocr_rule.freezed.dart';

extension type const OCRRuleAction._(String _) implements String {
  static const bounce = OCRRuleAction._('bounce');
  static const bounceFlag = OCRRuleAction._('bounce_flag');
  static const bounceRemove = OCRRuleAction._('bounce_remove');
  static const flag = OCRRuleAction._('flag');
  static const remove = OCRRuleAction._('remove');
  static const shadow = OCRRuleAction._('shadow');

  factory OCRRuleAction.fromJson(String json) => OCRRuleAction._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class OCRRule with _$OCRRule {
  const OCRRule({
    required this.action,
    required this.label,
  });

  @override
  @JsonKey(name: 'action')
  final OCRRuleAction action;

  @override
  @JsonKey(name: 'label')
  final String label;

  Map<String, dynamic> toJson() => _$OCRRuleToJson(this);

  static OCRRule fromJson(Map<String, dynamic> json) => _$OCRRuleFromJson(json);
}
