// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'pagination_params.g.dart';
part 'pagination_params.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class PaginationParams with _$PaginationParams {
  const PaginationParams({
    this.limit,
    this.offset,
  });

  @override
  @JsonKey(name: 'limit')
  final int? limit;

  @override
  @JsonKey(name: 'offset')
  final int? offset;

  Map<String, dynamic> toJson() => _$PaginationParamsToJson(this);

  static PaginationParams fromJson(Map<String, dynamic> json) => _$PaginationParamsFromJson(json);
}
