// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'parsed_predefined_filter_response.g.dart';
part 'parsed_predefined_filter_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ParsedPredefinedFilterResponse with _$ParsedPredefinedFilterResponse {
  const ParsedPredefinedFilterResponse({
    required this.filter,
    required this.name,
    this.sort,
  });

  @override
  @JsonKey(name: 'filter')
  final Map<String, Object?> filter;

  @override
  @JsonKey(name: 'name')
  final String name;

  @override
  @JsonKey(name: 'sort')
  final List<SortParamRequest>? sort;

  Map<String, dynamic> toJson() => _$ParsedPredefinedFilterResponseToJson(this);

  static ParsedPredefinedFilterResponse fromJson(Map<String, dynamic> json) =>
      _$ParsedPredefinedFilterResponseFromJson(json);
}
