// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'poll_vote_response.g.dart';
part 'poll_vote_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class PollVoteResponse with _$PollVoteResponse {
  const PollVoteResponse({
    required this.duration,
    this.poll,
    this.vote,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'poll')
  final PollResponseData? poll;

  @override
  @JsonKey(name: 'vote')
  final PollVoteResponseData? vote;

  Map<String, dynamic> toJson() => _$PollVoteResponseToJson(this);

  static PollVoteResponse fromJson(Map<String, dynamic> json) => _$PollVoteResponseFromJson(json);
}
