// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'poll_option_request.g.dart';
part 'poll_option_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class PollOptionRequest with _$PollOptionRequest {
  const PollOptionRequest({
    this.custom,
    required this.id,
    this.text,
  });

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?>? custom;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @JsonKey(name: 'text')
  final String? text;

  Map<String, dynamic> toJson() => _$PollOptionRequestToJson(this);

  static PollOptionRequest fromJson(Map<String, dynamic> json) => _$PollOptionRequestFromJson(json);
}
