// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'push_preference_input.g.dart';
part 'push_preference_input.freezed.dart';

extension type const PushPreferenceInputCallLevel._(String _) implements String {
  static const all = PushPreferenceInputCallLevel._('all');
  static const default_ = PushPreferenceInputCallLevel._('default');
  static const none = PushPreferenceInputCallLevel._('none');

  factory PushPreferenceInputCallLevel.fromJson(String json) => PushPreferenceInputCallLevel._(json);

  String toJson() => this;
}

extension type const PushPreferenceInputChatLevel._(String _) implements String {
  static const all = PushPreferenceInputChatLevel._('all');
  static const allMentions = PushPreferenceInputChatLevel._('all_mentions');
  static const default_ = PushPreferenceInputChatLevel._('default');
  static const directMentions = PushPreferenceInputChatLevel._('direct_mentions');
  static const mentions = PushPreferenceInputChatLevel._('mentions');
  static const none = PushPreferenceInputChatLevel._('none');

  factory PushPreferenceInputChatLevel.fromJson(String json) => PushPreferenceInputChatLevel._(json);

  String toJson() => this;
}

extension type const PushPreferenceInputFeedsLevel._(String _) implements String {
  static const all = PushPreferenceInputFeedsLevel._('all');
  static const default_ = PushPreferenceInputFeedsLevel._('default');
  static const none = PushPreferenceInputFeedsLevel._('none');

  factory PushPreferenceInputFeedsLevel.fromJson(String json) => PushPreferenceInputFeedsLevel._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class PushPreferenceInput with _$PushPreferenceInput {
  const PushPreferenceInput({
    this.callLevel,
    this.channelCid,
    this.chatLevel,
    this.chatPreferences,
    this.disabledUntil,
    this.feedsLevel,
    this.feedsPreferences,
    this.removeDisable,
    this.userId,
  });

  @override
  @JsonKey(name: 'call_level')
  final PushPreferenceInputCallLevel? callLevel;

  @override
  @JsonKey(name: 'channel_cid')
  final String? channelCid;

  @override
  @JsonKey(name: 'chat_level')
  final PushPreferenceInputChatLevel? chatLevel;

  @override
  @JsonKey(name: 'chat_preferences')
  final ChatPreferencesInput? chatPreferences;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'disabled_until')
  final DateTime? disabledUntil;

  @override
  @JsonKey(name: 'feeds_level')
  final PushPreferenceInputFeedsLevel? feedsLevel;

  @override
  @JsonKey(name: 'feeds_preferences')
  final FeedsPreferences? feedsPreferences;

  @override
  @JsonKey(name: 'remove_disable')
  final bool? removeDisable;

  @override
  @JsonKey(name: 'user_id')
  final String? userId;

  Map<String, dynamic> toJson() => _$PushPreferenceInputToJson(this);

  static PushPreferenceInput fromJson(Map<String, dynamic> json) => _$PushPreferenceInputFromJson(json);
}
