// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_channels_request.g.dart';
part 'query_channels_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryChannelsRequest with _$QueryChannelsRequest {
  const QueryChannelsRequest({
    this.filterConditions,
    this.filterValues,
    this.limit,
    this.memberCustomInclude,
    this.memberLimit,
    this.messageLimit,
    this.offset,
    this.predefinedFilter,
    this.presence,
    this.sort,
    this.sortValues,
    this.state,
    this.watch,
  });

  @override
  @JsonKey(name: 'filter_conditions')
  final Map<String, Object?>? filterConditions;

  @override
  @JsonKey(name: 'filter_values')
  final Map<String, Object?>? filterValues;

  @override
  @JsonKey(name: 'limit')
  final int? limit;

  @override
  @JsonKey(name: 'member_custom_include')
  final List<String>? memberCustomInclude;

  @override
  @JsonKey(name: 'member_limit')
  final int? memberLimit;

  @override
  @JsonKey(name: 'message_limit')
  final int? messageLimit;

  @override
  @JsonKey(name: 'offset')
  final int? offset;

  @override
  @JsonKey(name: 'predefined_filter')
  final String? predefinedFilter;

  @override
  @JsonKey(name: 'presence')
  final bool? presence;

  @override
  @JsonKey(name: 'sort')
  final List<SortParamRequest>? sort;

  @override
  @JsonKey(name: 'sort_values')
  final Map<String, Object?>? sortValues;

  @override
  @JsonKey(name: 'state')
  final bool? state;

  @override
  @JsonKey(name: 'watch')
  final bool? watch;

  Map<String, dynamic> toJson() => _$QueryChannelsRequestToJson(this);

  static QueryChannelsRequest fromJson(Map<String, dynamic> json) => _$QueryChannelsRequestFromJson(json);
}
