// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_banned_users_payload.g.dart';
part 'query_banned_users_payload.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryBannedUsersPayload with _$QueryBannedUsersPayload {
  const QueryBannedUsersPayload({
    this.excludeExpiredBans,
    required this.filterConditions,
    this.limit,
    this.offset,
    this.sort,
  });

  @override
  @JsonKey(name: 'exclude_expired_bans')
  final bool? excludeExpiredBans;

  @override
  @JsonKey(name: 'filter_conditions')
  final Map<String, Object?> filterConditions;

  @override
  @JsonKey(name: 'limit')
  final int? limit;

  @override
  @JsonKey(name: 'offset')
  final int? offset;

  @override
  @JsonKey(name: 'sort')
  final List<SortParamRequest>? sort;

  Map<String, dynamic> toJson() => _$QueryBannedUsersPayloadToJson(this);

  static QueryBannedUsersPayload fromJson(Map<String, dynamic> json) => _$QueryBannedUsersPayloadFromJson(json);
}
