// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_appeals_response.g.dart';
part 'query_appeals_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryAppealsResponse with _$QueryAppealsResponse {
  const QueryAppealsResponse({
    required this.duration,
    required this.items,
    this.next,
    this.prev,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'items')
  final List<AppealItemResponse> items;

  @override
  @JsonKey(name: 'next')
  final String? next;

  @override
  @JsonKey(name: 'prev')
  final String? prev;

  Map<String, dynamic> toJson() => _$QueryAppealsResponseToJson(this);

  static QueryAppealsResponse fromJson(Map<String, dynamic> json) => _$QueryAppealsResponseFromJson(json);
}
