// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_review_queue_response.g.dart';
part 'query_review_queue_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryReviewQueueResponse with _$QueryReviewQueueResponse {
  const QueryReviewQueueResponse({
    required this.actionConfig,
    this.defaultActionConfig,
    required this.duration,
    this.filterConfig,
    required this.items,
    this.next,
    this.prev,
    required this.stats,
  });

  @override
  @JsonKey(name: 'action_config')
  final Map<String, List<ModerationActionConfigResponse>> actionConfig;

  @override
  @JsonKey(name: 'default_action_config')
  final Map<String, List<ModerationActionConfigResponse>>? defaultActionConfig;

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'filter_config')
  final FilterConfigResponse? filterConfig;

  @override
  @JsonKey(name: 'items')
  final List<ReviewQueueItemResponse> items;

  @override
  @JsonKey(name: 'next')
  final String? next;

  @override
  @JsonKey(name: 'prev')
  final String? prev;

  @override
  @JsonKey(name: 'stats')
  final Map<String, Object?> stats;

  Map<String, dynamic> toJson() => _$QueryReviewQueueResponseToJson(this);

  static QueryReviewQueueResponse fromJson(Map<String, dynamic> json) => _$QueryReviewQueueResponseFromJson(json);
}
