// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_users_payload.g.dart';
part 'query_users_payload.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryUsersPayload with _$QueryUsersPayload {
  const QueryUsersPayload({
    required this.filterConditions,
    this.idGt,
    this.idGte,
    this.idLt,
    this.idLte,
    this.includeDeactivatedUsers,
    this.limit,
    this.offset,
    this.presence,
    this.sort,
  });

  @override
  @JsonKey(name: 'filter_conditions')
  final Map<String, Object?> filterConditions;

  @override
  @JsonKey(name: 'id_gt')
  final String? idGt;

  @override
  @JsonKey(name: 'id_gte')
  final String? idGte;

  @override
  @JsonKey(name: 'id_lt')
  final String? idLt;

  @override
  @JsonKey(name: 'id_lte')
  final String? idLte;

  @override
  @JsonKey(name: 'include_deactivated_users')
  final bool? includeDeactivatedUsers;

  @override
  @JsonKey(name: 'limit')
  final int? limit;

  @override
  @JsonKey(name: 'offset')
  final int? offset;

  @override
  @JsonKey(name: 'presence')
  final bool? presence;

  @override
  @JsonKey(name: 'sort')
  final List<SortParamRequest>? sort;

  Map<String, dynamic> toJson() => _$QueryUsersPayloadToJson(this);

  static QueryUsersPayload fromJson(Map<String, dynamic> json) => _$QueryUsersPayloadFromJson(json);
}
