// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_members_payload.g.dart';
part 'query_members_payload.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryMembersPayload with _$QueryMembersPayload {
  const QueryMembersPayload({
    this.filterConditions,
    this.id,
    this.limit,
    this.members,
    this.offset,
    this.sort,
    required this.type,
  });

  @override
  @JsonKey(name: 'filter_conditions')
  final Map<String, Object?>? filterConditions;

  @override
  @JsonKey(name: 'id')
  final String? id;

  @override
  @JsonKey(name: 'limit')
  final int? limit;

  @override
  @JsonKey(name: 'members')
  final List<ChannelMemberRequest>? members;

  @override
  @JsonKey(name: 'offset')
  final int? offset;

  @override
  @JsonKey(name: 'sort')
  final List<SortParamRequest>? sort;

  @override
  @JsonKey(name: 'type')
  final String type;

  Map<String, dynamic> toJson() => _$QueryMembersPayloadToJson(this);

  static QueryMembersPayload fromJson(Map<String, dynamic> json) => _$QueryMembersPayloadFromJson(json);
}
