// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_polls_response.g.dart';
part 'query_polls_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryPollsResponse with _$QueryPollsResponse {
  const QueryPollsResponse({
    required this.duration,
    this.next,
    required this.polls,
    this.prev,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'next')
  final String? next;

  @override
  @JsonKey(name: 'polls')
  final List<PollResponseData> polls;

  @override
  @JsonKey(name: 'prev')
  final String? prev;

  Map<String, dynamic> toJson() => _$QueryPollsResponseToJson(this);

  static QueryPollsResponse fromJson(Map<String, dynamic> json) => _$QueryPollsResponseFromJson(json);
}
