// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_moderation_configs_response.g.dart';
part 'query_moderation_configs_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryModerationConfigsResponse with _$QueryModerationConfigsResponse {
  const QueryModerationConfigsResponse({
    required this.configs,
    required this.duration,
    this.next,
    this.prev,
  });

  @override
  @JsonKey(name: 'configs')
  final List<ConfigResponse> configs;

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'next')
  final String? next;

  @override
  @JsonKey(name: 'prev')
  final String? prev;

  Map<String, dynamic> toJson() => _$QueryModerationConfigsResponseToJson(this);

  static QueryModerationConfigsResponse fromJson(Map<String, dynamic> json) =>
      _$QueryModerationConfigsResponseFromJson(json);
}
