// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_reactions_response.g.dart';
part 'query_reactions_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryReactionsResponse with _$QueryReactionsResponse {
  const QueryReactionsResponse({
    required this.duration,
    this.next,
    this.prev,
    required this.reactions,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'next')
  final String? next;

  @override
  @JsonKey(name: 'prev')
  final String? prev;

  @override
  @JsonKey(name: 'reactions')
  final List<ReactionResponse> reactions;

  Map<String, dynamic> toJson() => _$QueryReactionsResponseToJson(this);

  static QueryReactionsResponse fromJson(Map<String, dynamic> json) => _$QueryReactionsResponseFromJson(json);
}
