// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_poll_votes_request.g.dart';
part 'query_poll_votes_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryPollVotesRequest with _$QueryPollVotesRequest {
  const QueryPollVotesRequest({
    this.filter,
    this.limit,
    this.next,
    this.prev,
    this.sort,
  });

  @override
  @JsonKey(name: 'filter')
  final Map<String, Object?>? filter;

  @override
  @JsonKey(name: 'limit')
  final int? limit;

  @override
  @JsonKey(name: 'next')
  final String? next;

  @override
  @JsonKey(name: 'prev')
  final String? prev;

  @override
  @JsonKey(name: 'sort')
  final List<SortParamRequest>? sort;

  Map<String, dynamic> toJson() => _$QueryPollVotesRequestToJson(this);

  static QueryPollVotesRequest fromJson(Map<String, dynamic> json) => _$QueryPollVotesRequestFromJson(json);
}
