// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_threads_request.g.dart';
part 'query_threads_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryThreadsRequest with _$QueryThreadsRequest {
  const QueryThreadsRequest({
    this.filter,
    this.limit,
    this.memberLimit,
    this.next,
    this.participantLimit,
    this.prev,
    this.replyLimit,
    this.sort,
    this.watch,
  });

  @override
  @JsonKey(name: 'filter')
  final Map<String, Object?>? filter;

  @override
  @JsonKey(name: 'limit')
  final int? limit;

  @override
  @JsonKey(name: 'member_limit')
  final int? memberLimit;

  @override
  @JsonKey(name: 'next')
  final String? next;

  @override
  @JsonKey(name: 'participant_limit')
  final int? participantLimit;

  @override
  @JsonKey(name: 'prev')
  final String? prev;

  @override
  @JsonKey(name: 'reply_limit')
  final int? replyLimit;

  @override
  @JsonKey(name: 'sort')
  final List<SortParamRequest>? sort;

  @override
  @JsonKey(name: 'watch')
  final bool? watch;

  Map<String, dynamic> toJson() => _$QueryThreadsRequestToJson(this);

  static QueryThreadsRequest fromJson(Map<String, dynamic> json) => _$QueryThreadsRequestFromJson(json);
}
