// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'reaction_request.g.dart';
part 'reaction_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ReactionRequest with _$ReactionRequest {
  const ReactionRequest({
    this.createdAt,
    this.custom,
    this.score,
    required this.type,
    this.updatedAt,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime? createdAt;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?>? custom;

  @override
  @JsonKey(name: 'score')
  final int? score;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime? updatedAt;

  Map<String, dynamic> toJson() => _$ReactionRequestToJson(this);

  static ReactionRequest fromJson(Map<String, dynamic> json) => _$ReactionRequestFromJson(json);
}
