// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'read_state_response.g.dart';
part 'read_state_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ReadStateResponse with _$ReadStateResponse {
  const ReadStateResponse({
    this.lastDeliveredAt,
    this.lastDeliveredMessageId,
    required this.lastRead,
    this.lastReadMessageId,
    required this.unreadMessages,
    required this.user,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'last_delivered_at')
  final DateTime? lastDeliveredAt;

  @override
  @JsonKey(name: 'last_delivered_message_id')
  final String? lastDeliveredMessageId;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'last_read')
  final DateTime lastRead;

  @override
  @JsonKey(name: 'last_read_message_id')
  final String? lastReadMessageId;

  @override
  @JsonKey(name: 'unread_messages')
  final int unreadMessages;

  @override
  @JsonKey(name: 'user')
  final UserResponse user;

  Map<String, dynamic> toJson() => _$ReadStateResponseToJson(this);

  static ReadStateResponse fromJson(Map<String, dynamic> json) => _$ReadStateResponseFromJson(json);
}
