// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'reminder_created_event.g.dart';
part 'reminder_created_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ReminderCreatedEvent extends core.WsEvent with _$ReminderCreatedEvent {
  const ReminderCreatedEvent({
    required this.cid,
    required this.createdAt,
    required this.custom,
    required this.messageId,
    this.parentId,
    this.receivedAt,
    required this.reminder,
    required this.type,
    required this.userId,
  });

  @override
  @JsonKey(name: 'cid')
  final String cid;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @JsonKey(name: 'message_id')
  final String messageId;

  @override
  @JsonKey(name: 'parent_id')
  final String? parentId;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'received_at')
  final DateTime? receivedAt;

  @override
  @JsonKey(name: 'reminder')
  final ReminderResponseData reminder;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @JsonKey(name: 'user_id')
  final String userId;

  Map<String, dynamic> toJson() => _$ReminderCreatedEventToJson(this);

  static ReminderCreatedEvent fromJson(Map<String, dynamic> json) => _$ReminderCreatedEventFromJson(json);
}
