// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'restore_action_request_payload.g.dart';
part 'restore_action_request_payload.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class RestoreActionRequestPayload with _$RestoreActionRequestPayload {
  const RestoreActionRequestPayload({
    this.decisionReason,
  });

  @override
  @JsonKey(name: 'decision_reason')
  final String? decisionReason;

  Map<String, dynamic> toJson() => _$RestoreActionRequestPayloadToJson(this);

  static RestoreActionRequestPayload fromJson(Map<String, dynamic> json) => _$RestoreActionRequestPayloadFromJson(json);
}
