// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'review_queue_item_response.g.dart';
part 'review_queue_item_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ReviewQueueItemResponse with _$ReviewQueueItemResponse {
  const ReviewQueueItemResponse({
    required this.actions,
    this.activity,
    required this.aiTextSeverity,
    this.appeal,
    this.assignedTo,
    required this.bans,
    this.call,
    this.completedAt,
    this.configKey,
    required this.createdAt,
    this.entityCreator,
    this.entityCreatorId,
    required this.entityId,
    required this.entityType,
    required this.escalated,
    this.escalatedAt,
    this.escalatedBy,
    this.escalationMetadata,
    this.feedsV2Activity,
    this.feedsV2Reaction,
    this.feedsV3Activity,
    this.feedsV3Comment,
    required this.flags,
    required this.flagsCount,
    required this.id,
    required this.languages,
    required this.latestModeratorAction,
    this.message,
    this.moderationPayload,
    this.reaction,
    required this.recommendedAction,
    this.reviewedAt,
    required this.reviewedBy,
    required this.severity,
    required this.status,
    this.teams,
    required this.updatedAt,
  });

  @override
  @JsonKey(name: 'actions')
  final List<ActionLogResponse> actions;

  @override
  @JsonKey(name: 'activity')
  final EnrichedActivity? activity;

  @override
  @JsonKey(name: 'ai_text_severity')
  final String aiTextSeverity;

  @override
  @JsonKey(name: 'appeal')
  final AppealItemResponse? appeal;

  @override
  @JsonKey(name: 'assigned_to')
  final UserResponse? assignedTo;

  @override
  @JsonKey(name: 'bans')
  final List<BanInfoResponse> bans;

  @override
  @JsonKey(name: 'call')
  final ModerationCallResponse? call;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'completed_at')
  final DateTime? completedAt;

  @override
  @JsonKey(name: 'config_key')
  final String? configKey;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'entity_creator')
  final EntityCreatorResponse? entityCreator;

  @override
  @JsonKey(name: 'entity_creator_id')
  final String? entityCreatorId;

  @override
  @JsonKey(name: 'entity_id')
  final String entityId;

  @override
  @JsonKey(name: 'entity_type')
  final String entityType;

  @override
  @JsonKey(name: 'escalated')
  final bool escalated;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'escalated_at')
  final DateTime? escalatedAt;

  @override
  @JsonKey(name: 'escalated_by')
  final String? escalatedBy;

  @override
  @JsonKey(name: 'escalation_metadata')
  final EscalationMetadata? escalationMetadata;

  @override
  @JsonKey(name: 'feeds_v2_activity')
  final EnrichedActivity? feedsV2Activity;

  @override
  @JsonKey(name: 'feeds_v2_reaction')
  final Reaction? feedsV2Reaction;

  @override
  @JsonKey(name: 'feeds_v3_activity')
  final FeedsV3ActivityResponse? feedsV3Activity;

  @override
  @JsonKey(name: 'feeds_v3_comment')
  final FeedsV3CommentResponse? feedsV3Comment;

  @override
  @JsonKey(name: 'flags')
  final List<ModerationFlagResponse> flags;

  @override
  @JsonKey(name: 'flags_count')
  final int flagsCount;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @JsonKey(name: 'languages')
  final List<String> languages;

  @override
  @JsonKey(name: 'latest_moderator_action')
  final String latestModeratorAction;

  @override
  @JsonKey(name: 'message')
  final ChatMessageResponse? message;

  @override
  @JsonKey(name: 'moderation_payload')
  final ModerationPayloadResponse? moderationPayload;

  @override
  @JsonKey(name: 'reaction')
  final Reaction? reaction;

  @override
  @JsonKey(name: 'recommended_action')
  final String recommendedAction;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'reviewed_at')
  final DateTime? reviewedAt;

  @override
  @JsonKey(name: 'reviewed_by')
  final String reviewedBy;

  @override
  @JsonKey(name: 'severity')
  final int severity;

  @override
  @JsonKey(name: 'status')
  final String status;

  @override
  @JsonKey(name: 'teams')
  final List<String>? teams;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  Map<String, dynamic> toJson() => _$ReviewQueueItemResponseToJson(this);

  static ReviewQueueItemResponse fromJson(Map<String, dynamic> json) => _$ReviewQueueItemResponseFromJson(json);
}
