// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'role.g.dart';
part 'role.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class Role with _$Role {
  const Role({
    required this.createdAt,
    required this.custom,
    required this.name,
    required this.scopes,
    required this.updatedAt,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom')
  final bool custom;

  @override
  @JsonKey(name: 'name')
  final String name;

  @override
  @JsonKey(name: 'scopes')
  final List<String> scopes;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  Map<String, dynamic> toJson() => _$RoleToJson(this);

  static Role fromJson(Map<String, dynamic> json) => _$RoleFromJson(json);
}
