// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'rule_builder_condition.g.dart';
part 'rule_builder_condition.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class RuleBuilderCondition with _$RuleBuilderCondition {
  const RuleBuilderCondition({
    this.callCustomPropertyParams,
    this.callTypeRuleParams,
    this.callViolationCountParams,
    this.channelMessageCountRuleParams,
    this.closedCaptionRuleParams,
    this.confidence,
    this.contentCountRuleParams,
    this.contentCustomPropertyCountParams,
    this.contentCustomPropertyParams,
    this.contentFlagCountRuleParams,
    this.floodIdenticalParams,
    this.floodSimilarParams,
    this.imageContentParams,
    this.imageRuleParams,
    this.ipContentCountRuleParams,
    this.ipFlagCountRuleParams,
    this.keyframeOcrRuleParams,
    this.keyframeRuleParams,
    this.ocrContentParams,
    this.textContentParams,
    this.textRuleParams,
    this.type,
    this.userCreatedWithinParams,
    this.userCustomPropertyParams,
    this.userFlagCountRuleParams,
    this.userIdenticalContentCountParams,
    this.userRoleParams,
    this.userRuleParams,
    this.videoContentParams,
    this.videoRuleParams,
  });

  @override
  @JsonKey(name: 'call_custom_property_params')
  final CallCustomPropertyParameters? callCustomPropertyParams;

  @override
  @JsonKey(name: 'call_type_rule_params')
  final CallTypeRuleParameters? callTypeRuleParams;

  @override
  @JsonKey(name: 'call_violation_count_params')
  final CallViolationCountParameters? callViolationCountParams;

  @override
  @JsonKey(name: 'channel_message_count_rule_params')
  final ChannelMessageCountRuleParameters? channelMessageCountRuleParams;

  @override
  @JsonKey(name: 'closed_caption_rule_params')
  final ClosedCaptionRuleParameters? closedCaptionRuleParams;

  @override
  @JsonKey(name: 'confidence')
  final double? confidence;

  @override
  @JsonKey(name: 'content_count_rule_params')
  final ContentCountRuleParameters? contentCountRuleParams;

  @override
  @JsonKey(name: 'content_custom_property_count_params')
  final ContentCustomPropertyCountParameters? contentCustomPropertyCountParams;

  @override
  @JsonKey(name: 'content_custom_property_params')
  final ContentCustomPropertyParameters? contentCustomPropertyParams;

  @override
  @JsonKey(name: 'content_flag_count_rule_params')
  final FlagCountRuleParameters? contentFlagCountRuleParams;

  @override
  @JsonKey(name: 'flood_identical_params')
  final FloodIdenticalRuleParameters? floodIdenticalParams;

  @override
  @JsonKey(name: 'flood_similar_params')
  final FloodSimilarRuleParameters? floodSimilarParams;

  @override
  @JsonKey(name: 'image_content_params')
  final ImageContentParameters? imageContentParams;

  @override
  @JsonKey(name: 'image_rule_params')
  final ImageRuleParameters? imageRuleParams;

  @override
  @JsonKey(name: 'ip_content_count_rule_params')
  final IPContentCountRuleParameters? ipContentCountRuleParams;

  @override
  @JsonKey(name: 'ip_flag_count_rule_params')
  final IPFlagCountRuleParameters? ipFlagCountRuleParams;

  @override
  @JsonKey(name: 'keyframe_ocr_rule_params')
  final KeyframeOCRRuleParameters? keyframeOcrRuleParams;

  @override
  @JsonKey(name: 'keyframe_rule_params')
  final KeyframeRuleParameters? keyframeRuleParams;

  @override
  @JsonKey(name: 'ocr_content_params')
  final OCRContentParameters? ocrContentParams;

  @override
  @JsonKey(name: 'text_content_params')
  final TextContentParameters? textContentParams;

  @override
  @JsonKey(name: 'text_rule_params')
  final TextRuleParameters? textRuleParams;

  @override
  @JsonKey(name: 'type')
  final String? type;

  @override
  @JsonKey(name: 'user_created_within_params')
  final UserCreatedWithinParameters? userCreatedWithinParams;

  @override
  @JsonKey(name: 'user_custom_property_params')
  final UserCustomPropertyParameters? userCustomPropertyParams;

  @override
  @JsonKey(name: 'user_flag_count_rule_params')
  final FlagCountRuleParameters? userFlagCountRuleParams;

  @override
  @JsonKey(name: 'user_identical_content_count_params')
  final UserIdenticalContentCountParameters? userIdenticalContentCountParams;

  @override
  @JsonKey(name: 'user_role_params')
  final UserRoleParameters? userRoleParams;

  @override
  @JsonKey(name: 'user_rule_params')
  final UserRuleParameters? userRuleParams;

  @override
  @JsonKey(name: 'video_content_params')
  final VideoContentParameters? videoContentParams;

  @override
  @JsonKey(name: 'video_rule_params')
  final VideoRuleParameters? videoRuleParams;

  Map<String, dynamic> toJson() => _$RuleBuilderConditionToJson(this);

  static RuleBuilderCondition fromJson(Map<String, dynamic> json) => _$RuleBuilderConditionFromJson(json);
}
