// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'rule_builder_action.g.dart';
part 'rule_builder_action.freezed.dart';

extension type const RuleBuilderActionType._(String _) implements String {
  static const banUser = RuleBuilderActionType._('ban_user');
  static const blockContent = RuleBuilderActionType._('block_content');
  static const blur = RuleBuilderActionType._('blur');
  static const bounceContent = RuleBuilderActionType._('bounce_content');
  static const bounceFlagContent = RuleBuilderActionType._('bounce_flag_content');
  static const bounceRemoveContent = RuleBuilderActionType._('bounce_remove_content');
  static const callBlur = RuleBuilderActionType._('call_blur');
  static const callWarning = RuleBuilderActionType._('call_warning');
  static const endCall = RuleBuilderActionType._('end_call');
  static const flagContent = RuleBuilderActionType._('flag_content');
  static const flagUser = RuleBuilderActionType._('flag_user');
  static const kickUser = RuleBuilderActionType._('kick_user');
  static const muteAudio = RuleBuilderActionType._('mute_audio');
  static const muteVideo = RuleBuilderActionType._('mute_video');
  static const shadowContent = RuleBuilderActionType._('shadow_content');
  static const warning = RuleBuilderActionType._('warning');
  static const webhookOnly = RuleBuilderActionType._('webhook_only');

  factory RuleBuilderActionType.fromJson(String json) => RuleBuilderActionType._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class RuleBuilderAction with _$RuleBuilderAction {
  const RuleBuilderAction({
    this.banOptions,
    this.callOptions,
    this.flagUserOptions,
    this.reason,
    this.skipInbox,
    this.type,
  });

  @override
  @JsonKey(name: 'ban_options')
  final BanOptions? banOptions;

  @override
  @JsonKey(name: 'call_options')
  final CallActionOptions? callOptions;

  @override
  @JsonKey(name: 'flag_user_options')
  final FlagUserOptions? flagUserOptions;

  @override
  @JsonKey(name: 'reason')
  final String? reason;

  @override
  @JsonKey(name: 'skip_inbox')
  final bool? skipInbox;

  @override
  @JsonKey(name: 'type')
  final RuleBuilderActionType? type;

  Map<String, dynamic> toJson() => _$RuleBuilderActionToJson(this);

  static RuleBuilderAction fromJson(Map<String, dynamic> json) => _$RuleBuilderActionFromJson(json);
}
