// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'rule_builder_config.g.dart';
part 'rule_builder_config.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class RuleBuilderConfig with _$RuleBuilderConfig {
  const RuleBuilderConfig({
    this.async,
    this.rules,
  });

  @override
  @JsonKey(name: 'async')
  final bool? async;

  @override
  @JsonKey(name: 'rules')
  final List<RuleBuilderRule>? rules;

  Map<String, dynamic> toJson() => _$RuleBuilderConfigToJson(this);

  static RuleBuilderConfig fromJson(Map<String, dynamic> json) => _$RuleBuilderConfigFromJson(json);
}
