// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'rule_builder_rule.g.dart';
part 'rule_builder_rule.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class RuleBuilderRule with _$RuleBuilderRule {
  const RuleBuilderRule({
    this.action,
    this.actionSequences,
    this.conditions,
    this.cooldownPeriod,
    this.groups,
    this.id,
    this.logic,
    required this.ruleType,
  });

  @override
  @JsonKey(name: 'action')
  final RuleBuilderAction? action;

  @override
  @JsonKey(name: 'action_sequences')
  final List<CallRuleActionSequence>? actionSequences;

  @override
  @JsonKey(name: 'conditions')
  final List<RuleBuilderCondition>? conditions;

  @override
  @JsonKey(name: 'cooldown_period')
  final String? cooldownPeriod;

  @override
  @JsonKey(name: 'groups')
  final List<RuleBuilderConditionGroup>? groups;

  @override
  @JsonKey(name: 'id')
  final String? id;

  @override
  @JsonKey(name: 'logic')
  final String? logic;

  @override
  @JsonKey(name: 'rule_type')
  final String ruleType;

  Map<String, dynamic> toJson() => _$RuleBuilderRuleToJson(this);

  static RuleBuilderRule fromJson(Map<String, dynamic> json) => _$RuleBuilderRuleFromJson(json);
}
