// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'rule_builder_condition_group.g.dart';
part 'rule_builder_condition_group.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class RuleBuilderConditionGroup with _$RuleBuilderConditionGroup {
  const RuleBuilderConditionGroup({
    this.conditions,
    this.logic,
  });

  @override
  @JsonKey(name: 'conditions')
  final List<RuleBuilderCondition>? conditions;

  @override
  @JsonKey(name: 'logic')
  final String? logic;

  Map<String, dynamic> toJson() => _$RuleBuilderConditionGroupToJson(this);

  static RuleBuilderConditionGroup fromJson(Map<String, dynamic> json) => _$RuleBuilderConditionGroupFromJson(json);
}
