// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'search_warning.g.dart';
part 'search_warning.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SearchWarning with _$SearchWarning {
  const SearchWarning({
    this.channelSearchCids,
    this.channelSearchCount,
    required this.warningCode,
    required this.warningDescription,
  });

  @override
  @JsonKey(name: 'channel_search_cids')
  final List<String>? channelSearchCids;

  @override
  @JsonKey(name: 'channel_search_count')
  final int? channelSearchCount;

  @override
  @JsonKey(name: 'warning_code')
  final int warningCode;

  @override
  @JsonKey(name: 'warning_description')
  final String warningDescription;

  Map<String, dynamic> toJson() => _$SearchWarningToJson(this);

  static SearchWarning fromJson(Map<String, dynamic> json) => _$SearchWarningFromJson(json);
}
