// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'send_reaction_response.g.dart';
part 'send_reaction_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SendReactionResponse with _$SendReactionResponse {
  const SendReactionResponse({
    required this.duration,
    required this.message,
    required this.reaction,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'message')
  final MessageResponse message;

  @override
  @JsonKey(name: 'reaction')
  final ReactionResponse reaction;

  Map<String, dynamic> toJson() => _$SendReactionResponseToJson(this);

  static SendReactionResponse fromJson(Map<String, dynamic> json) => _$SendReactionResponseFromJson(json);
}
