// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'send_message_response.g.dart';
part 'send_message_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SendMessageResponse with _$SendMessageResponse {
  const SendMessageResponse({
    this.channelContext,
    required this.duration,
    this.mentionedMembers,
    required this.message,
  });

  @override
  @JsonKey(name: 'channel_context')
  final ChannelContextResponse? channelContext;

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'mentioned_members')
  final Map<String, bool>? mentionedMembers;

  @override
  @JsonKey(name: 'message')
  final MessageResponse message;

  Map<String, dynamic> toJson() => _$SendMessageResponseToJson(this);

  static SendMessageResponse fromJson(Map<String, dynamic> json) => _$SendMessageResponseFromJson(json);
}
