// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'send_event_request.g.dart';
part 'send_event_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SendEventRequest with _$SendEventRequest {
  const SendEventRequest({
    required this.event,
  });

  @override
  @JsonKey(name: 'event')
  final EventRequest event;

  Map<String, dynamic> toJson() => _$SendEventRequestToJson(this);

  static SendEventRequest fromJson(Map<String, dynamic> json) => _$SendEventRequestFromJson(json);
}
