// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'shared_location_response_data.g.dart';
part 'shared_location_response_data.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SharedLocationResponseData with _$SharedLocationResponseData {
  const SharedLocationResponseData({
    this.channel,
    required this.channelCid,
    required this.createdAt,
    required this.createdByDeviceId,
    this.endAt,
    required this.latitude,
    required this.longitude,
    this.message,
    required this.messageId,
    required this.updatedAt,
    required this.userId,
  });

  @override
  @JsonKey(name: 'channel')
  final ChannelResponse? channel;

  @override
  @JsonKey(name: 'channel_cid')
  final String channelCid;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'created_by_device_id')
  final String createdByDeviceId;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'end_at')
  final DateTime? endAt;

  @override
  @JsonKey(name: 'latitude')
  final double latitude;

  @override
  @JsonKey(name: 'longitude')
  final double longitude;

  @override
  @JsonKey(name: 'message')
  final MessageResponse? message;

  @override
  @JsonKey(name: 'message_id')
  final String messageId;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  @override
  @JsonKey(name: 'user_id')
  final String userId;

  Map<String, dynamic> toJson() => _$SharedLocationResponseDataToJson(this);

  static SharedLocationResponseData fromJson(Map<String, dynamic> json) => _$SharedLocationResponseDataFromJson(json);
}
