// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'sort_param_request.g.dart';
part 'sort_param_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SortParamRequest with _$SortParamRequest {
  const SortParamRequest({
    this.direction,
    this.field,
    this.type,
  });

  @override
  @JsonKey(name: 'direction')
  final int? direction;

  @override
  @JsonKey(name: 'field')
  final String? field;

  @override
  @JsonKey(name: 'type')
  final String? type;

  Map<String, dynamic> toJson() => _$SortParamRequestToJson(this);

  static SortParamRequest fromJson(Map<String, dynamic> json) => _$SortParamRequestFromJson(json);
}
