// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'submit_action_response.g.dart';
part 'submit_action_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SubmitActionResponse with _$SubmitActionResponse {
  const SubmitActionResponse({
    this.appealItem,
    this.autoRestoreWarning,
    required this.duration,
    this.item,
  });

  @override
  @JsonKey(name: 'appeal_item')
  final AppealItemResponse? appealItem;

  @override
  @JsonKey(name: 'auto_restore_warning')
  final String? autoRestoreWarning;

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'item')
  final ReviewQueueItemResponse? item;

  Map<String, dynamic> toJson() => _$SubmitActionResponseToJson(this);

  static SubmitActionResponse fromJson(Map<String, dynamic> json) => _$SubmitActionResponseFromJson(json);
}
