// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'sync_request.g.dart';
part 'sync_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SyncRequest with _$SyncRequest {
  const SyncRequest({
    required this.channelCids,
    required this.lastSyncAt,
  });

  @override
  @JsonKey(name: 'channel_cids')
  final List<String> channelCids;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'last_sync_at')
  final DateTime lastSyncAt;

  Map<String, dynamic> toJson() => _$SyncRequestToJson(this);

  static SyncRequest fromJson(Map<String, dynamic> json) => _$SyncRequestFromJson(json);
}
