// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'thresholds.g.dart';
part 'thresholds.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class Thresholds with _$Thresholds {
  const Thresholds({
    this.explicit,
    this.spam,
    this.toxic,
  });

  @override
  @JsonKey(name: 'explicit')
  final LabelThresholds? explicit;

  @override
  @JsonKey(name: 'spam')
  final LabelThresholds? spam;

  @override
  @JsonKey(name: 'toxic')
  final LabelThresholds? toxic;

  Map<String, dynamic> toJson() => _$ThresholdsToJson(this);

  static Thresholds fromJson(Map<String, dynamic> json) => _$ThresholdsFromJson(json);
}
