// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'translate_message_request.g.dart';
part 'translate_message_request.freezed.dart';

extension type const TranslateMessageRequestLanguage._(String _) implements String {
  static const af = TranslateMessageRequestLanguage._('af');
  static const am = TranslateMessageRequestLanguage._('am');
  static const ar = TranslateMessageRequestLanguage._('ar');
  static const az = TranslateMessageRequestLanguage._('az');
  static const bg = TranslateMessageRequestLanguage._('bg');
  static const bn = TranslateMessageRequestLanguage._('bn');
  static const bs = TranslateMessageRequestLanguage._('bs');
  static const cs = TranslateMessageRequestLanguage._('cs');
  static const da = TranslateMessageRequestLanguage._('da');
  static const de = TranslateMessageRequestLanguage._('de');
  static const el = TranslateMessageRequestLanguage._('el');
  static const en = TranslateMessageRequestLanguage._('en');
  static const es = TranslateMessageRequestLanguage._('es');
  static const esMX = TranslateMessageRequestLanguage._('es-MX');
  static const et = TranslateMessageRequestLanguage._('et');
  static const fa = TranslateMessageRequestLanguage._('fa');
  static const faAF = TranslateMessageRequestLanguage._('fa-AF');
  static const fi = TranslateMessageRequestLanguage._('fi');
  static const fr = TranslateMessageRequestLanguage._('fr');
  static const frCA = TranslateMessageRequestLanguage._('fr-CA');
  static const ha = TranslateMessageRequestLanguage._('ha');
  static const he = TranslateMessageRequestLanguage._('he');
  static const hi = TranslateMessageRequestLanguage._('hi');
  static const hr = TranslateMessageRequestLanguage._('hr');
  static const ht = TranslateMessageRequestLanguage._('ht');
  static const hu = TranslateMessageRequestLanguage._('hu');
  static const id = TranslateMessageRequestLanguage._('id');
  static const it = TranslateMessageRequestLanguage._('it');
  static const ja = TranslateMessageRequestLanguage._('ja');
  static const ka = TranslateMessageRequestLanguage._('ka');
  static const ko = TranslateMessageRequestLanguage._('ko');
  static const lt = TranslateMessageRequestLanguage._('lt');
  static const lv = TranslateMessageRequestLanguage._('lv');
  static const ms = TranslateMessageRequestLanguage._('ms');
  static const nl = TranslateMessageRequestLanguage._('nl');
  static const no = TranslateMessageRequestLanguage._('no');
  static const pl = TranslateMessageRequestLanguage._('pl');
  static const ps = TranslateMessageRequestLanguage._('ps');
  static const pt = TranslateMessageRequestLanguage._('pt');
  static const ro = TranslateMessageRequestLanguage._('ro');
  static const ru = TranslateMessageRequestLanguage._('ru');
  static const sk = TranslateMessageRequestLanguage._('sk');
  static const sl = TranslateMessageRequestLanguage._('sl');
  static const so = TranslateMessageRequestLanguage._('so');
  static const sq = TranslateMessageRequestLanguage._('sq');
  static const sr = TranslateMessageRequestLanguage._('sr');
  static const sv = TranslateMessageRequestLanguage._('sv');
  static const sw = TranslateMessageRequestLanguage._('sw');
  static const ta = TranslateMessageRequestLanguage._('ta');
  static const th = TranslateMessageRequestLanguage._('th');
  static const tl = TranslateMessageRequestLanguage._('tl');
  static const tr = TranslateMessageRequestLanguage._('tr');
  static const uk = TranslateMessageRequestLanguage._('uk');
  static const ur = TranslateMessageRequestLanguage._('ur');
  static const vi = TranslateMessageRequestLanguage._('vi');
  static const zh = TranslateMessageRequestLanguage._('zh');
  static const zhTW = TranslateMessageRequestLanguage._('zh-TW');

  factory TranslateMessageRequestLanguage.fromJson(String json) => TranslateMessageRequestLanguage._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class TranslateMessageRequest with _$TranslateMessageRequest {
  const TranslateMessageRequest({
    required this.language,
  });

  @override
  @JsonKey(name: 'language')
  final TranslateMessageRequestLanguage language;

  Map<String, dynamic> toJson() => _$TranslateMessageRequestToJson(this);

  static TranslateMessageRequest fromJson(Map<String, dynamic> json) => _$TranslateMessageRequestFromJson(json);
}
