// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'unread_counts_channel_type.g.dart';
part 'unread_counts_channel_type.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UnreadCountsChannelType with _$UnreadCountsChannelType {
  const UnreadCountsChannelType({
    required this.channelCount,
    required this.channelType,
    required this.unreadCount,
  });

  @override
  @JsonKey(name: 'channel_count')
  final int channelCount;

  @override
  @JsonKey(name: 'channel_type')
  final String channelType;

  @override
  @JsonKey(name: 'unread_count')
  final int unreadCount;

  Map<String, dynamic> toJson() => _$UnreadCountsChannelTypeToJson(this);

  static UnreadCountsChannelType fromJson(Map<String, dynamic> json) => _$UnreadCountsChannelTypeFromJson(json);
}
