// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'update_user_partial_request.g.dart';
part 'update_user_partial_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UpdateUserPartialRequest with _$UpdateUserPartialRequest {
  const UpdateUserPartialRequest({
    required this.id,
    this.set,
    this.unset,
  });

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @JsonKey(name: 'set')
  final Map<String, Object?>? set;

  @override
  @JsonKey(name: 'unset')
  final List<String>? unset;

  Map<String, dynamic> toJson() => _$UpdateUserPartialRequestToJson(this);

  static UpdateUserPartialRequest fromJson(Map<String, dynamic> json) => _$UpdateUserPartialRequestFromJson(json);
}
