// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'update_users_partial_request.g.dart';
part 'update_users_partial_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UpdateUsersPartialRequest with _$UpdateUsersPartialRequest {
  const UpdateUsersPartialRequest({
    required this.users,
  });

  @override
  @JsonKey(name: 'users')
  final List<UpdateUserPartialRequest> users;

  Map<String, dynamic> toJson() => _$UpdateUsersPartialRequestToJson(this);

  static UpdateUsersPartialRequest fromJson(Map<String, dynamic> json) => _$UpdateUsersPartialRequestFromJson(json);
}
