// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first, provide_deprecation_message

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'update_users_response.g.dart';
part 'update_users_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UpdateUsersResponse with _$UpdateUsersResponse {
  const UpdateUsersResponse({
    required this.duration,
    required this.membershipDeletionTaskId,
    required this.users,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @Deprecated(
    "Always empty. Removing a user from a team no longer deletes their memberships in that team's channels, so there is no task to poll.",
  )
  @JsonKey(name: 'membership_deletion_task_id')
  final String membershipDeletionTaskId;

  @override
  @JsonKey(name: 'users')
  final Map<String, FullUserResponse> users;

  Map<String, dynamic> toJson() => _$UpdateUsersResponseToJson(this);

  static UpdateUsersResponse fromJson(Map<String, dynamic> json) => _$UpdateUsersResponseFromJson(json);
}
