// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'update_live_location_request.g.dart';
part 'update_live_location_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UpdateLiveLocationRequest with _$UpdateLiveLocationRequest {
  const UpdateLiveLocationRequest({
    this.endAt,
    this.latitude,
    this.longitude,
    required this.messageId,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'end_at')
  final DateTime? endAt;

  @override
  @JsonKey(name: 'latitude')
  final double? latitude;

  @override
  @JsonKey(name: 'longitude')
  final double? longitude;

  @override
  @JsonKey(name: 'message_id')
  final String messageId;

  Map<String, dynamic> toJson() => _$UpdateLiveLocationRequestToJson(this);

  static UpdateLiveLocationRequest fromJson(Map<String, dynamic> json) => _$UpdateLiveLocationRequestFromJson(json);
}
