// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'update_message_partial_response.g.dart';
part 'update_message_partial_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UpdateMessagePartialResponse with _$UpdateMessagePartialResponse {
  const UpdateMessagePartialResponse({
    required this.duration,
    this.message,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'message')
  final MessageResponse? message;

  Map<String, dynamic> toJson() => _$UpdateMessagePartialResponseToJson(this);

  static UpdateMessagePartialResponse fromJson(Map<String, dynamic> json) =>
      _$UpdateMessagePartialResponseFromJson(json);
}
