// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first, provide_deprecation_message

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'update_reminder_request.g.dart';
part 'update_reminder_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UpdateReminderRequest with _$UpdateReminderRequest {
  const UpdateReminderRequest({
    this.expiresAt,
    this.remindAt,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'expires_at')
  final DateTime? expiresAt;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'remind_at')
  final DateTime? remindAt;

  Map<String, dynamic> toJson() => _$UpdateReminderRequestToJson(this);

  static UpdateReminderRequest fromJson(Map<String, dynamic> json) => _$UpdateReminderRequestFromJson(json);
}
