// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'update_message_request.g.dart';
part 'update_message_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UpdateMessageRequest with _$UpdateMessageRequest {
  const UpdateMessageRequest({
    required this.message,
    this.skipEnrichUrl,
    this.skipPush,
  });

  @override
  @JsonKey(name: 'message')
  final MessageRequest message;

  @override
  @JsonKey(name: 'skip_enrich_url')
  final bool? skipEnrichUrl;

  @override
  @JsonKey(name: 'skip_push')
  final bool? skipPush;

  Map<String, dynamic> toJson() => _$UpdateMessageRequestToJson(this);

  static UpdateMessageRequest fromJson(Map<String, dynamic> json) => _$UpdateMessageRequestFromJson(json);
}
