// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'upload_channel_request.g.dart';
part 'upload_channel_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UploadChannelRequest with _$UploadChannelRequest {
  const UploadChannelRequest({
    this.file,
    this.uploadSizes,
    this.user,
  });

  @override
  @JsonKey(name: 'file')
  final String? file;

  @override
  @JsonKey(name: 'upload_sizes')
  final List<ImageSize>? uploadSizes;

  @override
  @JsonKey(name: 'user')
  final OnlyUserID? user;

  Map<String, dynamic> toJson() => _$UploadChannelRequestToJson(this);

  static UploadChannelRequest fromJson(Map<String, dynamic> json) => _$UploadChannelRequestFromJson(json);
}
