// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'upload_channel_response.g.dart';
part 'upload_channel_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UploadChannelResponse with _$UploadChannelResponse {
  const UploadChannelResponse({
    required this.duration,
    this.file,
    this.moderationAction,
    this.thumbUrl,
    this.uploadSizes,
  });

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'file')
  final String? file;

  @override
  @JsonKey(name: 'moderation_action')
  final String? moderationAction;

  @override
  @JsonKey(name: 'thumb_url')
  final String? thumbUrl;

  @override
  @JsonKey(name: 'upload_sizes')
  final List<ImageSize>? uploadSizes;

  Map<String, dynamic> toJson() => _$UploadChannelResponseToJson(this);

  static UploadChannelResponse fromJson(Map<String, dynamic> json) => _$UploadChannelResponseFromJson(json);
}
