// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'upsert_config_request.g.dart';
part 'upsert_config_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UpsertConfigRequest with _$UpsertConfigRequest {
  const UpsertConfigRequest({
    this.aiAudioConfig,
    this.aiImageConfig,
    this.aiTextConfig,
    this.aiVideoConfig,
    this.async,
    this.automodPlatformCircumventionConfig,
    this.automodSemanticFiltersConfig,
    this.automodToxicityConfig,
    this.awsRekognitionConfig,
    this.blockListConfig,
    this.bodyguardConfig,
    this.floodConfig,
    this.googleVisionConfig,
    required this.key,
    this.llmConfig,
    this.ruleBuilderConfig,
    this.team,
    this.velocityFilterConfig,
    this.videoCallRuleConfig,
  });

  @override
  @JsonKey(name: 'ai_audio_config')
  final AIAudioConfigRequest? aiAudioConfig;

  @override
  @JsonKey(name: 'ai_image_config')
  final AIImageConfig? aiImageConfig;

  @override
  @JsonKey(name: 'ai_text_config')
  final AITextConfig? aiTextConfig;

  @override
  @JsonKey(name: 'ai_video_config')
  final AIVideoConfig? aiVideoConfig;

  @override
  @JsonKey(name: 'async')
  final bool? async;

  @override
  @JsonKey(name: 'automod_platform_circumvention_config')
  final AutomodPlatformCircumventionConfig? automodPlatformCircumventionConfig;

  @override
  @JsonKey(name: 'automod_semantic_filters_config')
  final AutomodSemanticFiltersConfig? automodSemanticFiltersConfig;

  @override
  @JsonKey(name: 'automod_toxicity_config')
  final AutomodToxicityConfig? automodToxicityConfig;

  @override
  @JsonKey(name: 'aws_rekognition_config')
  final AIImageConfig? awsRekognitionConfig;

  @override
  @JsonKey(name: 'block_list_config')
  final BlockListConfig? blockListConfig;

  @override
  @JsonKey(name: 'bodyguard_config')
  final AITextConfig? bodyguardConfig;

  @override
  @JsonKey(name: 'flood_config')
  final FloodConfig? floodConfig;

  @override
  @JsonKey(name: 'google_vision_config')
  final GoogleVisionConfig? googleVisionConfig;

  @override
  @JsonKey(name: 'key')
  final String key;

  @override
  @JsonKey(name: 'llm_config')
  final LLMConfig? llmConfig;

  @override
  @JsonKey(name: 'rule_builder_config')
  final RuleBuilderConfig? ruleBuilderConfig;

  @override
  @JsonKey(name: 'team')
  final String? team;

  @override
  @JsonKey(name: 'velocity_filter_config')
  final VelocityFilterConfig? velocityFilterConfig;

  @override
  @JsonKey(name: 'video_call_rule_config')
  final VideoCallRuleConfig? videoCallRuleConfig;

  Map<String, dynamic> toJson() => _$UpsertConfigRequestToJson(this);

  static UpsertConfigRequest fromJson(Map<String, dynamic> json) => _$UpsertConfigRequestFromJson(json);
}
