// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'user_reaction_count_rule_parameters.g.dart';
part 'user_reaction_count_rule_parameters.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UserReactionCountRuleParameters with _$UserReactionCountRuleParameters {
  const UserReactionCountRuleParameters({
    this.count,
    this.threshold,
    this.timeWindow,
  });

  @override
  @JsonKey(name: 'count')
  final String? count;

  @override
  @JsonKey(name: 'threshold')
  final int? threshold;

  @override
  @JsonKey(name: 'time_window')
  final String? timeWindow;

  Map<String, dynamic> toJson() => _$UserReactionCountRuleParametersToJson(this);

  static UserReactionCountRuleParameters fromJson(Map<String, dynamic> json) =>
      _$UserReactionCountRuleParametersFromJson(json);
}
