// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'user_deleted_event.g.dart';
part 'user_deleted_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UserDeletedEvent extends core.WsEvent with _$UserDeletedEvent {
  const UserDeletedEvent({
    required this.createdAt,
    required this.custom,
    required this.deleteConversation,
    required this.deleteConversationChannels,
    required this.deleteMessages,
    required this.deleteUser,
    required this.hardDelete,
    required this.markMessagesDeleted,
    this.receivedAt,
    required this.type,
    required this.user,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @JsonKey(name: 'delete_conversation')
  final String deleteConversation;

  @override
  @JsonKey(name: 'delete_conversation_channels')
  final bool deleteConversationChannels;

  @override
  @JsonKey(name: 'delete_messages')
  final String deleteMessages;

  @override
  @JsonKey(name: 'delete_user')
  final String deleteUser;

  @override
  @JsonKey(name: 'hard_delete')
  final bool hardDelete;

  @override
  @JsonKey(name: 'mark_messages_deleted')
  final bool markMessagesDeleted;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'received_at')
  final DateTime? receivedAt;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @JsonKey(name: 'user')
  final UserResponseCommonFields user;

  Map<String, dynamic> toJson() => _$UserDeletedEventToJson(this);

  static UserDeletedEvent fromJson(Map<String, dynamic> json) => _$UserDeletedEventFromJson(json);
}
