// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'user_custom_property_parameters.g.dart';
part 'user_custom_property_parameters.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UserCustomPropertyParameters with _$UserCustomPropertyParameters {
  const UserCustomPropertyParameters({
    this.operator,
    this.propertyKey,
  });

  @override
  @JsonKey(name: 'operator')
  final String? operator;

  @override
  @JsonKey(name: 'property_key')
  final String? propertyKey;

  Map<String, dynamic> toJson() => _$UserCustomPropertyParametersToJson(this);

  static UserCustomPropertyParameters fromJson(Map<String, dynamic> json) =>
      _$UserCustomPropertyParametersFromJson(json);
}
