// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'user_reactivated_event.g.dart';
part 'user_reactivated_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UserReactivatedEvent extends core.WsEvent with _$UserReactivatedEvent {
  const UserReactivatedEvent({
    required this.createdAt,
    this.createdBy,
    required this.custom,
    this.receivedAt,
    required this.type,
    required this.user,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'created_by')
  final UserResponseCommonFields? createdBy;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'received_at')
  final DateTime? receivedAt;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @JsonKey(name: 'user')
  final UserResponseCommonFields user;

  Map<String, dynamic> toJson() => _$UserReactivatedEventToJson(this);

  static UserReactivatedEvent fromJson(Map<String, dynamic> json) => _$UserReactivatedEventFromJson(json);
}
