// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'user_group_response.g.dart';
part 'user_group_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UserGroupResponse with _$UserGroupResponse {
  const UserGroupResponse({
    required this.createdAt,
    this.createdBy,
    this.description,
    required this.id,
    this.members,
    required this.name,
    this.teamId,
    required this.updatedAt,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'created_by')
  final String? createdBy;

  @override
  @JsonKey(name: 'description')
  final String? description;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @JsonKey(name: 'members')
  final List<UserGroupMember>? members;

  @override
  @JsonKey(name: 'name')
  final String name;

  @override
  @JsonKey(name: 'team_id')
  final String? teamId;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  Map<String, dynamic> toJson() => _$UserGroupResponseToJson(this);

  static UserGroupResponse fromJson(Map<String, dynamic> json) => _$UserGroupResponseFromJson(json);
}
