// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'user_created_within_parameters.g.dart';
part 'user_created_within_parameters.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UserCreatedWithinParameters with _$UserCreatedWithinParameters {
  const UserCreatedWithinParameters({
    this.maxAge,
  });

  @override
  @JsonKey(name: 'max_age')
  final String? maxAge;

  Map<String, dynamic> toJson() => _$UserCreatedWithinParametersToJson(this);

  static UserCreatedWithinParameters fromJson(Map<String, dynamic> json) => _$UserCreatedWithinParametersFromJson(json);
}
