// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'user_role_parameters.g.dart';
part 'user_role_parameters.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UserRoleParameters with _$UserRoleParameters {
  const UserRoleParameters({
    this.operator,
    this.role,
  });

  @override
  @JsonKey(name: 'operator')
  final String? operator;

  @override
  @JsonKey(name: 'role')
  final String? role;

  Map<String, dynamic> toJson() => _$UserRoleParametersToJson(this);

  static UserRoleParameters fromJson(Map<String, dynamic> json) => _$UserRoleParametersFromJson(json);
}
