// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'video_call_rule_config.g.dart';
part 'video_call_rule_config.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class VideoCallRuleConfig with _$VideoCallRuleConfig {
  const VideoCallRuleConfig({
    required this.flagAllLabels,
    required this.flaggedLabels,
    required this.rules,
  });

  @override
  @JsonKey(name: 'flag_all_labels')
  final bool flagAllLabels;

  @override
  @JsonKey(name: 'flagged_labels')
  final List<String> flaggedLabels;

  @override
  @JsonKey(name: 'rules')
  final List<HarmConfig> rules;

  Map<String, dynamic> toJson() => _$VideoCallRuleConfigToJson(this);

  static VideoCallRuleConfig fromJson(Map<String, dynamic> json) => _$VideoCallRuleConfigFromJson(json);
}
