// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'vote_data.g.dart';
part 'vote_data.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class VoteData with _$VoteData {
  const VoteData({
    this.answerText,
    this.optionId,
  });

  @override
  @JsonKey(name: 'answer_text')
  final String? answerText;

  @override
  @JsonKey(name: 'option_id')
  final String? optionId;

  Map<String, dynamic> toJson() => _$VoteDataToJson(this);

  static VoteData fromJson(Map<String, dynamic> json) => _$VoteDataFromJson(json);
}
