// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'wrapped_unread_counts_response.g.dart';
part 'wrapped_unread_counts_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class WrappedUnreadCountsResponse with _$WrappedUnreadCountsResponse {
  const WrappedUnreadCountsResponse({
    required this.channelType,
    required this.channels,
    required this.duration,
    required this.threads,
    required this.totalUnreadCount,
    this.totalUnreadCountByTeam,
    required this.totalUnreadThreadsCount,
  });

  @override
  @JsonKey(name: 'channel_type')
  final List<UnreadCountsChannelType> channelType;

  @override
  @JsonKey(name: 'channels')
  final List<UnreadCountsChannel> channels;

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'threads')
  final List<UnreadCountsThread> threads;

  @override
  @JsonKey(name: 'total_unread_count')
  final int totalUnreadCount;

  @override
  @JsonKey(name: 'total_unread_count_by_team')
  final Map<String, int>? totalUnreadCountByTeam;

  @override
  @JsonKey(name: 'total_unread_threads_count')
  final int totalUnreadThreadsCount;

  Map<String, dynamic> toJson() => _$WrappedUnreadCountsResponseToJson(this);

  static WrappedUnreadCountsResponse fromJson(Map<String, dynamic> json) => _$WrappedUnreadCountsResponseFromJson(json);
}
