// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

abstract class WSClientEvent<T extends core.WsEvent> {
  const WSClientEvent(this.wrapped);

  final T wrapped;
  String get type;

  static WSClientEvent fromJson(Map<String, dynamic> json) {
    final eventType = json['type'];

    if (eventType == null || eventType is! String) {
      throw ArgumentError('Invalid or missing "type" field in JSON: $json');
    }

    return switch (eventType) {
      "*" => _CustomEvent(CustomEvent.fromJson(json)),
      "ai_indicator.clear" => _AIIndicatorClearEvent(AIIndicatorClearEvent.fromJson(json)),
      "ai_indicator.stop" => _AIIndicatorStopEvent(AIIndicatorStopEvent.fromJson(json)),
      "ai_indicator.update" => _AIIndicatorUpdateEvent(AIIndicatorUpdateEvent.fromJson(json)),
      "app.updated" => _AppUpdatedEvent(AppUpdatedEvent.fromJson(json)),
      "channel.created" => _ChannelCreatedEvent(ChannelCreatedEvent.fromJson(json)),
      "channel.deleted" => _ChannelDeletedEvent(ChannelDeletedEvent.fromJson(json)),
      "channel.frozen" => _ChannelFrozenEvent(ChannelFrozenEvent.fromJson(json)),
      "channel.hidden" => _ChannelHiddenEvent(ChannelHiddenEvent.fromJson(json)),
      "channel.kicked" => _ChannelKickedEvent(ChannelKickedEvent.fromJson(json)),
      "channel.max_streak_changed" => _MaxStreakChangedEvent(MaxStreakChangedEvent.fromJson(json)),
      "channel.truncated" => _ChannelTruncatedEvent(ChannelTruncatedEvent.fromJson(json)),
      "channel.unfrozen" => _ChannelUnFrozenEvent(ChannelUnFrozenEvent.fromJson(json)),
      "channel.updated" => _ChannelUpdatedEvent(ChannelUpdatedEvent.fromJson(json)),
      "channel.visible" => _ChannelVisibleEvent(ChannelVisibleEvent.fromJson(json)),
      "draft.deleted" => _DraftDeletedEvent(DraftDeletedEvent.fromJson(json)),
      "draft.updated" => _DraftUpdatedEvent(DraftUpdatedEvent.fromJson(json)),
      "member.added" => _MemberAddedEvent(MemberAddedEvent.fromJson(json)),
      "member.removed" => _MemberRemovedEvent(MemberRemovedEvent.fromJson(json)),
      "member.updated" => _MemberUpdatedEvent(MemberUpdatedEvent.fromJson(json)),
      "message.deleted" => _MessageDeletedEvent(MessageDeletedEvent.fromJson(json)),
      "message.delivered" => _MessageDeliveredEvent(MessageDeliveredEvent.fromJson(json)),
      "message.new" => _MessageNewEvent(MessageNewEvent.fromJson(json)),
      "message.pending" => _PendingMessageEvent(PendingMessageEvent.fromJson(json)),
      "message.read" => _MessageReadEvent(MessageReadEvent.fromJson(json)),
      "message.undeleted" => _MessageUndeletedEvent(MessageUndeletedEvent.fromJson(json)),
      "message.updated" => _MessageUpdatedEvent(MessageUpdatedEvent.fromJson(json)),
      "moderation.custom_action" => _ModerationCustomActionEvent(ModerationCustomActionEvent.fromJson(json)),
      "moderation.flagged" => _ModerationFlaggedEvent(ModerationFlaggedEvent.fromJson(json)),
      "moderation.mark_reviewed" => _ModerationMarkReviewedEvent(ModerationMarkReviewedEvent.fromJson(json)),
      "notification.added_to_channel" => _NotificationAddedToChannelEvent(
        NotificationAddedToChannelEvent.fromJson(json),
      ),
      "notification.channel_deleted" => _NotificationChannelDeletedEvent(
        NotificationChannelDeletedEvent.fromJson(json),
      ),
      "notification.channel_mutes_updated" => _NotificationChannelMutesUpdatedEvent(
        NotificationChannelMutesUpdatedEvent.fromJson(json),
      ),
      "notification.channel_truncated" => _NotificationChannelTruncatedEvent(
        NotificationChannelTruncatedEvent.fromJson(json),
      ),
      "notification.invite_accepted" => _NotificationInviteAcceptedEvent(
        NotificationInviteAcceptedEvent.fromJson(json),
      ),
      "notification.invite_rejected" => _NotificationInviteRejectedEvent(
        NotificationInviteRejectedEvent.fromJson(json),
      ),
      "notification.invited" => _NotificationInvitedEvent(NotificationInvitedEvent.fromJson(json)),
      "notification.mark_read" => _NotificationMarkReadEvent(NotificationMarkReadEvent.fromJson(json)),
      "notification.mark_unread" => _NotificationMarkUnreadEvent(NotificationMarkUnreadEvent.fromJson(json)),
      "notification.message_new" => _NotificationNewMessageEvent(NotificationNewMessageEvent.fromJson(json)),
      "notification.mutes_updated" => _NotificationMutesUpdatedEvent(NotificationMutesUpdatedEvent.fromJson(json)),
      "notification.reminder_due" => _ReminderNotificationEvent(ReminderNotificationEvent.fromJson(json)),
      "notification.removed_from_channel" => _NotificationRemovedFromChannelEvent(
        NotificationRemovedFromChannelEvent.fromJson(json),
      ),
      "notification.thread_message_new" => _NotificationThreadMessageNewEvent(
        NotificationThreadMessageNewEvent.fromJson(json),
      ),
      "poll.closed" => _PollClosedEvent(PollClosedEvent.fromJson(json)),
      "poll.deleted" => _PollDeletedEvent(PollDeletedEvent.fromJson(json)),
      "poll.updated" => _PollUpdatedEvent(PollUpdatedEvent.fromJson(json)),
      "poll.vote_casted" => _PollVoteCastedEvent(PollVoteCastedEvent.fromJson(json)),
      "poll.vote_changed" => _PollVoteChangedEvent(PollVoteChangedEvent.fromJson(json)),
      "poll.vote_removed" => _PollVoteRemovedEvent(PollVoteRemovedEvent.fromJson(json)),
      "reaction.deleted" => _ReactionDeletedEvent(ReactionDeletedEvent.fromJson(json)),
      "reaction.new" => _ReactionNewEvent(ReactionNewEvent.fromJson(json)),
      "reaction.updated" => _ReactionUpdatedEvent(ReactionUpdatedEvent.fromJson(json)),
      "reminder.created" => _ReminderCreatedEvent(ReminderCreatedEvent.fromJson(json)),
      "reminder.deleted" => _ReminderDeletedEvent(ReminderDeletedEvent.fromJson(json)),
      "reminder.updated" => _ReminderUpdatedEvent(ReminderUpdatedEvent.fromJson(json)),
      "thread.updated" => _ThreadUpdatedEvent(ThreadUpdatedEvent.fromJson(json)),
      "typing.start" => _TypingStartEvent(TypingStartEvent.fromJson(json)),
      "typing.stop" => _TypingStopEvent(TypingStopEvent.fromJson(json)),
      "user.banned" => _UserBannedEvent(UserBannedEvent.fromJson(json)),
      "user.deactivated" => _UserDeactivatedEvent(UserDeactivatedEvent.fromJson(json)),
      "user.deleted" => _UserDeletedEvent(UserDeletedEvent.fromJson(json)),
      "user.messages.deleted" => _UserMessagesDeletedEvent(UserMessagesDeletedEvent.fromJson(json)),
      "user.muted" => _UserMutedEvent(UserMutedEvent.fromJson(json)),
      "user.presence.changed" => _UserPresenceChangedEvent(UserPresenceChangedEvent.fromJson(json)),
      "user.reactivated" => _UserReactivatedEvent(UserReactivatedEvent.fromJson(json)),
      "user.unbanned" => _UserUnbannedEvent(UserUnbannedEvent.fromJson(json)),
      "user.updated" => _UserUpdatedEvent(UserUpdatedEvent.fromJson(json)),
      "user.watching.start" => _UserWatchingStartEvent(UserWatchingStartEvent.fromJson(json)),
      "user.watching.stop" => _UserWatchingStopEvent(UserWatchingStopEvent.fromJson(json)),
      "user_group.created" => _UserGroupCreatedEvent(UserGroupCreatedEvent.fromJson(json)),
      "user_group.deleted" => _UserGroupDeletedEvent(UserGroupDeletedEvent.fromJson(json)),
      "user_group.member_added" => _UserGroupMemberAddedEvent(UserGroupMemberAddedEvent.fromJson(json)),
      "user_group.member_removed" => _UserGroupMemberRemovedEvent(UserGroupMemberRemovedEvent.fromJson(json)),
      "user_group.updated" => _UserGroupUpdatedEvent(UserGroupUpdatedEvent.fromJson(json)),
      _ => _UnknownWSClientEvent(UnknownWSClientEvent(eventType, json)),
    };
  }
}

class _CustomEvent extends WSClientEvent<CustomEvent> {
  const _CustomEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _AIIndicatorClearEvent extends WSClientEvent<AIIndicatorClearEvent> {
  const _AIIndicatorClearEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _AIIndicatorStopEvent extends WSClientEvent<AIIndicatorStopEvent> {
  const _AIIndicatorStopEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _AIIndicatorUpdateEvent extends WSClientEvent<AIIndicatorUpdateEvent> {
  const _AIIndicatorUpdateEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _AppUpdatedEvent extends WSClientEvent<AppUpdatedEvent> {
  const _AppUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelCreatedEvent extends WSClientEvent<ChannelCreatedEvent> {
  const _ChannelCreatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelDeletedEvent extends WSClientEvent<ChannelDeletedEvent> {
  const _ChannelDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelFrozenEvent extends WSClientEvent<ChannelFrozenEvent> {
  const _ChannelFrozenEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelHiddenEvent extends WSClientEvent<ChannelHiddenEvent> {
  const _ChannelHiddenEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelKickedEvent extends WSClientEvent<ChannelKickedEvent> {
  const _ChannelKickedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MaxStreakChangedEvent extends WSClientEvent<MaxStreakChangedEvent> {
  const _MaxStreakChangedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelTruncatedEvent extends WSClientEvent<ChannelTruncatedEvent> {
  const _ChannelTruncatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelUnFrozenEvent extends WSClientEvent<ChannelUnFrozenEvent> {
  const _ChannelUnFrozenEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelUpdatedEvent extends WSClientEvent<ChannelUpdatedEvent> {
  const _ChannelUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelVisibleEvent extends WSClientEvent<ChannelVisibleEvent> {
  const _ChannelVisibleEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _DraftDeletedEvent extends WSClientEvent<DraftDeletedEvent> {
  const _DraftDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _DraftUpdatedEvent extends WSClientEvent<DraftUpdatedEvent> {
  const _DraftUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MemberAddedEvent extends WSClientEvent<MemberAddedEvent> {
  const _MemberAddedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MemberRemovedEvent extends WSClientEvent<MemberRemovedEvent> {
  const _MemberRemovedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MemberUpdatedEvent extends WSClientEvent<MemberUpdatedEvent> {
  const _MemberUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MessageDeletedEvent extends WSClientEvent<MessageDeletedEvent> {
  const _MessageDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MessageDeliveredEvent extends WSClientEvent<MessageDeliveredEvent> {
  const _MessageDeliveredEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MessageNewEvent extends WSClientEvent<MessageNewEvent> {
  const _MessageNewEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _PendingMessageEvent extends WSClientEvent<PendingMessageEvent> {
  const _PendingMessageEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MessageReadEvent extends WSClientEvent<MessageReadEvent> {
  const _MessageReadEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MessageUndeletedEvent extends WSClientEvent<MessageUndeletedEvent> {
  const _MessageUndeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MessageUpdatedEvent extends WSClientEvent<MessageUpdatedEvent> {
  const _MessageUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ModerationCustomActionEvent extends WSClientEvent<ModerationCustomActionEvent> {
  const _ModerationCustomActionEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ModerationFlaggedEvent extends WSClientEvent<ModerationFlaggedEvent> {
  const _ModerationFlaggedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ModerationMarkReviewedEvent extends WSClientEvent<ModerationMarkReviewedEvent> {
  const _ModerationMarkReviewedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationAddedToChannelEvent extends WSClientEvent<NotificationAddedToChannelEvent> {
  const _NotificationAddedToChannelEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationChannelDeletedEvent extends WSClientEvent<NotificationChannelDeletedEvent> {
  const _NotificationChannelDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationChannelMutesUpdatedEvent extends WSClientEvent<NotificationChannelMutesUpdatedEvent> {
  const _NotificationChannelMutesUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationChannelTruncatedEvent extends WSClientEvent<NotificationChannelTruncatedEvent> {
  const _NotificationChannelTruncatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationInviteAcceptedEvent extends WSClientEvent<NotificationInviteAcceptedEvent> {
  const _NotificationInviteAcceptedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationInviteRejectedEvent extends WSClientEvent<NotificationInviteRejectedEvent> {
  const _NotificationInviteRejectedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationInvitedEvent extends WSClientEvent<NotificationInvitedEvent> {
  const _NotificationInvitedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationMarkReadEvent extends WSClientEvent<NotificationMarkReadEvent> {
  const _NotificationMarkReadEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationMarkUnreadEvent extends WSClientEvent<NotificationMarkUnreadEvent> {
  const _NotificationMarkUnreadEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationNewMessageEvent extends WSClientEvent<NotificationNewMessageEvent> {
  const _NotificationNewMessageEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationMutesUpdatedEvent extends WSClientEvent<NotificationMutesUpdatedEvent> {
  const _NotificationMutesUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ReminderNotificationEvent extends WSClientEvent<ReminderNotificationEvent> {
  const _ReminderNotificationEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationRemovedFromChannelEvent extends WSClientEvent<NotificationRemovedFromChannelEvent> {
  const _NotificationRemovedFromChannelEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationThreadMessageNewEvent extends WSClientEvent<NotificationThreadMessageNewEvent> {
  const _NotificationThreadMessageNewEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _PollClosedEvent extends WSClientEvent<PollClosedEvent> {
  const _PollClosedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _PollDeletedEvent extends WSClientEvent<PollDeletedEvent> {
  const _PollDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _PollUpdatedEvent extends WSClientEvent<PollUpdatedEvent> {
  const _PollUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _PollVoteCastedEvent extends WSClientEvent<PollVoteCastedEvent> {
  const _PollVoteCastedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _PollVoteChangedEvent extends WSClientEvent<PollVoteChangedEvent> {
  const _PollVoteChangedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _PollVoteRemovedEvent extends WSClientEvent<PollVoteRemovedEvent> {
  const _PollVoteRemovedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ReactionDeletedEvent extends WSClientEvent<ReactionDeletedEvent> {
  const _ReactionDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ReactionNewEvent extends WSClientEvent<ReactionNewEvent> {
  const _ReactionNewEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ReactionUpdatedEvent extends WSClientEvent<ReactionUpdatedEvent> {
  const _ReactionUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ReminderCreatedEvent extends WSClientEvent<ReminderCreatedEvent> {
  const _ReminderCreatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ReminderDeletedEvent extends WSClientEvent<ReminderDeletedEvent> {
  const _ReminderDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ReminderUpdatedEvent extends WSClientEvent<ReminderUpdatedEvent> {
  const _ReminderUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ThreadUpdatedEvent extends WSClientEvent<ThreadUpdatedEvent> {
  const _ThreadUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _TypingStartEvent extends WSClientEvent<TypingStartEvent> {
  const _TypingStartEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _TypingStopEvent extends WSClientEvent<TypingStopEvent> {
  const _TypingStopEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserBannedEvent extends WSClientEvent<UserBannedEvent> {
  const _UserBannedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserDeactivatedEvent extends WSClientEvent<UserDeactivatedEvent> {
  const _UserDeactivatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserDeletedEvent extends WSClientEvent<UserDeletedEvent> {
  const _UserDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserMessagesDeletedEvent extends WSClientEvent<UserMessagesDeletedEvent> {
  const _UserMessagesDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserMutedEvent extends WSClientEvent<UserMutedEvent> {
  const _UserMutedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserPresenceChangedEvent extends WSClientEvent<UserPresenceChangedEvent> {
  const _UserPresenceChangedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserReactivatedEvent extends WSClientEvent<UserReactivatedEvent> {
  const _UserReactivatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserUnbannedEvent extends WSClientEvent<UserUnbannedEvent> {
  const _UserUnbannedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserUpdatedEvent extends WSClientEvent<UserUpdatedEvent> {
  const _UserUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserWatchingStartEvent extends WSClientEvent<UserWatchingStartEvent> {
  const _UserWatchingStartEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserWatchingStopEvent extends WSClientEvent<UserWatchingStopEvent> {
  const _UserWatchingStopEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserGroupCreatedEvent extends WSClientEvent<UserGroupCreatedEvent> {
  const _UserGroupCreatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserGroupDeletedEvent extends WSClientEvent<UserGroupDeletedEvent> {
  const _UserGroupDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserGroupMemberAddedEvent extends WSClientEvent<UserGroupMemberAddedEvent> {
  const _UserGroupMemberAddedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserGroupMemberRemovedEvent extends WSClientEvent<UserGroupMemberRemovedEvent> {
  const _UserGroupMemberRemovedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserGroupUpdatedEvent extends WSClientEvent<UserGroupUpdatedEvent> {
  const _UserGroupUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UnknownWSClientEvent extends WSClientEvent<UnknownWSClientEvent> {
  const _UnknownWSClientEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class UnknownWSClientEvent extends core.WsEvent {
  const UnknownWSClientEvent(this.type, this.rawJson);

  final String type;
  final Map<String, Object?> rawJson;
}
