// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

abstract class WSEvent<T extends core.WsEvent> {
  const WSEvent(this.wrapped);

  final T wrapped;
  String get type;

  static WSEvent fromJson(Map<String, dynamic> json) {
    final eventType = json['type'];

    if (eventType == null || eventType is! String) {
      throw ArgumentError('Invalid or missing "type" field in JSON: $json');
    }

    return switch (eventType) {
      "*" => _CustomEvent(CustomEvent.fromJson(json)),
      "ai_indicator.clear" => _AIIndicatorClearEvent(AIIndicatorClearEvent.fromJson(json)),
      "ai_indicator.stop" => _AIIndicatorStopEvent(AIIndicatorStopEvent.fromJson(json)),
      "ai_indicator.update" => _AIIndicatorUpdateEvent(AIIndicatorUpdateEvent.fromJson(json)),
      "app.updated" => _AppUpdatedEvent(AppUpdatedEvent.fromJson(json)),
      "channel.created" => _ChannelCreatedEvent(ChannelCreatedEvent.fromJson(json)),
      "channel.deleted" => _ChannelDeletedEvent(ChannelDeletedEvent.fromJson(json)),
      "channel.frozen" => _ChannelFrozenEvent(ChannelFrozenEvent.fromJson(json)),
      "channel.hidden" => _ChannelHiddenEvent(ChannelHiddenEvent.fromJson(json)),
      "channel.kicked" => _ChannelKickedEvent(ChannelKickedEvent.fromJson(json)),
      "channel.max_streak_changed" => _MaxStreakChangedEvent(MaxStreakChangedEvent.fromJson(json)),
      "channel.truncated" => _ChannelTruncatedEvent(ChannelTruncatedEvent.fromJson(json)),
      "channel.unfrozen" => _ChannelUnFrozenEvent(ChannelUnFrozenEvent.fromJson(json)),
      "channel.updated" => _ChannelUpdatedEvent(ChannelUpdatedEvent.fromJson(json)),
      "channel.visible" => _ChannelVisibleEvent(ChannelVisibleEvent.fromJson(json)),
      "draft.deleted" => _DraftDeletedEvent(DraftDeletedEvent.fromJson(json)),
      "draft.updated" => _DraftUpdatedEvent(DraftUpdatedEvent.fromJson(json)),
      "member.added" => _MemberAddedEvent(MemberAddedEvent.fromJson(json)),
      "member.removed" => _MemberRemovedEvent(MemberRemovedEvent.fromJson(json)),
      "member.updated" => _MemberUpdatedEvent(MemberUpdatedEvent.fromJson(json)),
      "message.deleted" => _MessageDeletedEvent(MessageDeletedEvent.fromJson(json)),
      "message.delivered" => _MessageDeliveredEvent(MessageDeliveredEvent.fromJson(json)),
      "message.new" => _MessageNewEvent(MessageNewEvent.fromJson(json)),
      "message.pending" => _PendingMessageEvent(PendingMessageEvent.fromJson(json)),
      "message.read" => _MessageReadEvent(MessageReadEvent.fromJson(json)),
      "message.undeleted" => _MessageUndeletedEvent(MessageUndeletedEvent.fromJson(json)),
      "message.updated" => _MessageUpdatedEvent(MessageUpdatedEvent.fromJson(json)),
      "moderation.custom_action" => _ModerationCustomActionEvent(ModerationCustomActionEvent.fromJson(json)),
      "moderation.flagged" => _ModerationFlaggedEvent(ModerationFlaggedEvent.fromJson(json)),
      "moderation.mark_reviewed" => _ModerationMarkReviewedEvent(ModerationMarkReviewedEvent.fromJson(json)),
      "notification.added_to_channel" => _NotificationAddedToChannelEvent(
        NotificationAddedToChannelEvent.fromJson(json),
      ),
      "notification.channel_deleted" => _NotificationChannelDeletedEvent(
        NotificationChannelDeletedEvent.fromJson(json),
      ),
      "notification.channel_mutes_updated" => _NotificationChannelMutesUpdatedEvent(
        NotificationChannelMutesUpdatedEvent.fromJson(json),
      ),
      "notification.channel_truncated" => _NotificationChannelTruncatedEvent(
        NotificationChannelTruncatedEvent.fromJson(json),
      ),
      "notification.invite_accepted" => _NotificationInviteAcceptedEvent(
        NotificationInviteAcceptedEvent.fromJson(json),
      ),
      "notification.invite_rejected" => _NotificationInviteRejectedEvent(
        NotificationInviteRejectedEvent.fromJson(json),
      ),
      "notification.invited" => _NotificationInvitedEvent(NotificationInvitedEvent.fromJson(json)),
      "notification.mark_read" => _NotificationMarkReadEvent(NotificationMarkReadEvent.fromJson(json)),
      "notification.mark_unread" => _NotificationMarkUnreadEvent(NotificationMarkUnreadEvent.fromJson(json)),
      "notification.message_new" => _NotificationNewMessageEvent(NotificationNewMessageEvent.fromJson(json)),
      "notification.mutes_updated" => _NotificationMutesUpdatedEvent(NotificationMutesUpdatedEvent.fromJson(json)),
      "notification.reminder_due" => _ReminderNotificationEvent(ReminderNotificationEvent.fromJson(json)),
      "notification.removed_from_channel" => _NotificationRemovedFromChannelEvent(
        NotificationRemovedFromChannelEvent.fromJson(json),
      ),
      "notification.thread_message_new" => _NotificationThreadMessageNewEvent(
        NotificationThreadMessageNewEvent.fromJson(json),
      ),
      "poll.closed" => _PollClosedEvent(PollClosedEvent.fromJson(json)),
      "poll.deleted" => _PollDeletedEvent(PollDeletedEvent.fromJson(json)),
      "poll.updated" => _PollUpdatedEvent(PollUpdatedEvent.fromJson(json)),
      "poll.vote_casted" => _PollVoteCastedEvent(PollVoteCastedEvent.fromJson(json)),
      "poll.vote_changed" => _PollVoteChangedEvent(PollVoteChangedEvent.fromJson(json)),
      "poll.vote_removed" => _PollVoteRemovedEvent(PollVoteRemovedEvent.fromJson(json)),
      "reaction.deleted" => _ReactionDeletedEvent(ReactionDeletedEvent.fromJson(json)),
      "reaction.new" => _ReactionNewEvent(ReactionNewEvent.fromJson(json)),
      "reaction.updated" => _ReactionUpdatedEvent(ReactionUpdatedEvent.fromJson(json)),
      "reminder.created" => _ReminderCreatedEvent(ReminderCreatedEvent.fromJson(json)),
      "reminder.deleted" => _ReminderDeletedEvent(ReminderDeletedEvent.fromJson(json)),
      "reminder.updated" => _ReminderUpdatedEvent(ReminderUpdatedEvent.fromJson(json)),
      "thread.updated" => _ThreadUpdatedEvent(ThreadUpdatedEvent.fromJson(json)),
      "typing.start" => _TypingStartEvent(TypingStartEvent.fromJson(json)),
      "typing.stop" => _TypingStopEvent(TypingStopEvent.fromJson(json)),
      "user.banned" => _UserBannedEvent(UserBannedEvent.fromJson(json)),
      "user.deactivated" => _UserDeactivatedEvent(UserDeactivatedEvent.fromJson(json)),
      "user.deleted" => _UserDeletedEvent(UserDeletedEvent.fromJson(json)),
      "user.messages.deleted" => _UserMessagesDeletedEvent(UserMessagesDeletedEvent.fromJson(json)),
      "user.muted" => _UserMutedEvent(UserMutedEvent.fromJson(json)),
      "user.presence.changed" => _UserPresenceChangedEvent(UserPresenceChangedEvent.fromJson(json)),
      "user.reactivated" => _UserReactivatedEvent(UserReactivatedEvent.fromJson(json)),
      "user.unbanned" => _UserUnbannedEvent(UserUnbannedEvent.fromJson(json)),
      "user.updated" => _UserUpdatedEvent(UserUpdatedEvent.fromJson(json)),
      "user.watching.start" => _UserWatchingStartEvent(UserWatchingStartEvent.fromJson(json)),
      "user.watching.stop" => _UserWatchingStopEvent(UserWatchingStopEvent.fromJson(json)),
      "user_group.created" => _UserGroupCreatedEvent(UserGroupCreatedEvent.fromJson(json)),
      "user_group.deleted" => _UserGroupDeletedEvent(UserGroupDeletedEvent.fromJson(json)),
      "user_group.member_added" => _UserGroupMemberAddedEvent(UserGroupMemberAddedEvent.fromJson(json)),
      "user_group.member_removed" => _UserGroupMemberRemovedEvent(UserGroupMemberRemovedEvent.fromJson(json)),
      "user_group.updated" => _UserGroupUpdatedEvent(UserGroupUpdatedEvent.fromJson(json)),
      _ => _UnknownWSEvent(UnknownWSEvent(eventType, json)),
    };
  }
}

class _CustomEvent extends WSEvent<CustomEvent> {
  const _CustomEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _AIIndicatorClearEvent extends WSEvent<AIIndicatorClearEvent> {
  const _AIIndicatorClearEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _AIIndicatorStopEvent extends WSEvent<AIIndicatorStopEvent> {
  const _AIIndicatorStopEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _AIIndicatorUpdateEvent extends WSEvent<AIIndicatorUpdateEvent> {
  const _AIIndicatorUpdateEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _AppUpdatedEvent extends WSEvent<AppUpdatedEvent> {
  const _AppUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelCreatedEvent extends WSEvent<ChannelCreatedEvent> {
  const _ChannelCreatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelDeletedEvent extends WSEvent<ChannelDeletedEvent> {
  const _ChannelDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelFrozenEvent extends WSEvent<ChannelFrozenEvent> {
  const _ChannelFrozenEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelHiddenEvent extends WSEvent<ChannelHiddenEvent> {
  const _ChannelHiddenEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelKickedEvent extends WSEvent<ChannelKickedEvent> {
  const _ChannelKickedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MaxStreakChangedEvent extends WSEvent<MaxStreakChangedEvent> {
  const _MaxStreakChangedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelTruncatedEvent extends WSEvent<ChannelTruncatedEvent> {
  const _ChannelTruncatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelUnFrozenEvent extends WSEvent<ChannelUnFrozenEvent> {
  const _ChannelUnFrozenEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelUpdatedEvent extends WSEvent<ChannelUpdatedEvent> {
  const _ChannelUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ChannelVisibleEvent extends WSEvent<ChannelVisibleEvent> {
  const _ChannelVisibleEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _DraftDeletedEvent extends WSEvent<DraftDeletedEvent> {
  const _DraftDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _DraftUpdatedEvent extends WSEvent<DraftUpdatedEvent> {
  const _DraftUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MemberAddedEvent extends WSEvent<MemberAddedEvent> {
  const _MemberAddedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MemberRemovedEvent extends WSEvent<MemberRemovedEvent> {
  const _MemberRemovedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MemberUpdatedEvent extends WSEvent<MemberUpdatedEvent> {
  const _MemberUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MessageDeletedEvent extends WSEvent<MessageDeletedEvent> {
  const _MessageDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MessageDeliveredEvent extends WSEvent<MessageDeliveredEvent> {
  const _MessageDeliveredEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MessageNewEvent extends WSEvent<MessageNewEvent> {
  const _MessageNewEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _PendingMessageEvent extends WSEvent<PendingMessageEvent> {
  const _PendingMessageEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MessageReadEvent extends WSEvent<MessageReadEvent> {
  const _MessageReadEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MessageUndeletedEvent extends WSEvent<MessageUndeletedEvent> {
  const _MessageUndeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _MessageUpdatedEvent extends WSEvent<MessageUpdatedEvent> {
  const _MessageUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ModerationCustomActionEvent extends WSEvent<ModerationCustomActionEvent> {
  const _ModerationCustomActionEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ModerationFlaggedEvent extends WSEvent<ModerationFlaggedEvent> {
  const _ModerationFlaggedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ModerationMarkReviewedEvent extends WSEvent<ModerationMarkReviewedEvent> {
  const _ModerationMarkReviewedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationAddedToChannelEvent extends WSEvent<NotificationAddedToChannelEvent> {
  const _NotificationAddedToChannelEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationChannelDeletedEvent extends WSEvent<NotificationChannelDeletedEvent> {
  const _NotificationChannelDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationChannelMutesUpdatedEvent extends WSEvent<NotificationChannelMutesUpdatedEvent> {
  const _NotificationChannelMutesUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationChannelTruncatedEvent extends WSEvent<NotificationChannelTruncatedEvent> {
  const _NotificationChannelTruncatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationInviteAcceptedEvent extends WSEvent<NotificationInviteAcceptedEvent> {
  const _NotificationInviteAcceptedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationInviteRejectedEvent extends WSEvent<NotificationInviteRejectedEvent> {
  const _NotificationInviteRejectedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationInvitedEvent extends WSEvent<NotificationInvitedEvent> {
  const _NotificationInvitedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationMarkReadEvent extends WSEvent<NotificationMarkReadEvent> {
  const _NotificationMarkReadEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationMarkUnreadEvent extends WSEvent<NotificationMarkUnreadEvent> {
  const _NotificationMarkUnreadEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationNewMessageEvent extends WSEvent<NotificationNewMessageEvent> {
  const _NotificationNewMessageEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationMutesUpdatedEvent extends WSEvent<NotificationMutesUpdatedEvent> {
  const _NotificationMutesUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ReminderNotificationEvent extends WSEvent<ReminderNotificationEvent> {
  const _ReminderNotificationEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationRemovedFromChannelEvent extends WSEvent<NotificationRemovedFromChannelEvent> {
  const _NotificationRemovedFromChannelEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _NotificationThreadMessageNewEvent extends WSEvent<NotificationThreadMessageNewEvent> {
  const _NotificationThreadMessageNewEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _PollClosedEvent extends WSEvent<PollClosedEvent> {
  const _PollClosedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _PollDeletedEvent extends WSEvent<PollDeletedEvent> {
  const _PollDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _PollUpdatedEvent extends WSEvent<PollUpdatedEvent> {
  const _PollUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _PollVoteCastedEvent extends WSEvent<PollVoteCastedEvent> {
  const _PollVoteCastedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _PollVoteChangedEvent extends WSEvent<PollVoteChangedEvent> {
  const _PollVoteChangedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _PollVoteRemovedEvent extends WSEvent<PollVoteRemovedEvent> {
  const _PollVoteRemovedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ReactionDeletedEvent extends WSEvent<ReactionDeletedEvent> {
  const _ReactionDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ReactionNewEvent extends WSEvent<ReactionNewEvent> {
  const _ReactionNewEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ReactionUpdatedEvent extends WSEvent<ReactionUpdatedEvent> {
  const _ReactionUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ReminderCreatedEvent extends WSEvent<ReminderCreatedEvent> {
  const _ReminderCreatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ReminderDeletedEvent extends WSEvent<ReminderDeletedEvent> {
  const _ReminderDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ReminderUpdatedEvent extends WSEvent<ReminderUpdatedEvent> {
  const _ReminderUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ThreadUpdatedEvent extends WSEvent<ThreadUpdatedEvent> {
  const _ThreadUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _TypingStartEvent extends WSEvent<TypingStartEvent> {
  const _TypingStartEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _TypingStopEvent extends WSEvent<TypingStopEvent> {
  const _TypingStopEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserBannedEvent extends WSEvent<UserBannedEvent> {
  const _UserBannedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserDeactivatedEvent extends WSEvent<UserDeactivatedEvent> {
  const _UserDeactivatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserDeletedEvent extends WSEvent<UserDeletedEvent> {
  const _UserDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserMessagesDeletedEvent extends WSEvent<UserMessagesDeletedEvent> {
  const _UserMessagesDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserMutedEvent extends WSEvent<UserMutedEvent> {
  const _UserMutedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserPresenceChangedEvent extends WSEvent<UserPresenceChangedEvent> {
  const _UserPresenceChangedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserReactivatedEvent extends WSEvent<UserReactivatedEvent> {
  const _UserReactivatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserUnbannedEvent extends WSEvent<UserUnbannedEvent> {
  const _UserUnbannedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserUpdatedEvent extends WSEvent<UserUpdatedEvent> {
  const _UserUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserWatchingStartEvent extends WSEvent<UserWatchingStartEvent> {
  const _UserWatchingStartEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserWatchingStopEvent extends WSEvent<UserWatchingStopEvent> {
  const _UserWatchingStopEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserGroupCreatedEvent extends WSEvent<UserGroupCreatedEvent> {
  const _UserGroupCreatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserGroupDeletedEvent extends WSEvent<UserGroupDeletedEvent> {
  const _UserGroupDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserGroupMemberAddedEvent extends WSEvent<UserGroupMemberAddedEvent> {
  const _UserGroupMemberAddedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserGroupMemberRemovedEvent extends WSEvent<UserGroupMemberRemovedEvent> {
  const _UserGroupMemberRemovedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserGroupUpdatedEvent extends WSEvent<UserGroupUpdatedEvent> {
  const _UserGroupUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UnknownWSEvent extends WSEvent<UnknownWSEvent> {
  const _UnknownWSEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class UnknownWSEvent extends core.WsEvent {
  const UnknownWSEvent(this.type, this.rawJson);

  final String type;
  final Map<String, Object?> rawJson;
}

WSEvent wsEventFromJson(Map<String, dynamic> json) => WSEvent.fromJson(json);

Map<String, dynamic> wsEventToJson(WSEvent event) => (event.wrapped as dynamic).toJson() as Map<String, dynamic>;

List<WSEvent> wsEventListFromJson(List<dynamic> json) =>
    json.map((e) => wsEventFromJson(e as Map<String, dynamic>)).toList();

List<Map<String, dynamic>> wsEventListToJson(List<WSEvent> events) => events.map(wsEventToJson).toList();
