name: update_goldens

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Which goldens to update"
        required: true
        type: choice
        default: sdk
        options:
          - sdk
          - docs

jobs:
  update_sdk_goldens:
    if: inputs.target == 'sdk'
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Checkout branch
        uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}

      - name: 🐦 Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: stable
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: 📦 Install Tools
        run: flutter pub global activate melos

      - name: 🔧 Bootstrap Workspace
        run: melos bootstrap --verbose

      - name: 🖼️ Update SDK Goldens
        continue-on-error: true
        run: melos run update:goldens:sdk

      - name: 📤 Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: Update SDK Goldens"
          file_pattern: "packages/**/test/**/goldens/**/*.png"
          commit_user_name: "Stream SDK Bot"
          commit_user_email: "60655709+Stream-SDK-Bot@users.noreply.github.com"

  update_docs_goldens:
    if: inputs.target == 'docs'
    runs-on: macos-latest
    steps:
      - name: 📚 Checkout branch
        uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.BOT_SSH_PRIVATE_KEY }}

      - name: 🐦 Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: stable
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: 📦 Install Tools
        run: flutter pub global activate melos

      - name: 🔧 Bootstrap Workspace
        run: melos bootstrap --verbose

      - name: 🖼️ Update Docs Goldens
        continue-on-error: true
        run: melos run update:goldens:docs

      - name: 📤 Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: Update Docs Snapshots"
          file_pattern: "docs/**/test/**/goldens/macos/*.png"
          commit_user_name: "Stream SDK Bot"
          commit_user_email: "60655709+Stream-SDK-Bot@users.noreply.github.com"
